### ISSUE TITLE
Replace @mui/styles with @mui/system

### ISSUE THREAD

**Issue by ro7584** [mui-org/material-ui-x#1234] opened 2021-03-15 15:37 UTC
Hi ~

I was wondering if it could add `@material-ui/styles` as dependency for the `@material-ui/grid`?
The file below was included by `@material-ui/data-grid`, but missing in [package.json](https://github.com/mui-org/material-ui-x/blob/v4.0.0-alpha.22/packages/grid/data-grid/package.json).
https://github.com/mui-org/material-ui-x/blob/v4.0.0-alpha.22/packages/grid/_modules_/grid/utils/material-ui-utils.ts#L3

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

**Comment by oliviertassinari** [comment] 2021-03-16 22:28
@ro7584 Interesting. This import is strictly speaking wrong. 

https://github.com/mui-org/material-ui-x/blob/32fbaf095a0cc4391c248253b3a02e354f8f8ff2/packages/grid/_modules_/grid/utils/material-ui-utils.ts#L3

We are not allowed to import from this package. Only from the core.

As you can see, it's getting resolved with 

https://github.com/mui-org/material-ui-x/blob/32fbaf095a0cc4391c248253b3a02e354f8f8ff2/packages/grid/_modules_/grid/utils/material-ui-utils.ts#L15-L16

Now, the problem is that `@material-ui/styles` is a singleton. If we add it as a dependency to the data grid, it could lead to hard to debug CSS rendering issue. I would recommend we simply snooze the issue until we push #441 further (drop v4 support).

Are you facing a specific issue?

**Comment by ro7584** [comment] 2021-03-17 13:23
You're right.   
Recently, I'm trying to use [Plug'n'Play](https://yarnpkg.com/features/pnp) and get `@material-ui/style` resolved error at webpack dev server.

Glad to know that it's getting resolved in v5.
Feel free to snooze this issue. 👍

**Comment by bclehmann** [comment] 2021-07-14 21:33
It might be worth noting that Material 5 is not actually supported. On [NPM ](https://www.npmjs.com/package/@material-ui/data-grid) it says that you can use DataGrid with Material 5 when in fact you cannot.

**Comment by oliviertassinari** [comment] 2021-07-14 21:58
@bclehmann It's supported, but there are a few limitations, like this one that can be workedaround.

**Comment by bclehmann** [comment] 2021-07-14 22:11
I'm not sure that it makes sense to call it a limitation if merely importing the module will prevent compilation.

I don't think that you can say Material 5 is supported if it requires non-standard (and undocumented) changes to package resolution. And it's probably not supported if the current plan is to not add support until Material 5 leaves beta.

**Comment by oliviertassinari** [comment] 2021-07-14 22:18
@bclehmann Please provide a reproduction, a working demo with core v5: https://codesandbox.io/s/material-demo-forked-93pqu.

**Comment by oliviertassinari** [comment] 2021-08-16 14:41
The idea on this issue is to have `@material-ui/data-grid` rely on `@material-ui/system@v5.0.0-beta.4` (emotion) so we can drop the usage of `@material-ui/styles@v4` (JSS). It's about optimizing for v5 users while keeping some degraded support for v4.

**Comment by m4theushw** [comment] 2021-09-20 16:50
I've renamed the title to reuse this issue for the migration to @mui/system. We could investigate how complex would be to lower the specificity with the new API. Related to https://github.com/mui-org/material-ui-x/issues/99#issue-664397461

The goal is to be able to override styles with `.MuiDataGrid-columnHeader`, instead of `.MuiDataGrid-root .MuiDataGrid-columnHeader`.

https://github.com/mui-org/material-ui-x/blob/68ae5d5d477500ba56564df10a215eb7ad2e22d9/packages/grid/_modules_/grid/components/containers/GridRootStyles.ts#L99

**Comment by trickreich** [comment] 2021-09-22 12:04
I can't folow.. what's status quo? is @mui/styles going to be removed?

**Comment by m4theushw** [comment] 2021-10-01 13:58
> I can't folow.. what's status quo? is @mui/styles going to be removed?

@trickreich The @mui/styles package is the JSS-based styling solution used in MUI Core v4, but removed in v5, in place of emotion. Since it's legacy now, users need to have both styling packages to be able to use the DataGrid. Our plan is to remove the legacy package and use emotion only (with support for `sx` prop), like is done in the core.

**Comment by oliviertassinari** [comment] 2022-01-07 20:33
I'm reopening as `@mui/styles` is still present in the dependencies of this monorepo:
https://github.com/mui-org/material-ui-x/blob/b7fb0169f74cec58817e85ff167d197a244d6652/package.json#L72

And, we even have demos using it, it's misleading:

https://github.com/mui-org/material-ui-x/blob/6efc5f9f6f49e9a0566e048b2358cf204abc5753/docs/src/pages/components/data-grid/events/CatalogOfEventsNoSnap.js#L13

**Comment by oliviertassinari** [comment] 2022-01-07 20:37
My bad: https://github.com/mui-org/material-ui-x/issues/2991

**Closed by oliviertassinari** 2022-01-07 20:37 UTC
Labels: docs, core, component: DataGrid
