### ISSUE TITLE
Error sorting: column with field 'x' not found.

### ISSUE THREAD

**Issue by shivananda-sahu** [mui-org/material-ui-x#892] opened 2021-01-21 16:36 UTC
Error sorting: column with field 'username' not found.

When sorting is applied to xgrid, and then new data is loaded to xgrid - render fails with `Error sorting: column with field 'x' not found.`

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

- Load xgrid with data
- Sort on a column
- Load new data into xgrid (new set of columns and rows)
- See error: `Error sorting: column with field 'x' not found.`

## Expected Behavior 🤔

- Load xgrid with data
- Sort on a column
- Load new data into xgrid (new set of columns and rows)
- Sorting should be cleared and new data is rendered

## Workaround

- Use apiref to clear the sort model before loading new data.
- `apiRef.current.setSortModel([])`
- Although the workaround works - would have expected this to happen automatically when the columns are being reset/changed.

[Link to reproduce issue in codesandbox](https://codesandbox.io/s/material-demo-forked-c75ps?file=/demo.js )
Steps:

1.Load page
2.Sort on the username column (within 10s of the page load)
3.Page errors out

## Context 🔦

- We use xgrid to load different related reports.
- Although the structure is similar for most of these - the actual columns can differ - and some reports have extra columns in them.
- If sorting happens on a column that does not exist in another dataset - xgrid fails to render.

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  Browser used : Chrome
  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 40.82 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.19.0 - ~/.nvm/versions/node/v12.19.0/bin/node
    Yarn: 1.22.5 - /usr/local/Cellar/yvm/4.1.1/shim/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.19.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
    Homebrew: 2.7.5 - /usr/local/bin/brew
    pip3: 20.3.3 - ~/.pyenv/shims/pip3
    RubyGems: 3.0.3 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.24.3 - /usr/bin/git
    Clang: 1200.0.32.28 - /usr/bin/clang
  Servers:
    Apache: 2.4.41 - /usr/sbin/apachectl
  Virtualization:
    Docker: 20.10.2 - /usr/local/bin/docker
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Nano: 2.0.6 - /usr/bin/nano
    VSCode: 1.52.1 - /usr/local/bin/code
    Vim: 8.1 - /usr/bin/vim
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 11.0.9.1 - /Users/shivananda.sahu/.jenv/shims/javac
    Perl: 5.18.4 - /usr/bin/perl
    PHP: 7.3.11 - /usr/bin/php
    Python: 3.7.9 - /Users/shivananda.sahu/.pyenv/shims/python
    Python3: 3.7.9 - /Users/shivananda.sahu/.pyenv/shims/python3
    Ruby: 2.6.3 - /usr/bin/ruby
  Databases:
    PostgreSQL: 10.15 - /usr/local/opt/postgresql@10/bin/postgres
    SQLite: 3.28.0 - /usr/bin/sqlite3
  Browsers:
    Chrome: 88.0.4324.96
    Safari: 14.0.2
```
</details>

**Comment by oliviertassinari** [comment] 2021-01-23 00:45
@shivananda-sahu I can't reproduce the error on your codesandbox. Is it reproducing on your end?

**Comment by oliviertassinari** [comment] 2021-01-25 11:09
@shivananda-sahu I'm closing for now, if you can update the codesandbox to demonstrate the issue, it would be great

**Closed by oliviertassinari** 2021-01-25 11:09 UTC
Labels: status: incomplete
