### ISSUE TITLE
[DataGrid] Filter panel should show the field filters when opened from a specific column

### ISSUE THREAD

**Issue by zehawki** [mui-org/material-ui-x#2272] opened 2021-08-02 09:01 UTC
Clicking on the column overflow menu and selecting "filter" should show that field in filter box (rather than the 1st by default)

[x ] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

Please excuse me if this has been reported already - I was not able to find via various searches.

## Summary 💡

Eg here: https://material-ui.com/components/data-grid/filtering/#basic-filter

When one filters from the toolbar, then the field that's selected can be (by default) "id" since that's usually the 1st field.

![image](https://user-images.githubusercontent.com/8095144/127833969-3f03432a-0171-43ef-aca4-819e1633da3d.png)

But when one filters via a column:

![image](https://user-images.githubusercontent.com/8095144/127834070-c8319cee-da88-47b2-82d8-ea254b9e4ec9.png)

Then the field that shows up could be the relevant field, like this (instead of 1st field, id)

![image](https://user-images.githubusercontent.com/8095144/127834213-f4df18ed-957b-4f47-80b1-5c05ffdd3184.png)

**Comment by flaviendelangle** [comment] 2021-08-02 09:06
Relates to #1777 
We have a broader UX issue with the filters that needs to be addressed

**Comment by oliviertassinari** [comment] 2021-08-06 21:58
@flaviendelangle Yes, it's the exact same UX problem as in #1777 with the column menu and the filter.

**Comment by oliviertassinari** [comment] 2021-08-06 21:59
Duplicate of #1777

**Closed by oliviertassinari** 2021-08-06 21:59 UTC
Labels: bug 🐛, component: DataGrid
