### ISSUE TITLE
[DataGridPro] `GridPagination` does not update when instantiated several times

### ISSUE THREAD

**Issue by lizsaloka1** [mui-org/material-ui-x#3129] opened 2021-11-08 14:59 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

For my application, I have been using the DataGridPro `<GridFooter />` to include pagination at both the top of the table (Toolbar) and the bottom of the table (Footer). When one pagination component updates, the table updates correctly, but the other pagination component still shows the old configuration.

Ex- If I change the top pagination to 50 rowsPerPage from 25, the top pagination will now show 50 and the table will show the correct number of rows. However, the bottom pagination component is outdated and still shows 25 rowsPerPage, although the table is now displaying 50.

### Expected behavior 🤔

Both pagination components (top and bottom) should be in sync- when one changes, the other should change as well.

### Steps to reproduce 🕹

Steps:

1. Using DataGridPro, create a DataGrid table that uses `<GridFooter/>` in both the Toolbar and Footer
2. Populate the table with enough data so that you can change the number of rowsPerPage & the current page
3. Modify one of the pagination components (top or bottom, either will reproduce)
4. Notice that the other pagination component (that was untouched) now shows out-of-date information

### Context 🔦

Our application has always had top and bottom pagination for tables, it is easier for users to navigate through tables this way. Although this bug is rather minor, having pagination in sync will result in a cleaner, more trustworthy product that our users will want to use. If the user is deciding to display 50 or 100 rowsPerPage, it is easier to work with the table data if they have the option to change pages/row size at the top and bottom of the table, rather than having to scroll to the opposite end. Also, if we display pagination only at the bottom of the table, it might not be intuitive that this table has more data / the ability to paginate, as the user will need to scroll to the bottom in order to see it.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Using Chrome browser Version 95.0.4638.54 (Official Build) (x86_64)

  System:
    OS: macOS 11.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 4.37 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
  Managers:
    Homebrew: 3.2.2 - /usr/local/bin/brew
    Maven: 3.8.1 - ~/Downloads/apache-maven-3.8.1/bin/mvn
    pip3: 20.2.3 - /usr/bin/pip3
    RubyGems: 3.0.3 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.30.1 - /usr/bin/git
    Clang: 13.0.0 - /usr/bin/clang
  Servers:
    Apache: 2.4.48 - /usr/sbin/apachectl
  Virtualization:
    Docker: 20.10.7 - /usr/local/bin/docker
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
  IDEs:
    Nano: 2.0.6 - /usr/bin/nano
    Vim: 8.2 - /usr/bin/vim
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 16.0.1 - /usr/bin/javac
    Perl: 5.30.2 - /usr/bin/perl
    PHP: 7.3.29 - /usr/bin/php
    Python: 2.7.16 - /usr/bin/python
    Python3: 3.8.9 - /usr/bin/python3
    Ruby: 2.6.3 - /usr/bin/ruby
  Databases:
    MySQL: undefined - /usr/local/mysql/bin/mysql
    SQLite: 3.32.3 - /usr/bin/sqlite3
  Browsers:
    Chrome: 95.0.4638.69
    Firefox: 88.0.1
    Safari: 15.0
  Monorepos:
    Yarn Workspaces: 1.22.10
    Lerna: 4.0.0
```
</details>

### Order ID 💳 (optional)

#31159

**Comment by flaviendelangle** [comment] 2021-11-09 09:00
Could you please give us a reproduction case
It seems to work when I am trying to do it https://codesandbox.io/s/datagridpro-v5-quick-start-forked-p1owv

One possible reason for your bug is if you have a `React.memo` in your toolbar.
Currently, the state of the Grid is stored in a ref for performances reason. But one major drawback is that if you put a `React.memo` on a parent of a component listening to `useGridApiRef` (and `GridFooter` like almost all our components uses `useGridApiRef`), it won't re-render when the state changes.

**Comment by lizsaloka1** [comment] 2021-11-09 14:32
We don't have `React.memo` in our code. Could it be related to using custom Toolbar and Footer components?
```
		components: {
			Toolbar: DataGridToolbar,
			Footer: CustomFooter
		},
```

Toolbar:
```
<GridToolbarContainer>
			<Grid container spacing={2} alignItems="center" className={classes.toolbar}>
				{buttons.length > 0 && buttons.map((button, i) => <Grid item key={i}>{button}</Grid>)}
				{showDivider && <Divider orientation="vertical" flexItem className={classes.divider}/>}
				
				{canChangeDensity && <Grid item><GridToolbarDensitySelector {...buttonProps}/></Grid>}
				{canExport && <Grid item><GridToolbarExport {...buttonProps}/></Grid>}
				{pagination && <Grid item style={{flex: 1}}><GridFooter/></Grid>}
			</Grid>
		</GridToolbarContainer>
```

Footer-
```
pagination &&
			<GridFooterContainer>
				<Grid container alignItems="center" className={classes.footer}>
					{!noReload && <Grid item>
						<IconButton className={classes.reload} onClick={() => reloadTable(id)} tooltip="Reload Data" tooltipProps={{ placement: 'right' }} size="small">
							<Icon icon={faRedo} spin={!loaded} />
						</IconButton>
					</Grid>}
					<Grid item xs />
					<Grid item><GridFooter /></Grid>
				</Grid>
			</GridFooterContainer>
```

We also have `const apiRef  = useRef<GridApi>(null) as GridApiRef;`, but I believe our use of it is ok.

**Comment by flaviendelangle** [comment] 2021-11-10 08:42
I failed to reproduce your bug. I would really need a reproduction case on Codesandbox to find the cause.
https://codesandbox.io/s/datagridpro-v5-quick-start-forked-jw1xv


> We also have const apiRef = useRef<GridApi>(null) as GridApiRef;, but I believe our use of it is ok.

I should not cause bugs indeed. But is their a reason why your don't use `useGridApiRef` ? ​

```tsx
const apiRef = useGridApiRef();
```

**Comment by lizsaloka1** [comment] 2021-11-10 14:48
I figured it out. Turns out we **were** using memo, I just missed it somehow. Thanks for all your help- should I remove this?

**Comment by flaviendelangle** [comment] 2021-11-10 14:51
Unless removing the `React.memo` really impact your performances yes you should.
We are working to remove this ref-state from the grid, it is React anti-pattern, but is a very long work and we prefer not to promise anything yet :+1:

**Comment by lizsaloka1** [comment] 2021-11-10 14:52
Thanks! I meant remove the issue, lol. Since it turned out to be a non-issue.

**Comment by flaviendelangle** [comment] 2021-11-10 14:53
Oh right, yes I am closing it

**Closed by flaviendelangle** 2021-11-10 14:53 UTC
Labels: components: DataGridPro, status: incomplete
