### ISSUE TITLE
[DataGrid] Material-UI v5 `GridToolbarFilterButton` and `GridToolbarExport` requires passing in props

### ISSUE THREAD

**Issue by tamvo22** [mui-org/material-ui-x#2383] opened 2021-08-17 22:57 UTC
Based on Material UI v4 docs for Datagrid Export Typescript doesn't require passing of props for both GridToolbarFilterButton and GridToolbarExport. 

[Data Grid - Export](https://material-ui.com/components/data-grid/export)

However, Mui v5 will report the following error if we don't pass default props for them:

Type '{}' is missing the following properties from type 'Pick<GridToolbarFilterButtonProps, "defaultChecked" | "defaultValue" | "suppressContentEditableWarning" | "suppressHydrationWarning" | "accessKey" | ... 267 more ... | "componentsProps">': ...

- [X] The issue is present in the latest release.
- [X] I have searched the [issues](https://github.com/mui-org/material-ui/issues?q=is%3Aissue+is%3Aopen+datagrid) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Typescript error:
Type '{}' is missing the following properties from type 'Pick<GridToolbarFilterButtonProps, "defaultChecked" | "defaultValue" | "suppressContentEditableWarning" | "suppressHydrationWarning" | "accessKey" | ... 267 more ... | "componentsProps">': ...

## Expected Behavior 🤔

According to the Datagrid docs, GridToolbar shouldn't be reporting Typescript errors for not passing default props.

## Steps to Reproduce 🕹

 [CodeSandbox Test Code](https://codesandbox.io/s/material-ui-v5-datagrid-toolbar-typescript-error-q2ogk?file=/src/data-grid.tsx)

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  Don't forget to mention which browser you used.
  Output from `npx @material-ui/envinfo` goes here.
```
</details>

**Comment by DanailH** [comment] 2021-08-18 11:56
Ah ok this is because the `GridToolbarExport` is extending from `ButtonProps` type from the core and `GridToolbarFilterButton` from the `TooltipProps` again from the core. We could make them optional?

**Comment by ZeeshanTamboli** [comment] 2021-08-19 08:34
Duplicate of #2000

**Closed** 2021-08-19 08:34 UTC
Labels: duplicate
