### ISSUE TITLE
[DataGridPro] Filtering problem for number of 0

### ISSUE THREAD

**Issue by atillaaliyev** [mui-org/material-ui-x#3839] opened 2022-02-04 08:34 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I have two row in DataGrid. And **"Zeyil No"** column has 0 and 1 values. I'm filtering for **"Zeyil No"** with 1 value. It's working right. But, when I filtered with 0 value, no result. I'm using **"contains"**, **"equals"**, **"starts with"** and **"end with"** operators. Only, it's working for **"is any of"** operator

https://user-images.githubusercontent.com/6121871/152497032-5c009b4e-4bfc-4bdf-aa15-5817e2f6b4a1.mp4

.

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

37219

**Comment by flaviendelangle** [comment] 2022-02-04 11:30
Hi,

Could you give me a reproduction case ? 
[This template](https://codesandbox.io/s/datagridpro-v5-quick-start-5pjhc) could be a good starting point.

**Comment by atillaaliyev** [comment] 2022-02-04 12:14
@flaviendelangle 
[https://codesandbox.io/s/6d7mw](url)

You can filter Column3 with value 0 by equal, contains, starts with and ends with operators.
It won't filter.

**Comment by flaviendelangle** [comment] 2022-02-04 12:18
You can define the type of the column to have number operators

https://codesandbox.io/s/datagridpro-v5-quick-start-forked-p1qh1?file=/src/App.tsx

```ts
  { field: "col3", headerName: "Column 3", width: 150, type: "number" }
```

With that being said, the string columns should handle numbers correctly.
I think I got the source of the problem, I will do a fix.

**Comment by m4theushw** [comment] 2022-02-04 12:21
Possible duplicate of #3374?

The solution from https://github.com/mui-org/material-ui-x/issues/3374#issuecomment-991668634 should fix.

**Comment by flaviendelangle** [comment] 2022-02-04 12:30
Indeed, I'm closing it in favor of #3374 and doing the fix

**Closed by flaviendelangle** 2022-02-04 12:30 UTC
Labels: component: data grid, status: incomplete, plan: Pro
