### ISSUE TITLE
Incompatible with mui@next

### ISSUE THREAD

**Issue by FBurner** [mui-org/material-ui-x#2570] opened 2021-09-08 20:46 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Dependend on @material-ui/styles

### Expected behavior 🤔

Using x-grid-pro and should be using the new style engine.

### Steps to reproduce 🕹

Steps:

1. install mui/material@next
2. instal mui/x-data-grid-pro@next

### Context 🔦

Like to migrate to next because the old version seems to be not working perfectly with micro frontends

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by m4theushw** [comment] 2021-09-08 20:48
Duplicate of #2527

You can make it work by adding aliases. See https://github.com/mui-org/material-ui-x/issues/2527#issuecomment-915557814

**Closed** 2021-09-08 20:48 UTC
Labels: duplicate
