### ISSUE TITLE
[DataGrid] Unable to erase a record when using the "getRowId()"

### ISSUE THREAD

**Issue by samchon** [mui-org/material-ui-x#1553] opened 2021-05-02 11:13 UTC
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
I can't erase a row from the data-grid, when the data-grid is using the `getRowId`.

It seems most same like with the #607, only whether using `getRowId` or not is different.

![image](https://user-images.githubusercontent.com/13158709/116810676-1b78d780-ab80-11eb-8696-a389a32e91c3.png)

## Expected Behavior 🤔
Be able to erase a row from the data-grid even using the `getRowId` method.

## Steps to Reproduce 🕹

https://codesandbox.io/s/loving-butterfly-fsqn4?file=/src/CategoryGrid.tsx

  1. Select any item from the data-grid
  2. Click the `Erase` button
  3. The undefined error would be occured

## Context 🔦
I want to erase a row from the data-grid when using the `getRowId()`

## Your Environment 🌎
  - @material-ui/core 4.11.4
  - @material-ui/data-grid. 4.0.0-alpha.27
  - react 17.0.2
  - react-dom 17.0.0
  - react-scripts 4.0.0
  - Same error occurs in every browsers

**Comment by oliviertassinari** [comment] 2021-05-02 15:59
It's a duplicate of #1491, the second time we see somebody trying to mutate the rows in place.

I think that it's time to add the Object.freeze in dev mode:

https://github.com/mui-org/material-ui-x/blob/fa346f0fbe3d9b9eea9bb403fe4675f544d6abf9/packages/grid/x-grid-data-generator/src/useDemoData.ts#L78

for the rows.

**Closed** 2021-05-18 09:40 UTC
Labels: bug 🐛, component: DataGrid, good to take
