### ISSUE TITLE
[DataGrid] @material-ui/x-license is now required for DataGrid to load.

### ISSUE THREAD

**Issue by jedieaston** [mui-org/material-ui-x#2291] opened 2021-08-06 13:22 UTC
As of the current release, the open-source DataGrid requires @material-ui/x-license to be installed to load. This appears to have been introduced in #2176.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

DataGrid does not work unless you manually install @material-ui/x-license.

## Expected Behavior 🤔

DataGrid either has @material-ui/x-license installed as a dependency, or, since it's open source, don't even try to verify the license in DataGrid and just don't include the stuff that isn't open source with it. 

## Steps to Reproduce 🕹

https://codesandbox.io/s/n8nk9

Steps:

1. Open any of the examples in [the docs](https://material-ui.com/components/data-grid/) in CodeSandbox.
2. Marvel at the sight of it not loading because it can't find x-license since npm doesn't know its a dependency.

## Context 🔦

I'm trying to play with some examples in CodeSandbox so I don't have to pollute my local project. 

## Your Environment 🌎

CodeSandbox.

(If you want me to open a PR to add x-license as a dependency, I can do that in like 5 seconds. But I figured there's some regression I'm not seeing with my only mild familiarity with the codebase)

**Comment by joshunger** [comment] 2021-08-06 14:03
@jedieaston Nice! This was released in v4.0.0-alpha.36 which has a NPM release date of 2021-08-06T11:15:09.376Z or 5:15 AM mountain for anyone finding this page when your build failed.

**Comment by PorterK** [comment] 2021-08-06 14:48
Thanks! This was causing our CI builds to fail this morning - in the future should we remove the `^` in our package.json version for all alpha/beta MUI packages? Or is this just an oversight/bug?

**Comment by ddolcimascolo** [comment] 2021-08-06 15:11
Hey guys, we're hit by this too :) What's the current status, should we just wait for a release?

Thx !

**Comment by flaviendelangle** [comment] 2021-08-06 15:22
Caused by https://github.com/mui-org/material-ui-x/pull/2176
By importing the `LicenseStatus` type in `gridState` we made this package mandatory for the DataGrid...
The solution is probably to accept to type it with `string` which is not big of a deal.

One more reason to work on isolating the XGrid features instead of putting everything in the `_modules_` folder. It would be easier to catch when we are importing XGrid-only deps in DataGrid folder.

**Comment by oliviertassinari** [comment] 2021-08-06 22:27
For people that want to use HEAD with a fix: they can use `"@material-ui/data-grid": "https://pkg.csb.dev/mui-org/material-ui-x/commit/67812e94/@material-ui/data-grid",`.

**Closed** 2021-08-09 17:01 UTC
Labels: bug 🐛, priority: high, regression :rabbit2:
