### ISSUE TITLE
onEditCellChange with check boxes does not return the row id with 4.0.0-alpha.34

### ISSUE THREAD

**Issue by BrianSHenderson** [mui-org/material-ui-x#2212] opened 2021-07-26 11:18 UTC
When using the onEditCellChange the id that is returned is in the form mui-????? rather than the id of the row.  Standard text input boxes continue to work well.  This did work with previous versions.

- [ ] The issue is present in the latest release.
- [ ] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
onEditCellChange returns an id with something like mui-12345

## Expected Behavior 🤔
It should return params.row.id as with the previous version

## Steps to Reproduce 🕹
```
<XGrid columns={columns}  rows={rows} onEditCellChange={handleEditCellChange} />

const handleEditCellChange = async ({ id, field, props }, event) => {
  console.log('id', id)
}

```

Steps:

1.
2.
3.
4.

## Your Environment 🌎
  System:
    OS: macOS 11.5
  Binaries:
    Node: 14.15.5 - ~/.nvm/versions/node/v14.15.5/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.15.5/bin/npm
  Browsers:
    Chrome: 92.0.4515.107
    Edge: Not Found
    Firefox: 89.0
    Safari: 14.1.2
  npmPackages:
    @material-ui/core: ^4.11.3 => 4.11.3 
    @material-ui/icons: ^4.11.2 => 4.11.2 
    @material-ui/lab: ^4.0.0-alpha.57 => 4.0.0-alpha.57 
    @material-ui/styles:  4.11.3 
    @material-ui/system:  4.11.3 
    @material-ui/types:  5.1.0 
    @material-ui/utils:  4.11.2 
    @material-ui/x-grid: ^4.0.0-alpha.34 => 4.0.0-alpha.34 
    @material-ui/x-license:  4.0.0-alpha.34 
    @types/react:  17.0.4 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    styled-components: ^5.3.0 => 5.3.0 

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  Don't forget to mention which browser you used.
  Output from `npx @material-ui/envinfo` goes here.
```
</details>

## Order id 💳
Order #24250

**Comment by BrianSHenderson** [comment] 2021-07-26 12:23
Maybe the same as #2206

**Comment by DanailH** [comment] 2021-07-26 12:24
@BrianSHenderson, yes it does look like a duplicate of #2206

**Comment by m4theushw** [comment] 2021-07-26 12:46
Duplicate of #2206

**Closed** 2021-07-26 12:46 UTC
Labels: duplicate
