### ISSUE TITLE
[docs] Add example for customizing the styling of GridPanel & other GridToolbar panels

### ISSUE THREAD

**Issue by bryyytl** [mui-org/material-ui-x#1239] opened 2021-03-16 00:01 UTC
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡
I think it would be great to have additional documentation within the rendering section showing how to easily customize the styling of GridPanel, FilterPanel, ColumnsPanel, and other related components. Currently, it is not clear whether the easiest way to customize these inner panel classes through creating custom slots and passing a className to these custom slots or if there is another way to easily overwrite some of the inner panel classes.

Relates to: #1192, #1116, #1211

**Comment by oliviertassinari** [comment] 2021-03-16 22:10
@bryyytl Please share more on the pain you have in #1037. @DanailH was planning to work on it in the coming days.

**Comment by oliviertassinari** [comment] 2021-03-16 22:10
Duplicate of #1037

**Closed by oliviertassinari** 2021-03-16 22:10 UTC
Labels: status: needs triage
