### ISSUE TITLE
is it possible to create a multi-select filter for a column?

### ISSUE THREAD

**Issue by razk87** [mui-org/material-ui-x#2739] opened 2021-09-29 16:38 UTC
### Order ID 💳

#29674

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I would like to create a multi selec filter for a column, a list with the uniqe values of a column with checkboxes.
the closest thing i found was a single-select column type.
can this be achived using this library
![Group 66617 (1)](https://user-images.githubusercontent.com/83636963/135311779-a6cfe537-c16c-4feb-968b-5f009cdf7a32.jpeg)
?

### Your environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @material-ui/envinfo` goes here.
```
</details>

**Comment by m4theushw** [comment] 2021-09-29 16:47
Duplicate of #2437 

We don't have a built-in filter like that, but it can be created adding a custom operator: https://mui.com/components/data-grid/filtering/#create-a-custom-operator

I suggested to use the Autocomplete, because it already supports the selection of multiple values: https://mui.com/components/autocomplete/#multiple-values

**Closed** 2021-09-29 16:48 UTC
Labels: duplicate, question, pro plan
