### ISSUE TITLE
[DataGrid] Selection Cell TouchRipple not reset when navigating using keyboard

### ISSUE THREAD

**Issue by xiaoyu-tamu** [mui-org/material-ui-x#3456] opened 2021-12-18 00:32 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

https://user-images.githubusercontent.com/33362998/146622339-36081bcd-3f15-4047-a528-f0e3b9136e06.mov

### Steps to reproduce 🕹

see video

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by m4theushw** [comment] 2021-12-18 02:06
Duplicate of #2998

**Closed by m4theushw** 2021-12-18 02:06 UTC
Labels: status: needs triage
