### ISSUE TITLE
Error on Select component within DataGrid editable cell

### ISSUE THREAD

**Issue by jamintz** [mui-org/material-ui-x#1714] opened 2021-05-20 13:14 UTC
Attempting to modify the Custom Edit Component (https://codesandbox.io/s/5b3jy) to use a Select. Placing the select within the DataGrid cell and then attempting to use the Select results in an error: Uncaught TypeError: Failed to execute 'contains' on 'Node': parameter 1 is not of type 'Node'.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Attempting to use the Select within editable DataGrid cell results in error

## Expected Behavior 🤔

No error should occur

## Steps to Reproduce 🕹
https://codesandbox.io/s/material-demo-forked-w514o?file=/demo.js

Steps:
1. Change select for cell in table
2. Observe error

## Your Environment 🌎
 System:
    OS: macOS 11.2.1
  Binaries:
    Node: 15.8.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 90.0.4430.212
    Edge: Not Found
    Firefox: 84.0.1
    Safari: 14.0.3
  npmPackages:
    @material-ui/core: ^4.11.4 => 4.11.4 
    @material-ui/data-grid: ^4.0.0-alpha.27 => 4.0.0-alpha.27 
    @material-ui/icons: ^4.11.2 => 4.11.2 
    @material-ui/lab: ^4.0.0-alpha.58 => 4.0.0-alpha.58 
    @material-ui/styles:  4.11.4 
    @material-ui/system:  4.11.3 
    @material-ui/types:  5.1.0 
    @material-ui/utils:  4.11.2 
    @material-ui/x-grid: ^4.0.0-alpha.27 => 4.0.0-alpha.28 
    @material-ui/x-grid-data-generator: ^4.0.0-alpha.19 => 4.0.0-alpha.19 
    @material-ui/x-license:  4.0.0-alpha.28 
    @types/react:  17.0.1 
    react: ^17.0.0 => 17.0.0 
    react-dom: ^17.0.0 => 17.0.0 
    styled-components: ^5.0.0 => 5.2.1 

## Order id 💳
21172

**Comment by jamintz** [comment] 2021-05-20 13:40
@oliviertassinari are you saying this is a duplicate of https://github.com/mui-org/material-ui-x/issues/1439? Possible it'll be fixed by a full implementation of the select column type as is discussed there but this could also be a separate issue

**Comment by oliviertassinari** [comment] 2021-05-22 10:13
Duplicate of #1439

**Closed by oliviertassinari** 2021-05-22 10:13 UTC
Labels: duplicate, status: needs triage

**Comment by oliviertassinari** [comment] 2021-05-22 10:15
- In #1320 we might implement a dedicated enum type
- In #1439 we focus into supporting the `Select`
