### ISSUE TITLE
Support for a callback to fire when a column is hidden?

### ISSUE THREAD

**Issue by efreethy** [mui-org/material-ui-x#1206] opened 2021-03-11 22:18 UTC
Hello - I am a Material UI X Pro customer.

I am implementing persistent column preferences between sessions in the browser, and need a way to detect when a user has hidden a column, I also need a way to initialize the grid specifically with which columns are currently visible.

Is this possible with the current API? There are a ton of api methods and hooks that aren't documented on the [x grid api](https://next.material-ui.com/api/x-grid/#props) documentation page. Where can I view the most recent docs? Its been very difficult finding the functionality I need.

**Comment by oliviertassinari** [comment] 2021-03-12 22:00
Duplicate of #820

**Closed by oliviertassinari** 2021-03-12 22:00 UTC
Labels: duplicate

**Comment by AndrewRSharp** [comment] 2021-03-22 12:44
@efreethy - You can decide which columns are visible by default by adding the hide: true property to your column definitions for each column you want hidden. I found that [here](https://material-ui.com/components/data-grid/columns/#column-headers).

As an example, I had a full list of column definitions and a list of what fields should be visible by default so I said:

> const getCols = (visibleCols, allCols) => (
>    allCols.map( x => ({ ...(!visibleCols.includes(x.field) && {hide: true}}));
> 
> const [columns, setColumns] = useState(getCols(visibleCols, allCols));
> 
> <XGrid
> columns={columns}
> ...
> />

This obviously doesn't solve the state between sessions problems, but it helps you have a default state for new users instead of showing them every column. Hope that helps!
