### ISSUE TITLE
Collapsible row

### ISSUE THREAD

**Issue by ak-mid** [mui-org/material-ui-x#1194] opened 2021-03-09 14:17 UTC
Right now we're using a Material UI table where the user can expand each row to view more information about the corresponding entry. I checked the XGrid/DataGrid API and it doesn't seem like that I can hook into the row rendering and add another row underneath (which makes sense due to the fact how rows are build in a data grid).
Therefore it's probably an advanced feature for the XGrid component.

- [X] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

An icon at the beginning of the primary row will expand/collapse an additional secondary row right underneath of the primary row.

## Examples 🌈

There is already a Material UI example called collapsible table

https://material-ui.com/components/tables/#collapsible-table

## Motivation 🔦

It's important for us to provide additional row data to the customer without leaving the current screen. Also the current version of the product already includes a collapsible row. If we switch to XGrid without that feature we need to rethink our implementation or we need to use another data grid 😟

**Comment by oliviertassinari** [comment] 2021-03-10 19:20
Duplicate of #211

**Closed by oliviertassinari** 2021-03-10 19:20 UTC
