### ISSUE TITLE
[DataGrid] Edit date picker returns incorrect value

### ISSUE THREAD

**Issue by aTmb405** [mui-org/material-ui-x#1573] opened 2021-05-06 05:30 UTC
When selecting a date from the native date picker, the rendered cell value is one day off whenever the input type is 'date'. 

[This is due](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse#date_time_string_format) to `new Date()` interpreting the 'yyyy-mm-dd' form as UTC time (date-time forms are interpreted as local time). You can see a summary of date parsing behavior in JS [here](https://dygraphs.com/date-formats.html).

This can be fixed by setting `editProps.value` to always be `newValue`, and removing the conditional check to set `editProps.value` to be `new Date(newValue)` in 

https://github.com/mui-org/material-ui-x/blob/3e4be4de6cd41030eee75e8485c64a9a5ba48502/packages/grid/_modules_/grid/components/cell/GridEditInputCell.tsx#L30

I am not sure if this would be the preferred way to fix, or if it would be preferred to update the input value formatter on line

https://github.com/mui-org/material-ui-x/blob/3e4be4de6cd41030eee75e8485c64a9a5ba48502/packages/grid/_modules_/grid/components/cell/GridEditInputCell.tsx#L39

 so I have created an issue rather than a PR.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate. 

## Current Behavior 😯

When selecting any date with the date picker, the previous date is rendered as the cell value.

## Expected Behavior 🤔

When selecting any date with the date picker, the selected date is rendered as the cell value.

## Steps to Reproduce 🕹

1. Open DataGrid editing [docs](https://material-ui.com/components/data-grid/editing/)
2. Select a date in `Date Created` column (type='date')
3. Compare behavior with `Last Login` column (type='dateTime')

## Your Environment 🌎

 System:
    OS: macOS 11.2.3
  Binaries:
    Node: 15.2.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.0.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 90.0.4430.93

**Comment by oliviertassinari** [comment] 2021-05-06 12:24
> This can be fixed by setting editProps.value to always be newValue, and removing the conditional check to set editProps.value to be new Date(newValue) in

👍 for it, I have proposed the same in https://github.com/mui-org/material-ui-x/pull/1570#pullrequestreview-652553377.

But I fail to see how it's enough? From what I understand, we still need to store a JS Date object type in the row. And per https://github.com/mui-org/material-ui/pull/23475, we can't use `new Date()`.

**Comment by oliviertassinari** [comment] 2021-05-06 14:50
@aTmb405 In https://codesandbox.io/s/material-demo-forked-jh448?file=/demo.tsx, the input rows are type JS Date, and the edit value we get back at the end, are also type JS Date.

To me, it looks a lot like we need to use the [`LocalizationProvider`](https://next.material-ui.com/components/date-picker/#requirements) of Material-UI v5 to support the edit mode on date objects. Or figure out a way to do the parsing correctly, which might be preferable to keep the component lightweight (not requiring one of date-fns/moment/dayjs/luxon, etc).

**Comment by aTmb405** [comment] 2021-05-06 15:24
> @aTmb405 In https://codesandbox.io/s/material-demo-forked-jh448?file=/demo.tsx, the input rows are type JS Date, and the edit value we get back at the end, are also type JS Date.

Ah, I see. I think there might be an inconsistency within `GridEditInputCell`. The api event overrides the value type set by `setValueState` and `inputFormattedValue` whenever a date is picked.

> To me, it looks a lot like we need to use the [`LocalizationProvider`](https://next.material-ui.com/components/date-picker/#requirements) of Material-UI v5 to support the edit mode on date objects. Or figure out a way to do the parsing correctly, which might be preferable to keep the component lightweight (not requiring one of date-fns/moment/dayjs/luxon).

I think the parsing could be a simpler fix. The picker always returns the 'yyyy-mm-dd' format for dates, so it would only require a quick string manipulation to the 'yyyy/mm/dd' format that is handled in the [same way](http://blog.dygraphs.com/2012/03/javascript-and-dates-what-mess.html) by `Date.parse()` and `new Date() ` across all browsers.

**Comment by oliviertassinari** [comment] 2021-05-06 15:28
> so it would only require a quick string manipulation to the 'yyyy/mm/dd' format that is handled in the same way by Date.parse() and new Date() across all browsers.

Right, I would also 👍 to force the same timezone as the input JS date (if available).

**Comment by dtassone** [comment] 2021-05-06 18:00
Timezone is a complex issue.

The plan was to store dates in utc in state and just display them localised. So on change event would get them in utc.
The issue is when you set them, it gets complicated with time, as you set it at midnight so it rolls back to the previous day due to the locale.

> LocalizationProvider
Yes we might need something like that to do it properly...
We could also change the underlying component to an input that can handle all those edge cases.
And we can refactor the edit input for dates only to its own component, or add an option in the grid to consider dates in utc or locale, so server would localize accordingly.

**Comment by oliviertassinari** [comment] 2021-05-06 18:06
> Timezone is a complex issue.

Lol, yes: https://github.com/mui-org/material-ui-pickers/issues/1526

**Comment by aTmb405** [comment] 2021-05-06 20:36
> Timezone is a complex issue.

And JS Date object sometimes doesn't help - months are zero-based values but not dates?

> The issue is when you set them, it gets complicated with time, as you set it at midnight so it rolls back to the previous day due to the locale.

Yes, the rolling back behavior happens with `new Date('2021-05-06')`, but not with `new Date('2021/05/06')`

**Comment by dtassone** [comment] 2021-05-07 09:40
> Yes, the rolling back behavior happens with new Date('2021-05-06'), but not with new Date('2021/05/06')

Interesting. I think the issue is that the input takes a string, it would be easier if it took a date, as when we convert it to string we loose any timezone information so we have to reprocess it when we reassign it to a date. 
The format used also by the input is not really well known hence why it might work with YYYY/MM/DD

**Comment by aTmb405** [comment] 2021-05-07 15:37
> Interesting. I think the issue is that the input takes a string, it would be easier if it took a date, as when we convert it to string we loose any timezone information so we have to reprocess it when we reassign it to a date.

I don't think there's a way around this because HTML date inputs only output strings. 

> The format used also by the input is not really well known hence why it might work with YYYY/MM/DD

This is due to HTML inputs and JS Date objects not working together consistently. Whenever a date string with a timezone is passed to the Date object, it is always interpreted in local time [[source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse#date_time_string_format)]. Whenever a date string without a timezone is passed to the Date object, it has to assume the timezone. The shortened date string YYYY-MM-DD is 'standard format', so it is assumed to be UTC time, and this causes the rolling back when converted to local time. Other date strings like YYYY/MM/DD are not 'standard format', so they are assumed to be local time [[source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse#differences_in_assumed_time_zone)]. 

I think there's two ways to always get the same behavior with the date input - 
- ignore using the Date object and just pass values around as date strings
- with `input[type='date']`, convert the outputted value to YYYY/MM/DD before passing to the Date object

**Closed** 2021-05-17 13:54 UTC
Labels: bug 🐛, component: DataGrid

**Comment by Jegard** [comment] 2022-04-12 10:14
Hi which version of datagrid do i need to install to get this fix all all my dates are still a day before the one selected
