### ISSUE TITLE
[DataGrid] Dialog is closed when closing any popup

### ISSUE THREAD

**Issue by Tollwood** [mui-org/material-ui-x#1162] opened 2021-03-04 07:48 UTC
I want to use the DataGrid / XGrid in a mui dialog.

- [x ] The issue is present in the latest release.
- [ x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

- When added a XGrid to a Dialog or Drawer component the column filter is behind the Dialog
- When adjusting the z-index (temp solution) the menu appears and the filter can be opened, however the  dropdowns (firefox) and input (chrome + firefox) is not intercatable.

## Expected Behavior 🤔

A Grid / X-Grid should be usable witin a dialog

## Steps to Reproduce 🕹
Column menu is behind modal:
Steps:

1. open https://codesandbox.io/s/jolly-brown-txddl 
2. click button
3. click column menu
4. column menu is behind modal

Column menu and filter menu is displayed but input is not working:
1. https://codesandbox.io/s/objective-bohr-t00pu
- - this sets the dialog z-index to zero to make the column menu selectable
2. click button
3. click column menu 
4. select filter
5a. (firefox) dropdown and input is not usable
5b. (chrome) input is not usable

## Context 🔦

My website uses modal to collect user input. sometimes the user can select some element from a table. The table should be filterable to find the correct element.

## Your Environment 🌎
tested in chrome and firefox

<details>
  <summary>`npx @material-ui/envinfo`</summary>
npx @material-ui/envinfo 
npx: Installierte 2 in 3.242s

  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
  Browsers:
    Chrome: 88.0.4324.192
    Edge: Not Found
    Firefox: 85.0.2
    Safari: 14.0.2
  npmPackages:
    @material-ui/core: ^4.11.3 => 4.11.3 
    @material-ui/icons: ^4.11.2 => 4.11.2 
    @material-ui/lab: ^4.0.0-alpha.57 => 4.0.0-alpha.57 
    @material-ui/pickers: ^3.2.10 => 3.2.10 
    @material-ui/styles:  4.11.3 
    @material-ui/system:  4.11.3 
    @material-ui/types:  5.1.0 
    @material-ui/utils:  4.11.2 
    @material-ui/x-grid: 4.0.0-alpha.21 => 4.0.0-alpha.21 
    @material-ui/x-license:  4.0.0-alpha.21 
    @types/react: ^16.9.0 => 16.14.4 
    react: 17.0.1 => 17.0.1 
    react-dom: 17.0.1 => 17.0.1 
    typescript: ^3.9.5 => 3.9.9
</details>

## Order id 💳

21977

**Comment by oliviertassinari** [comment] 2021-03-13 17:28
Duplicate of #844

**Comment by oliviertassinari** [comment] 2021-03-13 17:30
@Tollwood If you want to contribute the CSS z-index fix proposed in #844, it would be appreciated :). Upgrading to v5 solves the usage of the input https://codesandbox.io/s/vibrant-payne-xr6wr?file=/src/App.js

**Comment by oliviertassinari** [comment] 2021-03-13 17:30
I'm reopening as there is still something wrong with the closing logic.

**Comment by oliviertassinari** [comment] 2021-03-13 17:47
I can only think of two solutions:

- have the ClickAwayListener listen in the capture phase, to give it more priority: https://github.com/mui-org/material-ui/issues/25077#issuecomment-798682999
- use the solution proposed in https://github.com/mui-org/material-ui/issues/25077#issuecomment-785250717, but that sucks as it would force two interactions, hence this problem: https://github.com/mui-org/material-ui/issues/7680#issuecomment-512825747

**Comment by m4theushw** [comment] 2021-03-23 14:32
@oliviertassinari Thinking out loud here. Another alternative would be creating a manager similar to ModalManager to deal only with the click-away logic. Instead of using ClickAwayListener or a backdrop all components would register on this manager. When a click occurs we call all listeners in the order they were registered, this gives more flexibility than `useCapture`. Of course, this will require breaking changes on the Dialog component but it's doable for future versions.

**Comment by oliviertassinari** [comment] 2021-03-23 22:13
@m4theushw

- I have simplified the reproduction with https://codesandbox.io/s/simpledialog-material-demo-forked-83l7d?file=/menu.tsx.
- I think that if we can avoid yet another singleton like the ModalManager, it would be great. We have seen a bunch of limitations with the approach. 
- I was curious to see if `addEventListener` behaves like a FIFO or a LIFO, it's [the latter](https://codesandbox.io/s/focused-hawking-j21p8?file=/src/App.tsx).
- It's also worth mentioning that <kbd>Escape</kbd> has the same behavior (close it all). 

I propose we close the issue and wait for developers to raise the issue on its own. I have repurposed the pain point of @Tollwood with an effort to be **thorough** as we have done in the core since very early on. But, maybe the current behavior is actually fine. I mean, see the following:

![ok](https://user-images.githubusercontent.com/3165635/112225615-57d62100-8c2d-11eb-8f3c-7614ac87bee9.gif)

The UX feels fine.

cc @mui-org/x

**Comment by m4theushw** [comment] 2021-03-23 22:25
> I think that if we can avoid yet another singleton like the ModalManager, it would be great. We have seen a bunch of limitations with the approach.

@oliviertassinari Maybe just to standardize all components to use the same approach to detect outside-clicks. The Dialog uses a screen-size div but GridPanel uses ClickAwayListener.

I think that if the dialog is part of a critical task the backdrop click should be disabled with `disableBackdropClick`. I'm OK with closing this issue.

**Comment by oliviertassinari** [comment] 2021-03-23 22:52
@m4theushw Per the FIFO behavior of the addEventListener, if Dialog uses ClickAwayListener too, I wouldn't expect it to work. Dialog's clickAway would fire first, since mounted first :/.

A note, we removed `disableBackdropClick` in v5 as the same behavior could already be easily implemented by filtering the `onClose` callback with the `reason` argument.

**Closed** 2021-03-25 12:49 UTC
Labels: bug 🐛, component: DataGrid
