### ISSUE TITLE
filterModel and onFilterModelChange - infinite loop

### ISSUE THREAD

**Issue by sgentile** [mui-org/material-ui-x#1655] opened 2021-05-12 14:18 UTC
I'm needing to create some aggregate data features (since this is not yet completed by the XGrid we purchased).   In order to do this I need to know when the filters have changed, get the visibleRows and aggregate some values.

Also, when the page loads, we pass some preset filters to the grid based on another page selection.   

The result is 
```
<XGrid
                rows={rows}
                columns={columns}
                pagination
                components={{
                    Toolbar: GridToolbar,
                }}
                filterModel={{
                    items: filterModelItems,
                }}
                onFilterModelChange={onFilterModelChange}
            />
```

So the user can unselect or apply another filter.   however, what happens is setting any other useState on the page, causes the grid to re-apply the filters.

This is creating an infinite loop.   And I can't take the filters from the onFilterModelChange call and pass those to the filterModel, as this also creates an infinite loop.

**Comment by sgentile** [comment] 2021-05-12 14:44
To add, the  onFilterModelChange is constantly firing even though it's sent a specific set of filter model items

**Comment by dtassone** [comment] 2021-05-12 15:42
```tsx
                filterModel={{
                    items: filterModelItems,
                }}
```
When you do the above you change the model at every render.
I suggest you put the `useState` on the full model not only on the items.

**Comment by oliviertassinari** [comment] 2021-05-12 16:12
Agree, it's simply a support request on how to control a state. You have to write the correct feedback.

**Comment by oliviertassinari** [comment] 2021-05-12 16:12
Duplicate of #1508

**Closed by oliviertassinari** 2021-05-12 16:12 UTC
Labels: component: DataGrid, question, status: incomplete

**Comment by sgentile** [comment] 2021-05-12 17:28
thank you - passing it in as an object vs. just items resolved my issue.   I suspect the example showing just setting items started me off in a wrong direction, but that said - I appreciate the quick response
