### ISSUE TITLE
[DataGrid] Filtering a column and then selecting all rows, selects even the hidden rows

### ISSUE THREAD

**Issue by taskmonk** [mui-org/material-ui-x#1707] opened 2021-05-19 15:09 UTC
- [ ] The issue is present in the latest release.
- [ ] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When a column is filtered, on clicking select all checkbox, only the filtered rows should be selected. Currently it selects all rows

## Expected Behavior 🤔

newSelection.selectionModel should contain only the filtered rows instead of all rows

## Steps to Reproduce 🕹

Steps:

1.
2.
3.
4.

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  Don't forget to mention which browser you used.
  Output from `npx @material-ui/envinfo` goes here.
```
</details>

**Comment by taskmonk** [comment] 2021-05-20 03:10
If this issue has already been addressed, can you add the issue link here please?

**Comment by oliviertassinari** [comment] 2021-05-22 13:59
@taskmonk I was expecting @mui-org/x to close with the correct duplicated issue.

**Comment by oliviertassinari** [comment] 2021-05-22 14:00
Duplicate of #1141

**Closed** 2021-05-22 14:00 UTC
Labels: duplicate

**Comment by taskmonk** [comment] 2021-05-30 05:16
Thanks! But this issue is not fixed there either. Any timeline on when the fix would be available?

**Comment by oliviertassinari** [comment] 2021-05-30 09:03
@taskmonk we have no timeline we can communicate on. We might not even implement the behavior you expect, but leave it to developers to control the selection to make it happen. We don't have yet enough information on how end users expect this to behave.
