### ISSUE TITLE
how to wrap text in cell of DataGrid

### ISSUE THREAD

**Issue by NavizDev** [mui-org/material-ui-x#1040] opened 2021-02-13 23:47 UTC
Hi, i trying to wrap text in cell of table.
Is there a way to wrap text in a table column?
i using `<DataGrid />`

![image](https://user-images.githubusercontent.com/40905751/107864564-79bcd680-6e2b-11eb-8010-232ce24e1b49.png)

```
.MuiDataGrid-root .MuiDataGrid-cell{
    color: tomato; //work
    white-space: 'normal' !important; //don't work
    word-wrap: 'break-word' !important; // don't work
}`
```

**Comment by oliviertassinari** [comment] 2021-02-16 15:24
Do you expect the height of the row to adapt to the number of wrapped lines?

**Comment by NavizDev** [comment] 2021-02-16 20:55
@oliviertassinari yes.

**Comment by alessandrocapra** [comment] 2021-02-17 07:49
Same here, I am considering going back to Table because of this. I google for quite some time and it seems the feature has not been released yet, but if there's any workaround please share :)

**Comment by dtassone** [comment] 2021-02-17 11:12
Having dynamic row height is on the pipeline but it might take some time before it gets to production.
In the meantime, I have created a demo with a cell expand renderer which allows seeing the full content of the cell when going over it. 

Check out https://codesandbox.io/s/expandcelldemo-enbw7

**Comment by oliviertassinari** [comment] 2021-02-17 11:23
Should we close as a duplicate of #417 and post the Popper workaround there?

**Comment by jfosterdavis** [comment] 2021-02-19 22:36
Can anybody help with an ES6 popper?

**Comment by oliviertassinari** [comment] 2021-02-21 00:22
Duplicate of #417

**Closed** 2021-02-21 00:22 UTC
Labels: duplicate

**Comment by chriszertamayo** [comment] 2021-12-19 10:31
@dtassone not in tsx please but in js?

**Comment by tielushko** [comment] 2022-01-11 18:35
@chriszertamayo 
https://codesandbox.io/s/bjupl?file=/demo.js

**Comment by rushilzala** [comment] 2022-03-03 07:00
> @chriszertamayo https://codesandbox.io/s/bjupl?file=/demo.js

Thank you so much

**Comment by shoaib1985** [comment] 2022-07-29 07:52
> Hi, i trying to wrap text in cell of table. Is there a way to wrap text in a table column? i using `<DataGrid />`
> 
> ![image](https://user-images.githubusercontent.com/40905751/107864564-79bcd680-6e2b-11eb-8010-232ce24e1b49.png)
> 
> ```
> .MuiDataGrid-root .MuiDataGrid-cell{
>     color: tomato; //work
>     white-space: 'normal' !important; //don't work
>     word-wrap: 'break-word' !important; // don't work
> }`
> ```

please try with following in your css
.MuiDataGrid-root .MuiDataGrid-cell{
  color: tomato; 
  white-space: normal !important; 
  word-wrap: break-word !important; 
}
this should be working

**Comment by zhuhang-jasper** [comment] 2022-12-02 08:17
> > Hi, i trying to wrap text in cell of table. Is there a way to wrap text in a table column? i using `<DataGrid />`
> > ![image](https://user-images.githubusercontent.com/40905751/107864564-79bcd680-6e2b-11eb-8010-232ce24e1b49.png)
> > ```
> > .MuiDataGrid-root .MuiDataGrid-cell{
> >     color: tomato; //work
> >     white-space: 'normal' !important; //don't work
> >     word-wrap: 'break-word' !important; // don't work
> > }`
> > ```
> 
> please try with following in your css .MuiDataGrid-root .MuiDataGrid-cell{ color: tomato; white-space: normal !important; word-wrap: break-word !important; } this should be working

not working. the cell is still ellipsed

**Comment by sadiki-o** [comment] 2022-12-21 09:50
here is a working solution using Tooltip:

```javascript
/* eslint-disable @typescript-eslint/no-non-null-asserted-optional-chain */
/* eslint-disable @typescript-eslint/no-non-null-assertion */
import { Tooltip } from '@mui/material';
import { GridRenderCellParams } from '@mui/x-data-grid';
import { useEffect, useRef, useState } from 'react';

const RenderExpandableCell = (props: GridRenderCellParams) => {
  const [isOverflowed, setIsOverflow] = useState(false);
  const { value } = props;

  const textElementRef = useRef<HTMLSpanElement | null>(null);

  const checkOverflow = () => {
    // Using getBoundingClientRect, instead of scrollWidth and clientWidth, to get width with fractional accuracy
    const clientWidth = textElementRef.current!.getBoundingClientRect().width;

    textElementRef.current!.style.overflow = 'visible';
    const contentWidth = textElementRef.current!.getBoundingClientRect().width;
    textElementRef.current!.style.overflow = 'hidden';

    setIsOverflow(contentWidth > clientWidth);
  };

  useEffect(() => {
    checkOverflow();
    window.addEventListener('resize', checkOverflow);
    return () => {
      window.removeEventListener('resize', checkOverflow);
    };
  }, []);

  return (
    <Tooltip title={value} disableHoverListener={!isOverflowed}>
      <span
        ref={textElementRef}
        style={{
          whiteSpace: 'nowrap',
          overflow: 'hidden',
          textOverflow: 'ellipsis',
        }}
      >
        {value}
      </span>
    </Tooltip>
  );
};

export default RenderExpandableCell;

```

**Comment by alsiddsarkar** [comment] 2024-05-16 05:45
This works:

` getRowHeight={(params) => "auto"}`

**Comment by jnewman-phare** [comment] 2024-07-10 00:19
> This works:
> 
> ` getRowHeight={(params) => "auto"}`

This is the best and most simple solution, thanks!

**Comment by jvallesmasttro** [comment] 2024-07-31 18:15
Is there a way to do the same with datagrid headers?

**Comment by csatish** [comment] 2024-09-27 17:31
> Is there a way to do the same with datagrid headers?
<DataGrid>
sx={{
 '& .MuiDataGrid-columnHeaderTitleContainer': {
            whiteSpace: 'normal'
          },
}}
</DataGrid>

**Comment by rahulchougule** [comment] 2025-01-02 07:58
> > This works:
> > ` getRowHeight={(params) => "auto"}`
> 
> This is the best and most simple solution, thanks!

My text in data grid cell was truncated, on mobile device. I added padding to make UI good along with this solution.

getRowHeight={() => 'auto'}
sx={{
'.MuiDataGrid-cell': {
                      fontSize: '16px',
                      padding:'10px'
                    }
        }}
