### ISSUE TITLE
[DataGrid] Multiple lines/children in renderCell doesn't work for MUI5

### ISSUE THREAD

**Issue by venik2007** [mui-org/material-ui-x#2859] opened 2021-10-13 19:11 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Multiple lines/children in cell doesn't work for MUI5 (example of solution on [stackoverflow](https://stackoverflow.com/questions/64865959/with-material-uis-datagrid-component-how-do-i-create-multi-layered-text-in-one) works fine for `MUI4`, but not for `MUI5`);

### Expected behavior 🤔

Multiple lines/children in cell works well

### Steps to reproduce 🕹

Steps:

1. Open [codesandbox](https://codesandbox.io/s/autumn-currying-kwxef?file=/src/Demo.tsx) example and see result
2. `Devtools` disabling `lineHeight` solve this issue, but I can't find any workarounds to do it through the code (probably it assigned/calculated by scripts, mui devs knows better)

![image](https://user-images.githubusercontent.com/52424112/137196724-33378e28-a11c-4fe3-864b-e91ef86b2645.png)
![image](https://user-images.githubusercontent.com/52424112/137196739-364da9b8-30fb-42e5-8c76-1973d24dfd07.png)

### Context 🔦

This issue blocks me. I need to render array of elements in a cell (with my own component with scroller); example of structure:
```
type Metrics = {
  key: string; 
  value: number;
};

type ServerResponse = {
  // some fields from response
  metrics: Metrics[];
}
```
And I need to show that metrics array for each entity (row) in a single cell

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Browsers: Chrome
```
![image](https://user-images.githubusercontent.com/52424112/136854825-a6a757f6-5d2c-41ed-b65a-eb458c96b2b0.png)
</details>

**Comment by DanailH** [comment] 2021-10-14 08:23
Hi @venik2007 thanks for raising this. It seems to be a duplicate of #417 and/or #438

**Comment by venik2007** [comment] 2021-10-14 09:25
Hi @DanailH, i'm afraid, this is not duplication, because of:
1) This is not https://github.com/mui-org/material-ui-x/issues/417 because i don't need dynamic height, fixed height is fine for me
2) This is not https://github.com/mui-org/material-ui-x/issues/438 because i can configure row height through `DataGrid` `rowHeight` prop, and it will change to different height (see screenshot with height `100`)
![image](https://user-images.githubusercontent.com/52424112/137289533-d3f1c2a1-9edf-4ced-87b7-9f4a292c4c15.png)

And i'm already provide a workaround hot to solve that (see screenshot with disabled `lineHeight`)
![image](https://user-images.githubusercontent.com/52424112/137289833-5cab9d0b-b5c6-4bb5-9a08-c32ee280b7e5.png)

The problem is that i can't override that value even locally to fix it for my project

**Comment by DanailH** [comment] 2021-12-09 09:43
Ok, this must-have slipped through the notifications. I see what the pain is now, thanks for explaining. The problem is how we center the text.

**Closed** 2021-12-22 11:28 UTC
Labels: bug 🐛, component: DataGrid
