### ISSUE TITLE
Module not found: Error: Can't resolve '@material-ui/x-license'

### ISSUE THREAD

**Issue by joshunger** [mui-org/material-ui-x#2294] opened 2021-08-06 13:53 UTC
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce 🕹

Steps:

1.
2.
3.
4.

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  Don't forget to mention which browser you used.
  Output from `npx @material-ui/envinfo` goes here.
```
</details>

**Comment by cmdcolin** [comment] 2021-08-06 13:55
Might be a dupe of https://github.com/mui-org/material-ui-x/issues/2291

**Comment by jedieaston** [comment] 2021-08-06 13:55
It is, this can be closed.

**Comment by joshunger** [comment] 2021-08-06 13:57
@cmdcolin @jedieaston Awesome! It would be helpful if 2291 had the error message so you could find the issue. I swear I searched. :)

**Closed** 2021-08-06 13:57 UTC
Labels: status: needs triage
