### ISSUE TITLE
[DataGrid] Open Drawer will reset column fluid width to 100px

### ISSUE THREAD

**Issue by YouWillBe** [mui-org/material-ui-x#747] opened 2020-12-15 02:30 UTC
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Column is set `flex: 1`, then open Drawer, column width will be changed.

## Steps to Reproduce 🕹

[demo](https://codesandbox.io/s/currying-worker-rv5ht?file=/src/App.js)

## Your Environment 🌎

| Tech          | Version |
| ------------- | ------- |
| @material-ui/core | v4.11.2  |
| @material-ui/data-grid | v4.0.0-alpha.12  |
| React | v17.0.1 |
| Browser | chrome v87.0.4280.88 |

**Comment by oliviertassinari** [comment] 2020-12-15 16:04
I have simplified the reproduction as much as possible in https://codesandbox.io/s/laughing-snowflake-21s1p?file=/src/App.js.

**Comment by oliviertassinari** [comment] 2020-12-15 16:04
Duplicate of #716

**Closed by oliviertassinari** 2020-12-15 16:04 UTC
Labels: duplicate
