### ISSUE TITLE
Data Grid Pagination

### ISSUE THREAD

**Issue by ziyadmutawy** [mui-org/material-ui-x#1769] opened 2021-05-25 19:34 UTC
While attempting to do a controlled `onPageChange` I noticed the event object during the callback only contained the `current` page and not the next one. Looking at the documentation and example, I also noticed that it didnt event work. https://material-ui.com/components/data-grid/pagination/#controlled-pagination

I also didnt notice any way for me to figure out if the user clicked "next" or "previous"

**Comment by DanMHammer** [comment] 2021-05-25 19:56
`params.page` is the new page number. To test this, create a table that has several pages, and log `page`. For example, use           `onPageChange={(params) => console.log(params.page)}`.

Starting on the first page (page 0), click next page, and you should log `1`. 
Click previous, and you'll get 0. 
etc.

I think you might not have known or realized that the first page is page 0.

**Comment by oliviertassinari** [comment] 2021-05-25 19:59
Duplicate of #1711

**Closed by oliviertassinari** 2021-05-25 19:59 UTC
