### ISSUE TITLE
Translateable DataGrid component

### ISSUE THREAD

**Issue by EmilKarlsson89** [mui-org/material-ui-x#415] opened 2020-10-08 07:41 UTC
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

The DataGrid component currently has the hard-coded values "Total Rows" and "x-y of z". It would be better if the contents of these texts could be altered to be any text, so that users from other countries do not have to know English in order to use the component.

## Examples 🌈

<DataGrid customTexts={{totalRows: 'Totalt antal rader', of: 'av'}}/>

## Motivation 🔦

I am currently trying to use the DataGrid component in my project. I don't want to mix English and Swedish but the DataGrid component is forcing me to do so.

**Comment by oliviertassinari** [comment] 2020-10-08 07:46
Duplicate of #196

**Closed by oliviertassinari** 2020-10-08 07:46 UTC
Labels: duplicate
