### ISSUE TITLE
Warning selectLabel is not implemented in ForwardRef(TablePagination)

### ISSUE THREAD

**Issue by pheintzelman** [mui-org/material-ui-x#2137] opened 2021-07-12 15:27 UTC
Getting this warning when using a simple datagrid.

The full warning is: 

"Material-UI: The key `selectLabel` provided to the classes prop is not implemented in ForwardRef(TablePagination).
You can only override one of the following: root,toolbar,spacer,caption,selectRoot,select,selectIcon,input,menuItem,actions."

- [X] The issue is present in the latest release.
- [X] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Getting a warning.

## Expected Behavior 🤔

No warning.

## Steps to Reproduce 🕹

Use this datagrid:

```
 <DataGrid
            columns={[
              {
                field: "title",
                headerName: "Title",
                flex: 1
              },
            ]}
            rows={[{ id: 1, title: "hello world" }]}
            className="collection"
            disableSelectionOnClick
          />
```

Steps:

1. Use the above dataGrid

## Your Environment 🌎

  
```
  Output from `npx @material-ui/envinfo`:
   System:
    OS: macOS 11.4
  Binaries:
    Node: 12.20.0 - ~/.nvm/versions/node/v12.20.0/bin/node
    Yarn: Not Found
    npm: 6.14.8 - ~/.nvm/versions/node/v12.20.0/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Edge: Not Found
    Firefox: 83.0
    Safari: 14.1.1
  npmPackages:
    @material-ui/core: ^4.11.4 => 4.12.1 
    @material-ui/data-grid: ^4.0.0-alpha.33 => 4.0.0-alpha.33 
    @material-ui/icons: ^4.11.2 => 4.11.2 
    @material-ui/styles:  4.11.4 
    @material-ui/system:  4.12.1 
    @material-ui/types:  5.1.0 
    @material-ui/utils:  4.11.2 
    @types/react:  17.0.13 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 

    Browser: Chrome
```

**Comment by oliviertassinari** [comment] 2021-07-17 15:41
Duplicate of #2106

**Closed** 2021-07-17 15:41 UTC
Labels: bug 🐛, duplicate
