### ISSUE TITLE
"mui.com/components/data-grid/" pages have too many redirects and reloads if you choose Russian language in browser

### ISSUE THREAD

**Issue by vnt-hub** [mui-org/material-ui-x#2992] opened 2021-10-25 11:38 UTC
"mui.com/components/data-grid/" pages have too many redirects and reloads if you choose Russian language in browser
![2021-10-25 14_25_57-Photos](https://user-images.githubusercontent.com/69205626/138688007-6e90ece4-7cfe-4e64-84c9-4505632bc3ab.jpg)

https://user-images.githubusercontent.com/69205626/138690432-3fe7e134-7339-48e1-a317-4f0a02ac9750.mp4

**Comment by m4theushw** [comment] 2021-11-09 14:37
Duplicate of #2844 

It should be fixed in the next release this week.

**Closed by m4theushw** 2021-11-09 14:37 UTC

**Comment by flaviendelangle** [comment] 2021-11-10 09:51
@blindbeat @vnt-hub it should now be fixed https://mui.com/components/data-grid/
