### ISSUE TITLE
[DataGrid] Checkbox doesn't work in cells

### ISSUE THREAD

**Issue by piotrdytkowski** [mui-org/material-ui-x#1238] opened 2021-03-15 22:27 UTC
When I want to use a Checkbox component with checked and onChange attributes, onChange is not fired.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

Versions:
"@material-ui/core": "4.11.3",
"@material-ui/data-grid": "4.0.0-alpha.22",

## Current Behavior 😯

When I add a controlled checkbox via column definition `renderCell`, it doesn't trigger `onChange` function.

## Expected Behavior 🤔

Clicking checkbox should trigger `onChange`.

## Steps to Reproduce 🕹

https://codesandbox.io/s/material-demo-checkbox-wct4g

Steps:

1. Click a checkbox in the second column.

## Context 🔦
Changing `onChange` to `onClick` triggers the function, but it has some drawbacks.

**Comment by dtassone** [comment] 2021-03-16 10:11
try using `defaultChecked` instead of `checked`

**Comment by piotrdytkowski** [comment] 2021-03-16 10:30
That doesn't work either and also throws an exception `Material-UI: A component is changing the default checked state of an uncontrolled SwitchBase after being initialized. To suppress this warning opt to use a controlled SwitchBase. `

**Comment by piotrdytkowski** [comment] 2021-03-16 10:34
That throws an exception `Material-UI: A component is changing the default checked state of an uncontrolled SwitchBase after being initialized. To suppress this warning opt to use a controlled SwitchBase.`.

**Comment by oliviertassinari** [comment] 2021-03-17 00:00
@piotrdytkowski This looks like a support request. Please ask on StackOverflow. The component behaves correctly.

**Comment by piotrdytkowski** [comment] 2021-03-17 09:58
The thing is that global state doesn't matter here. I provided a new example with `useState`. Pair `checked and onChange` doesn't work, pair `defaultChecked and onChange` throws an exception. Isn't it how checkboxes are supposed to be used? If I'm wrong I think the api is very counter intuitive.
Sandbox: https://codesandbox.io/s/data-grid-with-broken-and-working-checkbox-6z47k
Important thing is that this same checkbox works completely fine if used outside of the data-gird. Can you have another look? I put a checkbox outside of the datagrid to show the problem better. The same checkbox working outside, not working inside the grid.

**Comment by oliviertassinari** [comment] 2021-03-17 19:18
@piotrdytkowski Thanks for the update on the reproduction. Yeap, it's a bug: https://codesandbox.io/s/data-grid-with-broken-and-working-checkbox-2-forked-wbzv3?file=/demo.js

**Comment by oliviertassinari** [comment] 2021-03-17 19:30
It was fixed in #1158.

**Comment by oliviertassinari** [comment] 2021-03-17 19:47
It seems to originate from a subtle rendering timing issue with React. Being more idiomatic solves the pain.

**Closed by oliviertassinari** 2021-03-17 19:47 UTC
Labels: bug 🐛, component: DataGrid
