### ISSUE TITLE
[DataGrid] onRowClick fired when rendered Button is clicked

### ISSUE THREAD

**Issue by MMMMDCCXI** [mui-org/material-ui-x#891] opened 2021-01-21 14:19 UTC
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Buttons that are added within a grid also trigger the onRowClick event when clicked.

## Expected Behavior 🤔

onRowclick will not be fired

## Context 🔦

I have a grid that navigates onRowClick, in addition to this I have a button in the grid that opens a dialog. The click on the button triggers the navigation.

**Comment by oliviertassinari** [comment] 2021-01-21 14:25
@MMMMDCCXI Why not filter the events with `event.currentTarget` vs. `event.target`?

**Comment by MMMMDCCXI** [comment] 2021-01-21 14:55
@oliviertassinari  onRowClick does not redirect the event to the outside.

![image](https://user-images.githubusercontent.com/16964177/105367096-5d4cc600-5c00-11eb-9808-b2ac6db7808a.png)

**Comment by oliviertassinari** [comment] 2021-01-21 17:03
@MMMMDCCXI Thanks for raising these inconsistencies:

1. We don't expose the `event` as in other components
2. It looks like we don't listen on the right node (the root instead of the row itself): https://github.com/mui-org/material-ui-x/blob/88c78e47c7f7a3fd97f46ff09757c58fa826b9db/packages/grid/_modules_/grid/hooks/root/useEvents.ts#L186
3. It also looks like it's not listened on the right event bubbling phase (why is it not using capture: false?)
4. It looks like we don't rely on React event delegation, it could be beneficial, like `event.key` polyfill but t's probably secondary.

Could you create a reproduction so we can better understand your use case?

Out of curiosity, why use `onRowClick` over `onRowSelected`?

**Comment by MMMMDCCXI** [comment] 2021-01-21 19:28
Here is an example of what I am trying.
https://codesandbox.io/s/6e9xr?file=/demo.js

Clicking on a line should navigate me a level depth. But it should be possible to remove objects within the view.

**Comment by oliviertassinari** [comment] 2021-01-21 19:37
@MMMMDCCXI Thanks. The best solution I can think of is to be more idiomatic to React. Fix 1. and 3. should be enough to get a workaround 2. and 4. would make the solution clean: add a property on the event when you intercept it in the button and filter the event in the row click even if it's present. Without 2 and 4. you would have to update `event.nativeEvent` It's probably good enough.

**Comment by oliviertassinari** [comment] 2021-01-30 12:54
Note that you could also try `disableClickEventBubbling` https://codesandbox.io/s/material-demo-forked-gosob?file=/demo.js:336-361.

**Comment by m4theushw** [comment] 2021-06-17 20:31
To use interactive components inside cells, `event.stopPropagation` has to be called in the `onClick` of the component so the event is not propagated to the row. We use this approach to render links in the [demo](https://material-ui.com/components/data-grid/demo/).

@mui-org/x Can we close this issue? We don't mention `onRowClick` in any page of the docs to update it.

https://github.com/mui-org/material-ui-x/blob/7fd5c6663a9df424852f2df3447e5eaff1b7c6ef/packages/grid/x-grid-data-generator/src/renderer/renderLink.tsx#L22-L25

**Comment by oliviertassinari** [comment] 2021-06-17 21:37
@m4theushw The four points of https://github.com/mui-org/material-ui-x/issues/891#issuecomment-764795190 have been fixed. This allows https://codesandbox.io/s/material-demo-forked-gosob?file=/demo.js.

```jsx
const columns = [
  {
    field: "roleName",
    headerName: "Role",
    flex: 1
  },
  {
    field: "action",
    headerName: " ",
    width: 100,
    disableClickEventBubbling: true,
    renderCell: (params) => (
      <IconButton
        onClick={(event) => {
          event.ignore = true;
          console.log("delete");
        }}
      >
        <DeleteIcon />
      </IconButton>
    )
  }
];

export default function RenderCellGrid() {
  return (
    <div style={{ height: 300, width: "100%" }}>
      <DataGrid
        rows={rows}
        columns={columns}
        onRowClick={(params, event) => {
          if (!event.ignore) {
            console.log("push -> /roles/" + params.row.id);
          }
        }}
      />
    </div>
  );
}
```

👍 for closing.

**Comment by oliviertassinari** [comment] 2021-06-17 21:38
@m4theushw When you see outdated messages like this on: https://github.com/mui-org/material-ui-x/issues/891#issuecomment-770208265 feel free to hide:

<img width="935" alt="Capture d’écran 2021-06-17 à 23 37 45" src="https://user-images.githubusercontent.com/3165635/122475535-169fa400-cfc5-11eb-8067-9cb57bc6e172.png">

**Closed** 2021-06-17 21:50 UTC
Labels: breaking change, component: DataGrid, discussion, enhancement

**Comment by designbyadrian** [comment] 2021-09-22 16:07
`disableClickEventBubbling` doesn't seem to work on actions with `showInMenu` set to true.

**Comment by m4theushw** [comment] 2021-09-22 16:13
@designbyadrian `disableClickEventBubbling` was removed. You can use https://github.com/mui-org/material-ui-x/pull/1910#issue-921901120 or https://mui.com/components/data-grid/events/#disabling-the-default-behavior

**Comment by designbyadrian** [comment] 2021-09-24 08:04
> @designbyadrian `disableClickEventBubbling` was removed. You can use [#1910 (comment)](https://github.com/mui-org/material-ui-x/pull/1910#issue-921901120) or https://mui.com/components/data-grid/events/#disabling-the-default-behavior

This does not work onRowClick, so I have to check what was clicked:

```
const isActionCell = !!event.target.closest('.MuiDataGrid-actionsCell');

if (!isActionCell) {
  // do the thing
}
```

**Comment by HamzaM01** [comment] 2022-11-16 19:34
> To use interactive components inside cells, `event.stopPropagation` has to be called in the `onClick` of the component so the event is not propagated to the row. We use this approach to render links in the [demo](https://material-ui.com/components/data-grid/demo/).
> 
> @mui-org/x Can we close this issue? We don't mention `onRowClick` in any page of the docs to update it.
> 
> https://github.com/mui-org/material-ui-x/blob/7fd5c6663a9df424852f2df3447e5eaff1b7c6ef/packages/grid/x-grid-data-generator/src/renderer/renderLink.tsx#L22-L25

Hello. So I have the reverse problem of this that if you have onRowClick event, but one or more column `type`: "actions", then row click event is not fired when clicking on that column/cell, but works on other columns.
