### ISSUE TITLE
[DataGrid] Broken checkbox selection in v5 alpha 33

### ISSUE THREAD

**Issue by antoinerousseau** [mui-org/material-ui-x#1663] opened 2021-05-13 11:38 UTC
The `checkboxSelection` option of the latest [DataGrid](https://next.material-ui.com/api/data-grid/) from the latest MUI alpha release is broken.
It works with MUI v4.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

`checkboxSelection` allows to check rows but not uncheck them.

## Expected Behavior 🤔

`checkboxSelection` should allow ticking and unticking rows like with MUI v4.

## Steps to Reproduce 🕹

https://codesandbox.io/s/material-5-data-grid-v6pew

## Context 🔦

I wasn't sure wether I should open an issue since it's about an alpha release, so feel free to close or move it if it's irrelevant.

Dependencies used:

- @emotion/react 11.4.0
- @emotion/styled 11.3.0
- @material-ui/core 5.0.0-alpha.33
- @material-ui/data-grid 4.0.0-alpha.28
- react 17.0.2
- react-dom 17.0.2
- react-scripts 4.0.0

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  System:
    OS: macOS 11.3.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 1.25 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.10.1 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v13.12.0/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v13.12.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/lib/ruby/gems/2.7.0/bin/pod
    Homebrew: 2.6.1 - /usr/local/bin/brew
    RubyGems: 3.2.5 - /usr/local/opt/ruby/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.28.0 - /usr/local/bin/git
    Clang: 1205.0.22.9 - /usr/bin/clang
  Servers:
    Apache: 2.4.46 - /usr/sbin/apachectl
  Virtualization:
    VirtualBox: 6.1.0 - /usr/local/bin/vboxmanage
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.1, 29.0.2
      System Images: android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Nano: 2.0.6 - /usr/bin/nano
    VSCode: 1.56.1 - /usr/local/bin/code
    Vim: 8.2 - /usr/bin/vim
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 1.8.0_202 - /usr/bin/javac
    Perl: 5.30.2 - /usr/bin/perl
    PHP: 7.3.24 - /usr/bin/php
    Python: 2.7.16 - /usr/bin/python
    Python3: 3.8.6 - /usr/local/opt/python@3.8/bin/python3
    Ruby: 2.7.2 - /usr/local/opt/ruby/bin/ruby
  Databases:
    SQLite: 3.32.3 - /usr/bin/sqlite3
  Browsers:
    Brave Browser: 90.1.24.84
    Chrome: 90.0.4430.212
    Firefox: 87.0
    Safari: 14.1
```
</details>

**Comment by oliviertassinari** [comment] 2021-05-13 16:48
Duplicate of #1577

**Closed by oliviertassinari** 2021-05-13 16:48 UTC
