### ISSUE TITLE
Deploying 4.0.0-alpha.28 fails (useGridApiRef' is not exported)

### ISSUE THREAD

**Issue by BrianSHenderson** [mui-org/material-ui-x#1629] opened 2021-05-11 15:23 UTC
With my licensed X-Grid it runs locally but when I try to deploy to Vercel with Nextjs I get an error:

 ```
15:48:44.026 | Failed to compile.
-- | --
15:48:44.027 | ./pages/schools2.js
15:48:44.027 | Attempted import error: 'useGridApiRef' is not exported from '@material-ui/x-grid' (imported as 'useGridApiRef').
15:48:44.027 | > Build error occurred
15:48:44.028 | Error: > Build failed because of webpack errors
15:48:44.029 | at /vercel/path0/node_modules/next/dist/build/index.js:17:924
15:48:44.029 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:5:584)

```
The previous version worked fine, is there an issue with this deploy?

**Comment by dtassone** [comment] 2021-05-14 14:51
Since we can't test or reproduce your issue, I'm closing it for now.
If you have more details, stacktrace or anything, drop it here and we'll take a look

**Closed by dtassone** 2021-05-14 14:51 UTC
Labels: bug 🐛, status: incomplete
