### ISSUE TITLE
Unable to remove a row in data-grid

### ISSUE THREAD

**Issue by rgins16** [mui-org/material-ui-x#607] opened 2020-11-20 01:09 UTC
I am unable to remove a row in the react material ui data-grid.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
I can not remove a row from the data-grid

## Expected Behavior 🤔
I should be able to remove a row from the data-grid

## Steps to Reproduce 🕹
https://codesandbox.io/s/priceless-hopper-lf3ky

Steps:
1. Click the button to attempt to remove row 3

## Context 🔦
I want to remove a row in the data-grid

## Your Environment 🌎
@material-ui/core             4.11.0
@material-ui/data-grid.   4.0.0-alpha.9 (4.0.0-alpha.9)
react                                  16.13.1
react-dom                         16.13.1
react-scripts                     3.4.3

**Comment by egluhbegovic** [comment] 2020-11-20 05:42
Facing the same issue:
https://stackoverflow.com/questions/64912763/material-ui-datagrid-removing-a-row-from-state-causes-cannot-read-property-erro

There are production features we need to release and this is blocking us from achieving that.

**Comment by oliviertassinari** [comment] 2020-11-20 11:45
Duplicate of #571

**Closed by oliviertassinari** 2020-11-20 11:45 UTC
Labels: duplicate

**Comment by egluhbegovic** [comment] 2020-11-20 12:37
@oliviertassinari Has this been resolved?
I am facing the issue on "^4.0.0-alpha.8"?

**Comment by oliviertassinari** [comment] 2020-11-20 12:39
https://github.com/mui-org/material-ui-x/issues/571#issuecomment-731121928
