### ISSUE TITLE
Data Grid Can't resolve '@material-ui/styles' with @Material-UI installed

### ISSUE THREAD

**Issue by chaserda** [mui-org/material-ui-x#2609] opened 2021-09-14 16:17 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Following documentation, data grid cant find a module even though @Material-UI is installed 

./node_modules/@mui/x-data-grid/dist/index-esm.js
Module not found: Can't resolve '@material-ui/styles'

**Comment by m4theushw** [comment] 2021-09-14 16:20
You need to install `@material-ui/styles` too. See https://material-ui.com/components/data-grid/getting-started/#installation

**Comment by chaserda** [comment] 2021-09-14 16:22
@m4theushw I feel like the documentation is a little misleading then

"The grid has two peer dependencies on Material-UI components. _If you are not already using Material-UI in your project_, you can install it with:"

However that being said, it still does not resolve the issue installing ```@material-ui/styles

**Comment by m4theushw** [comment] 2021-09-14 16:26
If you're using Material-UI v4, then installing `@material-ui/styles` should not be necessary. For v5 it does.

> However that being said, it still does not resolve the issue installing @material-ui/styles

Could you provide a reproduction? [This **codesandbox.io** template](https://material-ui.com/r/issue-template) _may_ be a good starting point.

**Comment by chaserda** [comment] 2021-09-14 21:13
@m4theushw I noticed on codesandbox the latest ```@material-ui/styles``` package is ```5.0.0-beta.5``` however running ```npm install @mui/styles``` package.json comes up with ```"@mui/styles": "^5.0.0-rc.0"``` but thats not an option on codebase. Would something like that cause this issue?

**Comment by m4theushw** [comment] 2021-09-15 01:11
`@material-ui/styles` and `@mui/styles` are different packages. Although you're using v5, which requires `@mui/styles`, we still need the first one. The next release will support the new package name and it won't require having two v5 versions. 

I'm closing this one because it's related to the same incompatibility issues pointed in #2527. Instead of installing `@material-ui/styles`, you can also use the unreleased version from https://github.com/mui-org/material-ui-x/issues/2527#issuecomment-916062202 as a workaround.

**Closed by m4theushw** 2021-09-15 01:11 UTC
Labels: status: needs triage
