### ISSUE TITLE
[DataGrid] Server-side pagination is not rendering rows on page 2+

### ISSUE THREAD

**Issue by effique** [mui-org/material-ui-x#640] opened 2020-11-25 15:30 UTC
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
DataGrid component switched to server-side-pagination ` <DataGrid
        rows={rows}
        rowCount={rowsCount}
        columns={columns}
        pageSize={limit}
        pagination
        paginationMode="server"
        onPageChange={handlePageChange}
        page={page}
        loading={loading}
      />` does not render updated rows. The loader is gone when new rows are fetched from api and they are accesible in the view ( I can render the first few rows above data grid and see updated values, etc) but the table stays empty. 

## Expected Behavior 🤔
New rows are displayed when switching pages. 

## Steps to Reproduce 🕹

Issue is present even on your docs page. 
Please visit:
https://material-ui.com/components/data-grid/pagination/#server-side-pagination

Click ">". Pages 6-10 and up are empty.

**Comment by oliviertassinari** [comment] 2020-11-25 19:31
Duplicate of #568

**Closed by oliviertassinari** 2020-11-25 19:31 UTC
Labels: component: DataGrid, duplicate
