### ISSUE TITLE
[Datagrid]: customize row rendering in datagrid

### ISSUE THREAD

**Issue by khanzzirfan** [mui-org/material-ui-x#1360] opened 2021-04-04 12:16 UTC
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡
Custom row should render a collapsable row in my case. but can be any styled div element. can have custom row level styles applied on it. Custom row can be a custom react component altogether. 

## Examples 🌈
In my case, I'm looking for a Material ui table with collapisable row design.
https://material-ui.com/components/tables/#collapsible-table

## Motivation 🔦
I would like to show user with collapsible row. When row is expanded, I would like to show in detail information on the grid row and also few buttons to navigate to different section/page of the app.

**Comment by oliviertassinari** [comment] 2021-04-04 14:07
Duplicate of #1194

**Closed by oliviertassinari** 2021-04-04 14:07 UTC
Labels: component: DataGrid, duplicate
