### ISSUE TITLE
DataGrid Picker doesn't pick february

### ISSUE THREAD

**Issue by jose-hilario** [mui-org/material-ui-x#3061] opened 2021-10-29 15:17 UTC
The fields of type date inside a Datagrid are not allowing to choose february

## Current Behavior 😯

The selected month is march instead of february

## Steps to Reproduce 🕹

1. Goto to the first demo in MUI DataGrid Demo page https://mui.com/components/data-grid/demo/
2. Go to the last column called 'Created On'
3. Chose any day in february
4. The selected month is march, not february

## Context 🔦

I'm trying to choose any february's day in 2021 or 2022 in the DataGrid's column DatePicker (default for 'date' field type)

## Your Environment 🌎

System:
	OS: Linux 4.4 Ubuntu 20.04.2 LTS (Focal Fossa)
Binaries:
	Node: 16.4.0 - /usr/bin/node
	npm: 7.20.3 - /usr/bin/npm
Microsoft Edge

**Comment by alexfauquette** [comment] 2021-11-02 09:28
Hi, 

I struggle to reproduce your bug. Could you be more precise on how you pick the date (a gif recording, or something similar)

I can not reproduce your environment, because Microsoft Edge does not support Ubuntu. Is Edge running in a virtual machine or is it another web browser?

**Comment by jose-hilario** [comment] 2021-11-04 18:21
Hi Alex, today it's already working in the MUI page https://mui.com/components/data-grid/demo/. I'll update to the latest version in my environment. Thank you.

**Comment by flaviendelangle** [comment] 2021-11-05 09:59
Perfect, I'm closing this :+1:

**Comment by ProfHercules** [comment] 2021-11-30 09:03
I am experiencing this issue at the moment, it can be reproduced on the official docs on Chrome on MacOS and Windows, as well as Safari on MacOS.

I've set up a [codesandbox](https://codesandbox.io/s/sweet-pasteur-dtjx6?file=/src/App.js) to demo the issue.

Specifically; selecting any date in February (of any year) returns the same day, but in March. It only appears to be an issue for February.

**Comment by alexfauquette** [comment] 2021-11-30 10:05
Ok, we will deal with this bug in the new issue you opened

**Closed** 2021-11-30 10:05 UTC
Labels: component: DataGrid, status: incomplete
