### ISSUE TITLE
Incompatibility between latest rc-0 and data-grid

### ISSUE THREAD

**Issue by LeoLozes** [mui-org/material-ui-x#2569] opened 2021-09-08 13:34 UTC
### **EDIT**: Nevermind, it doesn't even compile. I must have had some weird node_modules mix.

Also, [duplicated in the other repo](https://github.com/mui-org/material-ui-x/issues/2562).

I didn't find anything related to Data Grid in the v5.0.0-rc.0 release, so I guess it's not supported, but it was working until this last version (I guess the package renaming is the problem). 

I tested with the latest versions of the following packages: 
```
@mui/core
@mui/icons-material
@mui/lab
@mui/material
@mui/styles
@mui/system
@mui/x-data-grid
```

## Current Behavior 😯

When a data grid is rendered, it looks like new styles are injected, and the custom styles applied previously to mui components are switched to a inferior order, disappearing:

![bug](https://user-images.githubusercontent.com/11133817/132519032-5e37f7f8-5ff4-4de5-aa64-4dacc1c7bccb.gif)

## Expected Behavior 🤔

No change in how styles are applied.

## Steps to Reproduce 🕹

Update to the latest version and rename all the packages.

**Comment by stevenkampen** [comment] 2021-09-08 19:09
I believe the data-grid has "partial support" for v5 at the moment (read it somewhere a couple days ago and can't find it now). I assumed by that they meant it's still requiring the old `@material-ui` namedspaced packages.

**Comment by m4theushw** [comment] 2021-09-08 19:17
Duplicate of #2527

You can try adding aliases to the old material-ui modules: https://github.com/mui-org/material-ui-x/issues/2527#issuecomment-912575537. We're working to fully support v5 in the release.

**Closed** 2021-09-08 19:17 UTC
Labels: duplicate
