### ISSUE TITLE
Code crash if user "hides" multiple DataGrid columns

### ISSUE THREAD

**Issue by Furqan-Syed** [mui-org/material-ui-x#876] opened 2021-01-19 03:38 UTC
- [x ] The issue is present in the latest release.
- [ x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
If user tries to hide too many columns on a large DataGrid which exceeds the width of screen, the code will crash and give error of **"TypeError Cannot read property 'width' of undefined"**

## Expected Behavior 🤔

User should be able to hide more than 6 rows on a table regardless of the table's width

## Steps to Reproduce 🕹
You can see this with the demo table for "Custom filter operator" at [ https://material-ui.com/components/data-grid/filtering/](https://material-ui.com/components/data-grid/filtering/) (It's the fourth table on the page)
Attempt to hide the first 6 columns and an error will pop up. 
Here is the code sandbox for that sample table: [ https://material-ui.com/components/data-grid/filtering/](https://codesandbox.io/s/ko04z)
## Context 🔦
Trying to use Datatable to display data with many columns.

**Comment by DanailH** [comment] 2021-01-19 14:30
Hi @Furqan-Syed thanks for reporting this, we are aware of the problem. There is already a PR opened with a fix. You can follow it here #875. Also, this is a duplicate of this https://github.com/mui-org/material-ui-x/issues/856

**Comment by oliviertassinari** [comment] 2021-01-19 14:39
Duplicate of #856

**Closed by oliviertassinari** 2021-01-19 14:39 UTC
Labels: duplicate
