### ISSUE TITLE
XGrid resizes columns large data sets are used

### ISSUE THREAD

**Issue by MitchellJeppson** [mui-org/material-ui-x#795] opened 2020-12-30 17:00 UTC
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

I am using a ToggleButtonGroup that controls the data in my xgrid. When I select the ToggleButton that loads the most data into the grid, the grid columns resize from their configured sizes back to the default 100px columns. Clicking the ToggleButton that loads the smaller dataset resizes the columns back to the specified size.

## Expected Behavior 🤔

XGrid should maintain specified column sizes regardless of data loaded into it. 

## Steps to Reproduce 🕹

https://codesandbox.io/s/material-ui-issue-forked-m3ylx
Steps:

1. Notice width of columns
2. click "two" toggle button at top of page
3. xgrid resizes columns to default 100px

## Context 🔦

Trying to dynamically update data in xgrid. No current workaround. 

## Your Environment 🌎

| Tech                | Version |
| -------------  | ------- |
| Material-UI X  | v4.0.0-alpha.13  |
| React               |    17.0.1     |
| Browser           |     87.0.4280.88 (Official Build) (x86_64)    |

**Comment by DanailH** [comment] 2020-12-31 10:59
Hi @MitchellJeppson, thanks for reporting this. It seems that it is a duplicate of #716. The issue will be fixed in the upcoming release.

**Comment by oliviertassinari** [comment] 2020-12-31 11:39
I have released v4.0.0-alpha.14, and can confirm the bug was fixed. Here is the same codesandbox with the latest versions: https://codesandbox.io/s/material-ui-issue-forked-vo24r?file=/src/Demo.js

**Closed by oliviertassinari** 2020-12-31 11:39 UTC
Labels: duplicate, status: needs triage

**Comment by MitchellJeppson** [comment] 2020-12-31 17:08
Thanks for the quick triage. I'll need to check issues with xgrid and datagrid in the future.
