### ISSUE TITLE
[DataGrid] Changing ```Rows per page``` localization missing keys

### ISSUE THREAD

**Issue by GregdTd** [mui-org/material-ui-x#1854] opened 2021-06-08 12:35 UTC
Hello,
I was able to change the Data grid localization thanks to [this](https://material-ui.com/components/data-grid/localization/).  I also used [this](https://github.com/mui-org/material-ui-x/blob/HEAD/packages/grid/_modules_/grid/constants/localeTextConstants.ts) to know which keys are supported.

I was not able to change the `Rows per page` locale. Am I missing something ?
It looks like we are missing a key for this ?

- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Add a keys in the [DataGrid localization](https://material-ui.com/components/data-grid/localization/#translation-keys). 

Another solution could be: having a props `labelRowsPerPage` like in the [TablePagination](https://material-ui.com/api/table-pagination/) component.

**Comment by GregdTd** [comment] 2021-06-08 13:12
For those looking for a solution I was able to find a way using the [TablePagination](https://material-ui.com/api/table-pagination/) component.

```typescript
<DataGrid
     {...props}
     components={{
          Pagination: () => (
              <TablePagination
                  labelRowsPerPage={t('analysisExplorer.analysisTable.rowPerPage')}
                  rowsPerPageOptions={[5, 10, 25, 50, 100]}
                  component="div"
                  count={storedAnalysis.length}
                  rowsPerPage={rowsPerPage}
                  page={page}
                  onChangePage={handleChangePage}
                  onChangeRowsPerPage={handleChangeRowsPerPage}
              />
          )
      }}
/>
```

**Comment by GregdTd** [comment] 2021-06-08 13:33
I was able to make it work using the [TablePagination](https://material-ui.com/api/table-pagination/) component:

```typescript

 Pagination: () => (
        <TablePagination
            labelRowsPerPage="Rows per page" // <-- change her for anything you like
            rowsPerPageOptions={[5, 10, 25, 50, 100]}
            component="div"
            count={count}
            rowsPerPage={rowsPerPage}
            page={page}
            onChangePage={handleChangePage}
            onChangeRowsPerPage={handleChangeRowsPerPage}
        />
    )
```

But it is not the best solution in my opinion ?

**Comment by dtassone** [comment] 2021-06-08 14:04
Yes it looks like we missed this key in our localization API. 
So ATM your workaround is the best option but we will fix this one very soon. We keep you posted here.
Thanks for raising the issue

**Comment by m4theushw** [comment] 2021-06-08 14:26
@GregdTd We don't have a key for this string because the pagination is based on `TablePagination` from the core library. 

> But it is not the best solution in my opinion?

It works but you have to provide your own pagination. You could also change the default value passed to the `labelRowsPerPage` prop in the theme, as following: 

```jsx
const theme = createMuiTheme({
  props: {
    MuiTablePagination: {
      labelRowsPerPage: "Page size"
    }
  }
});
```

Using this approach there's no need to add a custom pagination component.

**Comment by GregdTd** [comment] 2021-06-08 15:16
> @dtassone We don't have a key for this string because the pagination is based on the `TablePagination` from the core library.
> 
> > But it is not the best solution in my opinion?
> 
> @GregdTd It works but you have to provide your own pagination. You could also change the default value passed to the `labelRowsPerPage` prop in the theme, as following:
> 
> ```js
> const theme = createMuiTheme({
>   props: {
>     MuiTablePagination: {
>       labelRowsPerPage: "Page size"
>     }
>   }
> });
> ```
> 
> Using this approach there's no need to add a custom pagination component.

Thank you for this reply @m4theushw, unfortunately my goal here is to use [i18next](https://www.i18next.com/) and especially the dynamic function `t('key.rowPerPageTranslation')` thanks to the hooks provided by [react-i18next](https://react.i18next.com/latest/usetranslation-hook) so it doesn't suit me for the moment ;)

**Comment by m4theushw** [comment] 2021-06-08 15:24
In this case, you can use the [`componentsProps`](https://material-ui.com/components/data-grid/components/#overriding-components) prop to pass additional props to the pagination component. Since it will be inside a component you'll be able to use hooks.

```jsx
<DataGrid
  componentsProps={{
    pagination: {
      labelRowsPerPage: t('key.rowPerPageTranslation')
    }
  }}
/>
```

**Comment by GregdTd** [comment] 2021-06-08 15:46
> In this case, you can use the [`componentsProps`](https://material-ui.com/components/data-grid/components/#overriding-components) prop to pass additional props to the pagination component. Since it will be inside a component you'll be able to use hooks.
> 
> ```js
> <DataGrid
>   componentsProps={{
>     pagination: {
>       labelRowsPerPage: t('key.rowPerPageTranslation')
>     }
>   }}
> />
> ```

Thanks @m4theushw this is perfect !

Should I close/resolve the issue ?

**Comment by dtassone** [comment] 2021-06-08 15:59
I think the solution provided by @m4theushw is better, no need to override the component.
That being said, IMO, it should be handled outside the box so I think the pagination component should be part of the locale text api and that's bug

**Comment by m4theushw** [comment] 2021-06-08 16:26
@dtassone Do you want to integrate the strings used by `TablePagination` into our locale file? That could be done, but I think the most common use case for localization is to change the entire language of the grid. If the user changes the language of the theme, the grid as well as the pagination will be translated.

**Comment by dtassone** [comment] 2021-06-08 17:20
@m4theushw I think the pagination translations should be stored along with all the other translations as it allows us to have a single approach to how we translate the full grid component.
As you mention above you can do it differently but I think the whole grid including the default components should all be translatable in a single place

**Comment by GregdTd** [comment] 2021-06-08 17:41
@dtassone  `If the user changes the language of the theme`
I saw that Mui does have [localization](https://material-ui.com/guides/localization/) but again I can't change it on the flow using the `i18next` language... 
This would definitely be a better solution than translate each keys of the data grid...

**Comment by oliviertassinari** [comment] 2021-06-08 18:30
Duplicate of #1107?

**Comment by oliviertassinari** [comment] 2021-06-08 18:43
> I think the pagination translations should be stored along with all the other translations

@dtassone We discussed about this in #1107 and decided against because it would meant a duplication of the translations we maintain. This sounds like something we really don't want to do (duplicate the source of the frFR, esES, etc locales between x and core). 

> I think the whole grid including the default components should all be translatable in a single place

Agree, it was proposed in https://github.com/mui-org/material-ui-x/issues/1107#issuecomment-824163178 too:

> We might also need to extend the `locale` prop to have a single location where developers can **discover** what's needed (without depending too much on the docs).

**Closed** 2021-06-18 14:23 UTC
Labels: bug 🐛, component: DataGrid

**Comment by MichalReifer** [comment] 2024-05-10 11:15
```

<DataGrid
      {...data}
      localeText={{
        MuiTablePagination: {
          labelDisplayedRows: ({ from, to, count }) =>
            `${from} - ${to} of ${count === -1 ? `more than ${to}` : count}`,
        },
      }}
    />
```

 https://mui.com/x/react-data-grid/localization/#translation-keys

**Comment by Mohammadtafakori01** [comment] 2024-11-26 17:01
```md
<DataGrid
  {...data}
  localeText={{
    MuiTablePagination: {
      labelRowsPerPage: "HERE"
    },
  }}
/>
```
