### ISSUE TITLE
Use new @mui/* dependencies

### ISSUE THREAD

**Issue by andreawyss** [mui-org/material-ui-x#2605] opened 2021-09-14 05:26 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Current dependencies are: @material-ui/core, @material-ui/styles and @material-ui/utils

### Expected behavior 🤔

Should update dependencies to use the new @mui/* packages.

### Steps to reproduce 🕹

Trying to use current x-data-grid in project that uses new @mui packages causes:

Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app

**Comment by flaviendelangle** [comment] 2021-09-14 09:06
Duplicate of #2527 

For now, you can use https://github.com/mui-org/material-ui-x/issues/2527#issuecomment-916062202.

**Closed** 2021-09-14 09:06 UTC
Labels: duplicate
