### ISSUE TITLE
[DataGrid] (4.0.0-alpha.29) onPageChange returns current page instead of the correct one

### ISSUE THREAD

**Issue by bitkris-dev** [mui-org/material-ui-x#1771] opened 2021-05-26 14:01 UTC
Hi everyone,
I've tried to update my materialUI DataGrid from **4.0.0-alpha.26** to **4.0.0-alpha.29** because I need the new feature "_isRowSelectable_", but when I did it I've discovered that the function **onPageChange** doesn't behave anymore like before. It always returns the current page.

Also:
Is there a way to simulate "isRowSelectable" in the meanwhile that the issue is resolved? I was trying the cellClassRules approach to hide a checkbox via CSS but there is no way to pass it to the checkboxes column.

Thanks for the attention!

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

The function **onPageChange** returns an object with a "page" key; In case my current page is 2, it always returns the un-updated value 2. So the number doesn't move back or forward with the click.
I think a bug has been introduced with one of the last commits.

## Expected Behavior 🤔

I expect the function **onPageChange** to return the updated page value. In case my current page is 2, it should be 3 if I've pressed the forward button and 1 if I've pressed the previous button, for example.

## Steps to Reproduce 🕹

Steps:

1. Install "@material-ui/data-grid@4.0.0-alpha.29"
2. Declare the <DataGrid /> in a React component
3. Add a onPageChange function prop to <DataGrid /> and print the first argument
4. First argument is an object, check the "page" key, it should be different than current page.

## Your Environment 🌎
  System:
    OS: macOS 11.2.2
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
  Browsers:
    Chrome: 90.0.4430.212
    Edge: Not Found
    Firefox: 84.0.2
    Safari: 14.0.3
  npmPackages:
    @material-ui/core: ^4.11.0 => 4.11.3 
    @material-ui/data-grid: ^4.0.0-alpha.26 => 4.0.0-alpha.26 
    @material-ui/icons: ^4.9.1 => 4.11.2 
    @material-ui/lab: ^4.0.0-alpha.56 => 4.0.0-alpha.57 
    @material-ui/pickers: ^3.2.10 => 3.2.10 
    @material-ui/styles:  4.11.3 
    @material-ui/system: ^4.9.14 => 4.11.3 
    @material-ui/types:  5.1.0 
    @material-ui/utils:  4.11.2 
    @types/react:  17.0.2 
    react: ^16.13.1 => 16.14.0 
    react-dom: ^16.13.1 => 16.14.0 
    typescript:  4.2.2 

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  Don't forget to mention which browser you used.
  Output from `npx @material-ui/envinfo` goes here.
```
</details>

**Comment by bitkris-dev** [comment] 2021-05-26 14:41
@oliviertassinari why duplicate? Didn't find any other issue talking about it.

**Comment by oliviertassinari** [comment] 2021-05-26 14:52
Duplicate of #1711

**Closed by oliviertassinari** 2021-05-26 14:52 UTC
Labels: duplicate, status: needs triage

**Comment by m4theushw** [comment] 2021-05-26 16:02
> Is there a way to simulate "isRowSelectable" in the meanwhile that the issue is resolved? I was trying the cellClassRules approach to hide a checkbox via CSS but there is no way to pass it to the checkboxes column.

You can use the [controlled mode](https://material-ui.com/components/data-grid/selection/#controlled-selection) to prevent the selection of certain rows. To hide the checkbox, the `getRowClassName` prop added in 4.0.0-alpha.28 can be used to apply a custom class name to the row and with CSS you hide the checkbox.
