### ISSUE TITLE
[DataGrid] Clicking 'Filters' button in the toolbar shift the view to the bottom of the page

### ISSUE THREAD

**Issue by charlie-ancoris** [mui-org/material-ui-x#1148] opened 2021-03-02 17:18 UTC
On the first click of the 'Filters' button, the users view is shifted to the bottom of the page. Depending on the page height, this can mean that the filters are no longer in view at all. 

This only occurs on the first click. On subsequent clicks the filter overly is shown without any shift in view as expected. It also does not occur when using DataGrid only XGrid  

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Clicking on the Filters button shifts the users view to the bottom of the page

## Expected Behavior 🤔

Clicking on the filters button displays the filter overlay without and shift in view

## Steps to Reproduce 🕹

You can reproduce the issue easily with this code:

````
import * as React from 'react';
import { useDemoData } from '@material-ui/x-grid-data-generator';
//import { DataGrid, GridToolbar } from '@material-ui/data-grid';
import {XGrid, GridToolbar} from "@material-ui/x-grid";

export default function BasicToolbarFilteringGrid() {
  const { data } = useDemoData({
    dataSet: 'Commodity',
    rowLength: 50,
    maxColumns: 6,
  });

  return (
    <div style={{ height: 2400, width: '100%' }}>
      <XGrid
        {...data}
        components={{
          Toolbar: GridToolbar,
        }}
      />
    </div>
  );
}
````

Steps:

1. Refresh the page
2. Click 'Filters'

You can switch the XGrid above for DataGrid to see it working as expected

## Context 🔦

It's really affecting the user experience of our site. We can't have the view jumping around when you click buttons. 

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  Don't forget to mention which browser you used.
  Output from `npx @material-ui/envinfo` goes here.
```
</details>

```
System:
    OS: macOS 11.2.1
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.22.10 - ~/dev/Rentokil/myInitial/rentokil-myinitial/node_modules/.bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
  Browsers:
    Chrome: 88.0.4324.192
    Edge: Not Found
    Firefox: Not Found
    Safari: 14.0.3
  npmPackages:
    @material-ui/core: ~4.11.0 => 4.11.2
    @material-ui/data-grid: ^4.0.0-alpha.21 => 4.0.0-alpha.21
    @material-ui/icons: ~4.9.1 => 4.9.1
    @material-ui/lab: ^4.0.0-alpha.57 => 4.0.0-alpha.57
    @material-ui/pickers: ^3.2.10 => 3.2.10
    @material-ui/styles: ^4.11.2 => 4.11.2
    @material-ui/system:  4.11.2
    @material-ui/types:  5.1.0
    @material-ui/utils:  4.11.2
    @material-ui/x-grid: ^4.0.0-alpha.21 => 4.0.0-alpha.21
    @material-ui/x-grid-data-generator: ^4.0.0-alpha.21 => 4.0.0-alpha.21
    @material-ui/x-license:  4.0.0-alpha.21
    @types/react:  17.0.0
    react: ~16.14.0 => 16.14.0
    react-dom: ~16.14.0 => 16.14.0
    typescript: ~4.0.3 => 4.0.5

```

## Order id 💳

[Order #21167] (February 9, 2021)

**Comment by DanailH** [comment] 2021-03-03 09:38
Thanks, @charlie-ancoris. Yes, I've noticed this yesterday as well. We would need to investigate, it seems to be focus related issue.

**Comment by charlie-ancoris** [comment] 2021-03-03 09:50
Thanks Danail. I noticed that 'component: DataGrid' has been added. Actually I think DataGrid is operating correctly. Its XGrid that is affected.

**Comment by oliviertassinari** [comment] 2021-03-03 15:29
I could reproduce with the column selector too: https://codesandbox.io/s/material-demo-forked-lqndy?file=/demo.tsx. Click on "Columns" or "Filters" in the toolbar.

@dtassone @DanailH how about we only add the bug label once we have a reproduction?

**Comment by oliviertassinari** [comment] 2021-03-03 15:37
The issue with the Filter popup seems fixed with Material-UI v5: https://codesandbox.io/s/material-demo-forked-bgmk3?file=/demo.tsx. However, the column selector still scrolls the page, which yields a poor UX.

@eps1lon Has faced a similar issue with the date picker in https://github.com/mui-org/material-ui/pull/25010. It seems to be the second time we face this problem inside the data grid.

**Comment by charlie-ancoris** [comment] 2021-03-06 08:50
Hi guys. Just thought I'd see if there was any update on this issue. It's pretty important for us and I haven't heard anything for a few days.

**Comment by oliviertassinari** [comment] 2021-03-06 09:12
@charlie-ancoris all updates are on this issue.

**Comment by dtassone** [comment] 2021-03-08 10:32
it seems that it's scrolling just to show the full columns selector, not to the bottom of the page

**Comment by oliviertassinari** [comment] 2021-03-08 10:38
> it seems that it's scrolling just to show the full columns selector, not to the bottom of the page

@dtassone In your reproduction (with core v4), I get the following:

- the column popup scrolls to set the whole content visible
- the filter popup scrolls to the bottom of the page

**Comment by dtassone** [comment] 2021-03-08 10:46
> - the filter popup scrolls to the bottom of the page

Only the first time you click, hence why I didn't notice earlier 🤔

**Comment by oliviertassinari** [comment] 2021-03-10 19:23
I'm adding the important flag to this issue. We can reproduce it on https://material-ui.com/components/data-grid/demo/.

**Comment by charlie-ancoris** [comment] 2021-03-12 16:51
We also found a similar issue with DataGrid
It's actually reproducible from the documentation at https://material-ui.com/components/data-grid/filtering/
Scroll down to the toolbar section. Click the filter button then click the 'x' and you'll get taken to the bottom of the page. Again, it only happens the first time you click it after the page loads. After that it works fine.

**Comment by m4theushw** [comment] 2021-03-22 03:10
@DanailH Have you found a solution to this problem? I can take it, if you don't mind.

I fixed it with the diff below. Since the `isEnabled` prop changes on every render and it's used as a dependency [here](https://github.com/mui-org/material-ui/blob/master/packages/material-ui/src/Unstable_TrapFocus/Unstable_TrapFocus.js#L149), the TrapFocus keeps trying to re-focus the panel. But the problem is that it focus on an incorrect element when the panel was opened via the toolbar button.

```diff
diff --git a/packages/grid/_modules_/grid/components/panel/GridPanelWrapper.tsx b/packages/grid/_modules_/grid/components/panel/GridPanelWrapper.tsx
index 5a0d299..1aa66bb 100644
--- a/packages/grid/_modules_/grid/components/panel/GridPanelWrapper.tsx
+++ b/packages/grid/_modules_/grid/components/panel/GridPanelWrapper.tsx
@@ -17,13 +17,15 @@ const useStyles = makeStyles(
   { name: 'MuiDataGridPanelWrapper' },
 );

+const isEnabled = () => true;
+
 export function GridPanelWrapper(
   props: React.PropsWithChildren<React.HTMLAttributes<HTMLDivElement>>,
 ) {
   const classes = useStyles();
   const { className, ...other } = props;
   return (
-    <TrapFocus open disableEnforceFocus isEnabled={() => true} getDoc={() => document}>
+    <TrapFocus open disableEnforceFocus isEnabled={isEnabled} getDoc={() => document}>
       <div tabIndex={-1} className={classnames(classes.root, className)} {...other} />
     </TrapFocus>
   );
```

**Comment by oliviertassinari** [comment] 2021-03-22 09:50
@m4theushw It's the exact same fix that I had in mind in https://github.com/mui-org/material-ui-x/issues/1254#issuecomment-803343725.

**Closed** 2021-03-25 12:02 UTC
Labels: bug 🐛, component: DataGrid, important
