### ISSUE TITLE
[DataGrid] Support for wrapping text in cells

### ISSUE THREAD

**Issue by fanavarro** [mui-org/material-ui-x#886] opened 2021-01-20 13:09 UTC
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

I am wondering if it would be possible to wrap text in the cells of DataGrid component. Currently, if the text does not fit into the column size, there is an unreachable part:
![imagen](https://user-images.githubusercontent.com/11376639/105177796-77ff3c00-5b27-11eb-9ec3-fbb5a42403d7.png)

It would be great to permit the option of "wrap text", or "adjust text" in cells as excel or libreoffice calc do. In this way, if the text does not fit in the cell, it will include break lines, and the height of the row would increase:
![imagen](https://user-images.githubusercontent.com/11376639/105178664-a0d40100-5b28-11eb-9cbe-b4e163fbf3ab.png)

I have search and I have not found any relevant information about this with regards to the DataGrid component. I also tried with custom rendering, but I did not achieve this desired behavior.

**Comment by oliviertassinari** [comment] 2021-01-21 16:04
@DanailH It makes me think about #417. Duplicate?

**Comment by fanavarro** [comment] 2021-01-21 16:44
Thanks for your answers! I think @oliviertassinari is right, #417 is requesting the same functionality. I did not find that issue when I searched, sorry for that.

**Comment by DanailH** [comment] 2021-01-22 12:51
Duplicate #417

**Comment by DanailH** [comment] 2021-01-22 12:52
Duplicate of #417

**Closed** 2021-01-22 12:52 UTC
Labels: duplicate
