### ISSUE TITLE
[DataGrid] cant enter date year with keyboard 

### ISSUE THREAD

**Issue by Freundschaft** [mui-org/material-ui-x#3085] opened 2021-11-03 23:29 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

![image](https://user-images.githubusercontent.com/5065616/140232824-49ec228e-fede-44a9-8413-9b9f231eeccd.png)

### Expected behavior 🤔

I should be able to enter the date manually with keyboard, I can reproduce this behavior in my code and on the official documentation of the datagrid

### Steps to reproduce 🕹

Steps:

1. Edit Cell with Date Column
2. Enter Day, Month
3. Enter Year
4. Bugs out

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment] 2021-11-04 08:29
Hi, thanks for reporting this bug.

It seems to be a duplicate of #2854. Pull request #2918 should solve it in the next release. You can test in the PR [preview](https://deploy-preview-2918--material-ui-x.netlify.app/components/data-grid/editing/#cell-editing) if your bug is still here. 

I close the issue. If you can reproduce the bug on the preview, don't hesitate to reopen it

**Comment by Freundschaft** [comment] 2021-11-04 22:01
I see, but unfortunately with google chrome I get the same bug, even on the preview at https://deploy-preview-2918--material-ui-x.netlify.app/components/data-grid/editing/#cell-editing

**Comment by alexfauquette** [comment] 2021-11-08 07:53
I do not manage to reproduce it.

If you manage to reproduce it with the last version, don't hesitate to reopen the ticket with a precise description (from the page loading, which key did you press) such that we can investigate on it :)

**Comment by Freundschaft** [comment] 2021-11-09 20:42
ok now it seems it works in regular mode,

but

in the scenario where I use it with


```
                        onEditRowsModelChange={handleEditRowsModelChange}
                        editRowsModel={editRowsModel}
```

it seems the bug appears again

**Comment by Freundschaft** [comment] 2021-11-09 23:21
also the issue still happens, if I enter a year with 5 digits, after which the entire control bugs out

**Comment by alexfauquette** [comment] 2021-11-10 08:28
Ok, I can reproduce the bug for the year with 5 digits. 

About the scenario where you use `onEditRowsModelChnage`, this is too vague to be able to investigate your bug. Please provide a minimal reproduction test case with the latest version. This would help a lot :construction_worker: .
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/2i56z?file=/demo.tsx) _may_ be a good starting point. Thank you!

**Comment by Freundschaft** [comment] 2021-11-10 22:40
yes its essentially the sample from the documentation:

https://codesandbox.io/s/columntypesgrid-material-demo-forked-yqrru

https://mui.com/components/data-grid/editing/#controlled-editing

**Comment by Freundschaft** [comment] 2021-11-11 00:49
in the meantime, i fixed the issue by using the regular datepicker instead of the native one on the grid

```
renderEditCell: function (props) {
                const { id, value, api, field } = props;
                const handleChange = (event) => {
                    debugger;
                    api.setEditCellValue({ id, field, value: event }, event);
                    api.commitCellChange({ id, field });
                    api.setCellMode(id, field, 'view');
                };

                return <MobileDatePicker
                    label="Date mobile"
                    inputFormat="MM/dd/yyyy"
                    value={value}
                    onChange={handleChange}
                    renderInput={(params) => <TextField {...params} />}
                    open={true}
                />;
            }
```

**Comment by Freundschaft** [comment] 2021-11-19 00:48
Umm sorry im not sure the closing of this issue was appropriate action as there were still some things missing to be done

**Comment by alexfauquette** [comment] 2021-11-19 07:32
@Freundschaft I open an issue for the bug with 5 digits

For the other part, I need a precise list of steps to reproduce it, and a description of what appends. You said you have problems with `onEditRowsModelChange`, I'm looking to your codesandbox, I do not see any `onEditRowsModelChange` and I don't know what is the problem& in your example.

To be able to reproduce your bug, I need a precise list of steps, or better a recording of your screen. And if it does not appears on the doc, a codesandbox in which it appears. Otherwise I can not do anything

**Comment by Freundschaft** [comment] 2021-11-22 15:23
sorry, its this one:
https://codesandbox.io/s/6bh59?file=/demo.js:804-825

**Comment by alexfauquette** [comment] 2021-11-22 15:42
Thanks for the example, I will have a look

**Closed** 2021-12-09 14:55 UTC
Labels: bug 🐛, component: DataGrid
