### ISSUE TITLE
Input elements rendered in renderCell are non-editable

### ISSUE THREAD

**Issue by hansoksendahl** [mui-org/material-ui-x#675] opened 2020-12-02 19:56 UTC
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When the cursor is placed in an `<input />` element rendered by `renderCell()` the contents are non-editable. It appears that some key events are not propagating to elements rendered by `<DataGrid />`

## Expected Behavior 🤔

Input elements rendered in a DataGrid should be editable.

## Steps to Reproduce 🕹

https://codesandbox.io/s/material-demo-forked-buirv?file=/demo.tsx

Steps:

1. Attempt to edit any of the input fields rendered in the second column of the DataGrid

## Context 🔦

I have a form element that I need to render in a `<DataGrid />` I need the contents of the form element to be editable so users can fill out the form.

## Your Environment 🌎

| Tech          | Version |
| ------------- | ------- |
| Material-UI X | v4.0.0-alpha.10  |
| React         |  16.13.1  |
| Browser       |  Chrome, Safari  |
| TypeScript    |     3.7.2    |

**Comment by oliviertassinari** [comment] 2020-12-02 20:05
Duplicate of #572

**Closed by oliviertassinari** 2020-12-02 20:05 UTC
Labels: duplicate
