### ISSUE TITLE
Data Grid requires Material UI Core which is mui/material in v5

### ISSUE THREAD

**Issue by naved97** [mui-org/material-ui-x#2601] opened 2021-09-13 06:26 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Could not find dependency: '@material-ui/core' relative to '/node_modules/@mui/x-data-grid-pro/dist/index-esm.js'

The same dependency issue is flashing on next.material.ui data-grid sandbox examples also.

### Expected behavior 🤔

To understand that @material-ui/core is @mui/material

### Steps to reproduce 🕹

Steps:

1. Open https://next.material-ui.com/components/data-grid/
2. Run any Sandbox code

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by Yrlish** [comment] 2021-09-13 09:04
I just stumbled upon the same problem. I'm using MUI v5 beta, installed `@mui/x-data-grid` and tried to run it.

```
Failed to compile.

./node_modules/@mui/x-data-grid/dist/index-esm.js
Module not found: Can't resolve '@material-ui/core/Badge' in '<proj path>\node_modules\@mui\x-data-grid\dist'
```

**Comment by Yrlish** [comment] 2021-09-13 09:26
I've noticed the `next` branch here on GitHub has solved this already, but there aren't any next release of `@mui/x-data-grid` unfortunately.

**Comment by m4theushw** [comment] 2021-09-13 12:47
Duplicate of #2527 

For now, you can use https://github.com/mui-org/material-ui-x/issues/2527#issuecomment-916062202.

**Closed** 2021-09-13 12:48 UTC
Labels: duplicate
