### ISSUE TITLE
[XGrid] Column reorder glitches when dragging a cell with a link

### ISSUE THREAD

**Issue by jessq** [mui-org/material-ui-x#1773] opened 2021-05-26 21:32 UTC
Column reorder should only reorder when you drag the header cell. If a non-header cell has a link, and you drag that link, it triggers the column reorder and the table glitches.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior 🤔
Should not reorder columns 

## Steps to Reproduce 🕹
Go to the example in the documentation: https://material-ui.com/components/data-grid/columns/#column-reorder
Click and drag on the "Trader Email" column
Watch the table glitch around as the columns reorder

## Context 🔦
Customers accidentally dragging columns when they just want to click on a cell and having a poor experience

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  Don't forget to mention which browser you used.
  Output from `npx @material-ui/envinfo` goes here.
```
</details>

## Order id 💳
#22665

**Comment by oliviertassinari** [comment] 2021-05-30 16:56
Duplicate of #1762

**Closed by oliviertassinari** 2021-05-30 16:56 UTC
Labels: duplicate
