### ISSUE TITLE
[DataGrid] Header TextField do not keep focus when clicking from previously focused checkboxSelectable element

### ISSUE THREAD

**Issue by mnavoizat** [mui-org/material-ui-x#3383] opened 2021-12-08 17:25 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

If you have a DataGrid component with custom header containing TextField component in checkboxSelection mode, if you click on a checkbox to select a row and then click on the TextField component, focus is immediately lost. A second click is necessary for the focus to be kept.

### Expected behavior 🤔

After clicking on a checkbox and then clicking on the TextFieldComponent, focus should be kept.

### Steps to reproduce 🕹

Repro: [link to the sandbox](https://codesandbox.io/s/busy-oskar-rm8ku?file=/src/App.tsx)
Use of renderHeader to render the TextField and of checkboxSelection for the checkboxes

Steps:
1. Click on checkbox
2. Click on TextField component 
--> focus switch back to checkbox

### Context 🔦

I need custom TextFields in the header to perform a custom filtering.

### Your environment 🌎

see code sandbox

**Comment by MatthieuCoelho** [comment] 2021-12-09 08:26
Same issue. It looks like TextField is rerender causing focus lost.

**Comment by DanailH** [comment] 2021-12-09 09:44
Duplicate of #3382 

Hi, @mnavoizat thanks for raising this. The same issue has been reported here https://github.com/mui-org/material-ui-x/issues/3382. Since that one was the first one I will mark this as duplicate and close it but the problem is tagged in the other issue. You can track the effort there.

**Closed** 2021-12-09 09:44 UTC
Labels: duplicate
