### ISSUE TITLE
Material-UI: The key `selectLabel` provided to the classes prop is not implemented in ForwardRef(TablePagination).

### ISSUE THREAD

**Issue by M2Changezi** [mui-org/material-ui-x#2168] opened 2021-07-18 13:11 UTC
It only give error in development mode not in browser.
When first load of table happends and on first click of any of the cell data, column header or row  the error occurs as :
`
Material-UI: The key ``selectLabel`` provided to the classes prop is not implemented in ForwardRef(TablePagination).
You can only override one of the following: root,toolbar,spacer,caption,selectRoot,select,selectIcon,input,menuItem,actions.
`

- [ ] The issue is present in the latest release.
- [X ] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

 The error is appearing in console 

## Expected Behavior 🤔

There should be no error

## Steps to Reproduce 🕹
[https://snack.expo.io/@m2c/navigation-events-%7C-react-navigation](example)

Steps:

1.
2.
3.
4.

## Your Environment 🌎
my expo app is in bluestack 5

<details>
  <summary>
`

-  "@emotion/react": "^11.4.0",
    "@emotion/styled": "^11.3.0",
    "@material-ui/core": "^4.12.1",
    "@material-ui/data-grid": "^4.0.0-alpha.33",
    "@material-ui/icons": "^4.11.2",
    "@material-ui/lab": "^4.0.0-alpha.60",
    "@material-ui/system": "^4.12.1",
    "@material-ui/x-grid-data-generator": "^4.0.0-alpha.33",

`</summary>
  
```
  Don't forget to mention which browser you used.
  Output from `npx @material-ui/envinfo` goes here.
```
</details>

**Comment by dangnuo7** [comment] 2021-07-20 06:14
I have exactly the same situation！

**Comment by Piglacquer** [comment] 2021-07-20 17:43
Experiencing the same error in dev.
```    "@material-ui/core": "^5.0.0-alpha.23",
    "@material-ui/data-grid": "4.0.0-alpha.28",```

**Comment by Piglacquer** [comment] 2021-07-20 17:44
Experiencing the same issue.
```
    "@material-ui/core": "^5.0.0-alpha.23",
    "@material-ui/data-grid": "4.0.0-alpha.28",
```

**Comment by m4theushw** [comment] 2021-07-20 18:10
Duplicate of #2106

**Closed** 2021-07-20 18:10 UTC
Labels: bug 🐛, duplicate

**Comment by Programador02SM** [comment] 2021-08-10 07:14
I have the same issue 😢 

 "@material-ui/core": "^4.12.3",
 "@material-ui/data-grid": "^4.0.0-alpha.28",

**Comment by ApplicationNinja** [comment] 2021-08-16 22:54
Ditto same issue...

"@material-ui/core": "latest",
"@material-ui/data-grid": "latest",

**Comment by robsilva** [comment] 2021-10-14 04:24
Same issue happening for me as well.

**Comment by m4theushw** [comment] 2021-10-18 17:30
The warning should be gone by updating to the last version. Notice that the MUI Core package name now is  `@mui/material`.

**Comment by tejaswinid-simplecrm** [comment] 2022-07-08 12:12
Does anyone knows how to solve this?
