### ISSUE TITLE
[DataGrid] Control rendered field in CSV export

### ISSUE THREAD

**Issue by fanavarro** [mui-org/material-ui-x#1145] opened 2021-03-02 12:21 UTC
Hi and thanks for your work, it is very useful.

I have been using the DataGrid component in an application for the last months. Now, I am trying to use the recently added CSV export functionality, but I am not sure about how to specify the render method for creating the CSV file.

Concretely, my data is formed by JSON objects, so I have to specify the 'valueGetter' prop when defining the columns in order to print a concrete field of my data in the DataGrid, and this works perfectly well. Now, I included the CSV export functionality as the   [documentation](https://material-ui.com/components/data-grid/export/) shows, and this adds the button for the CSV download. However, when I download the CSV, the cells contain the string "[object Object]".

I think there should be a property or something to specify a function to convert JSON object to the final CSV cell value, as someone recommended [here](https://github.com/mui-org/material-ui-x/issues/197), but I have been searching in the documentation and I have not found nothing relevant. What is the way to do this?

Thanks beforehand.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

**Comment by oliviertassinari** [comment] 2021-03-02 13:59
Please provide a minimal reproduction test case. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://material-ui.com/r/issue-template) _may_ be a good starting point. Thank you!

**Comment by fanavarro** [comment] 2021-03-02 18:26
Hi @oliviertassinari, thanks for your quick response! Sorry for not following the issue template, but I though this was a question more than a bug.
I have created a live example [here](https://codesandbox.io/s/material-ui-issue-forked-d63me?file=/src/index.js). I've never used codesanbox before, I hope I created it well. In that code you have json objects as data, particularly brands, which have a name and a founder, and models, which have a name and a stock. I used the valueGetter prop when defining columns to select the name as the property to be printed in the table; however, if you export the CSV file, you will see [object Object] in all cells. I think this is due to it is trying to print the JSON object directly without applying the valueGetter function. My question is if there is a way to customize how the data is printed in the CSV file.

Thanks!

**Comment by oliviertassinari** [comment] 2021-03-02 18:40
@fanavarro Perfect, thanks for the reproduction.

@DanailH I think that it's a follow-up on the CSV work you have started. (1.) It does seem wrong that we are not using the output of `valueGetter`. I think that we could start there. It seems to be an easy win.

Regarding pushing the solution further. I didn't benchmark what the other data grid is doing regarding this matter. I imagine there is an opportunity to add many more options. I would be cautious with moving slowly here. It seems that (1.) is enough for this very problem.

**Comment by stevieg2123** [comment] 2021-03-04 21:41
Somewhat on-topic with this: It would be great for the CSV export to respect valueFormatter in the output. We do some EPOCH conversions, as well as bool to Yes/No - CSV export is dumping the raw input (and encountering the comma issue, which massive +1 to the work on. #1143)

Let me know if you want me to punt this to a separate issue for tracking

**Comment by DanailH** [comment] 2021-03-05 09:26
@stevieg2123 thanks for raising this.

@oliviertassinari yes we need to address the problem with the `valueGetter`.

**Comment by fanavarro** [comment] 2021-03-09 10:29
I would suggest not only to apply the valueGetter but also to provide a way to control how the raw data is rendered in the final CSV file. For example, a developer could want to show the main aspects of the data in the online table, but he or she could want to include other things that are hidden in this table when exporting to CSV.

**Comment by fanavarro** [comment] 2021-03-09 11:03
Hi @oliviertassinari. Sorry, I though the planned solution would be to simply apply the valueGetter when exporting the CSV. Misunderstanding from my part, my apologies.

**Comment by m4theushw** [comment] 2021-06-02 02:15
This was fixed in #1154.

I'll close this issue and move the discussion about https://github.com/mui-org/material-ui-x/issues/1145#issuecomment-790965569 to #1814 because it's the same use case.

**Closed by m4theushw** 2021-06-02 02:15 UTC
Labels: component: DataGrid, enhancement
