### ISSUE TITLE
[DataGrid] Cell wrapping within a wrap

### ISSUE THREAD

**Issue by rahiparikh** [mui-org/material-ui-x#949] opened 2021-01-29 15:50 UTC
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

In certain cases (eg. smaller screens), it is difficult to show all the cells in a table row on one line. It would be great if cells could be wrapped to allow one to display more data w/ cell wrapping.  

## Examples 🌈

The [screenshot](https://i.imgur.com/R1HfysG.png) is from Gmail's mobile application where vertical space is used to show more information in the grid.

**Comment by oliviertassinari** [comment] 2021-01-30 12:48
Duplicate of #417

**Closed** 2021-01-30 12:49 UTC
Labels: duplicate

**Comment by alxndrsn** [comment] 2021-11-03 10:30
@oliviertassinari I'm not sure this is a duplicate of #417.  My understanding is that:

* #417 is wrapping of long cell content within the cell, and
* #949 (this ticket) is allowing a single row to display its cells vertically

Maybe it would help to update the issue title to "Cell wrapping within a row"?

There's a great example of this behaviour at https://vuetifyjs.com/en/components/data-tables/#usage:

# Wide screen

![Screenshot_2021-11-03_13-27-05](https://user-images.githubusercontent.com/191496/140044497-99e9f0a7-5e46-4b34-8d3d-cc33844accbf.png)


# Thin screen

![Screenshot_2021-11-03_13-26-42](https://user-images.githubusercontent.com/191496/140044522-475e1356-103a-40c8-9906-5424e9be1781.png)
