### ISSUE TITLE
Column maxWidth property

### ISSUE THREAD

**Issue by cq-ubaid-khan** [mui-org/material-ui-x#3517] opened 2021-12-28 10:07 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Currently we have column `minWidth` option but there is no way to set max width of column. adding `maxWidth` property would be really helpful in case where we want the default column width to automatically expands based on one of the max cell content and stops expanding when reaches to the `maxWidth`, Same also imply for column resize to resize between min and max widths'.

### Examples 🌈

You can see from the image below the **Group** column expands till the maxWidth.

![image](https://user-images.githubusercontent.com/58769931/147554707-0bc1c188-5a4e-475e-af57-54048b99a0b6.png)

### Motivation 🔦

We have a datagrid requirement where column all cells should adjust their widths to max cell content width in that column also we have predefined max width which should prevent max column width to exceed beyond that width.
 e.g, `maxWidth={240} `

**Comment by oliviertassinari** [comment] 2021-12-28 16:26
Duplicate of #2174

**Closed** 2021-12-28 16:27 UTC
Labels: duplicate
