### ISSUE TITLE
[DataGrid] checkboxSelection does not work with material-ui/core 5.0.0

### ISSUE THREAD

**Issue by klinge27** [mui-org/material-ui-x#1684] opened 2021-05-17 10:08 UTC
Checkbox selection of a row cannot be deselected by clicking on the checkbox with material-ui/core 5.0.0-alpha.33. 

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

I updated the data grid demo: https://codesandbox.io/s/material-demo-forked-9h0oh?file=/package.json

After selection of some rows, deselect a row by clicking on the checkbox. The checkbox is not deselected. 
The rows cannot be deselected via the top checkbox.
The row can be deselected after clicking on one of the cells. 

## Expected Behavior 🤔

The row can be deselected after clicking on the checkbox.
All rows can be deselected after clicking on the top checkbox.

## Steps to Reproduce 🕹

Steps:

1. Open the forked example with the material-ui/core version 5.0.0.-alpha.33
2. Select a row by clicking on the checkbox
3. Deselect the row by clicking on the same checkbox
4. The row is not deselected. 
5. Deselect all checkboxes via the top checkbox
6. An error message appears in the console
7. "A component is changing the controlled checked state of SwitchBase to be uncontrolled.
Elements should not switch from uncontrolled to controlled (or vice versa).
Decide between using a controlled or uncontrolled SwitchBase element for the lifetime of the component.
The nature of the state is determined during the first render. It's considered controlled if the value is not `undefined`."

## Context 🔦
Using material-ui/core alpha + data grid

see https://codesandbox.io/s/material-demo-forked-9h0oh?file=/package.json

## Your Environment 🌎

see https://codesandbox.io/s/material-demo-forked-9h0oh?file=/package.json

## Order id 💳

None

**Comment by klinge27** [comment] 2021-05-18 07:21
Can you please help - I don't want to downgrade Material UI Core. 

PS: Sorry for duplicated issue

**Comment by oliviertassinari** [comment] 2021-05-18 09:27
Duplicate of #1672

**Closed by oliviertassinari** 2021-05-18 09:27 UTC
Labels: duplicate, status: needs triage
