### ISSUE TITLE
Material ui datagrid with fixed first column 

### ISSUE THREAD

**Issue by konerunaveena** [mui-org/material-ui-x#3156] opened 2021-11-10 18:30 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by m4theushw** [comment] 2021-11-10 21:02
Duplicate of #193

**Closed** 2021-11-10 21:02 UTC
Labels: duplicate
