### ISSUE TITLE
[Datagrid] Performance issue during scrolling with many TextField

### ISSUE THREAD

**Issue by reygj** [mui-org/material-ui-x#1812] opened 2021-06-01 17:01 UTC
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
Scrolling and moving the datagrid makes the whole grid lag when using Autocomplete inside the cell.

## Expected Behavior 🤔
Scrolling the datagrid should be smooth and without major lags.

## Steps to Reproduce 🕹
Go to:
https://codesandbox.io/s/material-demo-forked-r4wv7?file=/demo.js
Try to move from left to right on the datagrid
The datagrid will lag a lot

![issue](https://i.imgur.com/WB2ZiPn.gif)

## Your Environment 🌎
Custom column code:
```
{
    field: "nameA",
    headerName: "Name A",
    disableClickEventBubbling: true,
    width: 200,
    renderCell: (params1) => {
      return (
        <Autocomplete
          options={["Susan", "Mark"]}
          defaultValue={params1.getValue(params1.id, "nameA")}
          getOptionLabel={(option) => option}
          getOptionSelected={(option, value) => option.value === value.value}
          style={{ width: "100%", paddingTop: 20 }}
          renderInput={(params) => <TextField {...params} variant="outlined" />}
        />
      );
    }
  } 
```

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  Don't forget to mention which browser you used.
  Output from `npx @material-ui/envinfo` goes here.
```
</details>

**Comment by oliviertassinari** [comment] 2021-06-01 23:13
> It seems that TextField is simply too slow for this use case.

https://github.com/mui-org/material-ui-x/issues/569#issuecomment-808727136

I would propose we close as "won't fix": Don't use the grid this way.

**Comment by dtassone** [comment] 2021-06-02 13:27
Your `renderCell` functions are not memoized, and the components get redrawn at every render hence the issue.

```tsx
const MyAutoComplete = React.memo((params) => {
  return (
    <Autocomplete
      options={["Susan", "Mark"]}
      defaultValue={params.getValue(params.id, "nameA")}
      getOptionLabel={(option) => option}
      getOptionSelected={(option, value) => option.value === value.value}
      style={{ width: "100%", paddingTop: 20 }}
      renderInput={(params) => <TextField {...params} variant="outlined" />}
    />
  );
});

//then 
...
  {
    field: "nameA",
    headerName: "Name A",
    disableClickEventBubbling: true,
    width: 200,
    renderCell: (params) => <MyAutoComplete {...params} />
  },
...
```
Check out 
https://codesandbox.io/s/xgrid-render-autocomplete-sxi42

**Comment by oliviertassinari** [comment] 2021-06-02 17:49
> Check out https://codesandbox.io/s/xgrid-render-autocomplete-sxi42

@dtassone I don't feel any difference between the two [codesand](https://codesandbox.io/s/material-demo-forked-r4wv7?file=/demo.js)[boxes](https://codesandbox.io/s/xgrid-render-autocomplete-sxi42). When I enable the FPS counter or use Chrome Dev tools performance feature I also see no differences.

Actually, in both cases with:

<img width="170" alt="Capture d’écran 2021-06-02 à 19 40 26" src="https://user-images.githubusercontent.com/3165635/120527263-6d5c8980-c3da-11eb-9e85-af7b58f5debd.png">

It's lags.

I also don't understand why React.memo would help. Intuitively, I would have expected it to harm slightly as it leads to more CPU cycles spent on comparing props for nothing. Consider the following: https://codesandbox.io/s/xgrid-render-autocomplete-sxi42?file=/demo.js. I get the same number of renders when I scroll memo or not.

**Comment by oliviertassinari** [comment] 2021-06-02 18:03
> It's lags.

I have spent 10 minutes looking at why the performance issue as I wasn't satisfied with "use react memo". What I can see is a major rendering (user-agent, not React) step when scrolling starts, and when it stops:

<img width="683" alt="Capture d’écran 2021-06-02 à 19 59 27" src="https://user-images.githubusercontent.com/3165635/120529722-0f7d7100-c3dd-11eb-8ba4-2afae9d9c7a9.png">

This [forced reflow](https://developers.google.com/web/fundamentals/performance/rendering/avoid-large-complex-layouts-and-layout-thrashing?utm_source=devtools#avoid-forced-synchronous-layouts) is triggered by 

https://github.com/mui-org/material-ui-x/blob/fa346f0fbe3d9b9eea9bb403fe4675f544d6abf9/packages/grid/_modules_/grid/hooks/utils/useGridScrollFn.ts#L31-L33

**Comment by oliviertassinari** [comment] 2021-06-02 18:15
Commenting on these 3 lines leads to interesting behavior.

```diff
diff --git a/packages/grid/_modules_/grid/hooks/utils/useGridScrollFn.ts b/packages/grid/_modules_/grid/hooks/utils/useGridScrollFn.ts
index 86943b6a..ad533f7e 100644
--- a/packages/grid/_modules_/grid/hooks/utils/useGridScrollFn.ts
+++ b/packages/grid/_modules_/grid/hooks/utils/useGridScrollFn.ts
@@ -28,9 +28,9 @@ export function useGridScrollFn(

       if (renderingZoneElementRef && renderingZoneElementRef.current) {
         logger.debug(`Moving ${renderingZoneElementRef.current.className} to: ${v.left}-${v.top}`);
-        if (renderingZoneElementRef.current!.style.pointerEvents !== 'none') {
-          renderingZoneElementRef.current!.style.pointerEvents = 'none';
-        }
+        // if (renderingZoneElementRef.current!.style.pointerEvents !== 'none') {
+        //   renderingZoneElementRef.current!.style.pointerEvents = 'none';
+        // }
         // Force the creation of a layer, avoid paint when changing the transform value.
         renderingZoneElementRef.current!.style.transform = `translate3d(-${v.left}px, -${v.top}px, 0)`;
         columnHeadersElementRef.current!.style.transform = `translate3d(-${v.left}px, 0, 0)`;
```

We remove the upfront major rendering step, but it seems we add more rendering effort along the way:

<img width="686" alt="Capture d’écran 2021-06-02 à 20 06 28" src="https://user-images.githubusercontent.com/3165635/120530937-561f9b00-c3de-11eb-84af-a9ce065d8b47.png">

Overall it seems smoother and to have a more creative hover feedback.

**Comment by dtassone** [comment] 2021-06-03 10:17
The goal of the memo is to avoid to redraw the cell so I would have expected slightly better perf. It would be easier to see maybe with more data...
Interesting found on the pointer-events, are you saying it creates issues? It should make things smoother as it blocks the over events...

**Comment by oliviertassinari** [comment] 2021-06-03 10:37
> to avoid to redraw the cell

@dtassone Could we expand on the why? By redraw, do you mean at the browser level? I really can't connect the dots.

> It would be easier to see maybe with more data...

We could consider what happen with more data indeed, however:

- The users doesn't seem to render more data to see the performance issue
- Why would more data make a difference? Maybe a codesandbox with a reproduction could illustrate it. 

> are you saying it creates issues? It should make things smoother as it blocks the over events

I would recommend you try the change out in your local environment to get a feeling of the difference of rendering experience. It definitely causes an expensive redraw before any scroll action can be performed by the browser. I don't know if it's the problem the author is talking about, still it's feels laggy with a low-end CPU.

The other advantage seems to help with the hover feedback on the cells, it feels more responsive (you get the hover styles as you scroll for instance)

**Comment by dtassone** [comment] 2021-06-03 11:23
I think before the performance fixes #1513, the pointer events helped, as mouse events would make cells to rerender due to  different cell params. Now it seems fine, over events should not cause cells to rerender therefore we can leave the pointer events while scrolling. I had a play locally and it seems smooth without.

For the text box issue, I have updated the component to render basic input text and it definitely feels much faster.
It seems that the autocomplete takes a while to render and that it causes the perf bottleneck.
It doesn't seem to be an issue with the grid.

**Comment by oliviertassinari** [comment] 2021-06-03 14:40
> It seems that the autocomplete takes a while to render and that it causes the perf bottleneck.

@dtassone Yeah, there is some truth to it. First, I think that we can rule out the Autocomplete and reduce the issue to the TextField as React doesn't render anything, and only the TextField is visible. See the difference when scrolling:

<img width="444" alt="Capture d’écran 2021-06-03 à 16 37 39" src="https://user-images.githubusercontent.com/3165635/120663393-4493cd00-c48a-11eb-80b3-686518920204.png">

TextField: https://r4wv7.csb.app/

<img width="445" alt="Capture d’écran 2021-06-03 à 16 37 46" src="https://user-images.githubusercontent.com/3165635/120663420-49f11780-c48a-11eb-9779-08ee9f8a78df.png">

raw input: https://sxi42.csb.app/

**Comment by dtassone** [comment] 2021-06-04 15:31
With Ant design autocomplete https://qhlrp.csb.app/

**Comment by edudar** [comment] 2021-06-16 22:57
JFYI, playing with `pointerEvents` might have rather unexpected side effects. I'm using [testing library](https://github.com/testing-library/user-event/pull/631) and got a handful of test failures after upgrading to the latest version that introduced support for `pointer-events: 'none'` because nothing in the grid was suddenly clickable. Upgrading to alpha31 with #1829 fixes this because `'none'` is gone and elements are considered clickable again.

**Comment by dancernogorsky** [comment] 2021-06-22 23:05
> ```tsx
>   {
>     field: "nameA",
>     headerName: "Name A",
>     disableClickEventBubbling: true,
>     width: 200,
>     renderCell: (params) => <MyAutoComplete {...params} />
>   },
> ```

@dtassone  I was testing this out and noticed if you pass in {...params} to the component, it will re-render every time. This is because you are passing the api, and entire grid state which is going to be different every time.

I tried just passing in {params.row}, and it seems to be working as expected. Still need to be improved, but atleast I am seeing a bump in performance.

**Comment by oliviertassinari** [comment] 2021-06-22 23:11
@dancernogorsky Are you using the latest version? If you have a reproduction it would help. This should no longer be true with the latest version.

I'm closing as the conclusion was that the issue is not with the data grid, but the text field.

**Closed by oliviertassinari** 2021-06-22 23:11 UTC
Labels: component: DataGrid, performance

**Comment by dildamaara** [comment] 2022-10-20 01:40
Not sure why it's closed. It's still happening.
Just use any component within renderCell and it will slow down on scrolling horizontally/vertically.
Issue is not with Textfield

**Comment by sebabratakundu** [comment] 2023-01-18 13:35
> > ```tsx
> >   {
> >     field: "nameA",
> >     headerName: "Name A",
> >     disableClickEventBubbling: true,
> >     width: 200,
> >     renderCell: (params) => <MyAutoComplete {...params} />
> >   },
> > ```
> 
> @dtassone I was testing this out and noticed if you pass in {...params} to the component, it will re-render every time. This is because you are passing the api, and entire grid state which is going to be different every time.
> 
> I tried just passing in {params.row}, and it seems to be working as expected. Still needs to be improved, but atleast I am seeing a bump in performance.

yah, non-primitive props will always trigger re-rendering. So we have to memo its value before pass it to our custom comp. In this case its not possible. so we can pass the prop and inside our component and memo it , and then return the memo render result. This helps me to get a performance boost by pausing down the re-rendering of the elements which are returned by our custom comp.

![image](https://user-images.githubusercontent.com/44576979/213184784-71a883b0-4893-430a-9ff1-18ff673a1d23.png)

Here `DataTableActionButton` is the custom element. its re-rendering everytime. but the returned compent result is memoized
