### ISSUE TITLE
[DataGridPro] "Hide all" and "Show all" does not call "onChangeColumnsVisibility"

### ISSUE THREAD

**Issue by tfcb93** [mui-org/material-ui-x#2198] opened 2021-07-23 16:36 UTC
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Inside the columns preference menu (using GridToolbarColumnsButton) when I click some of the switches, it can show or hide a desirable column, and it will call onChangeColumnsVisibility (due to the change of a single column). Although, when I click to show all or hide all bellow the preferences menu it doesn't active onChangeColumnsVisibility, and this way I can't grab the actual state of the columns, if they are all hidden or not.
I tried to do using onStateChange, but this is triggered almost all the time by anything inside the XGrid.
I'm registering as a bug cause I believe that onChangeColumnsVisibility should be triggered by those two as well.
## Expected Behavior 🤔
When click "Hide all" or "Show all" it will call "onChangeColumnsVisibility" as well, returning the actual array of columns updated with it respective values on the hide attribute.

## Steps to Reproduce 🕹
Insert a GridToolbarColumnsButton on a XGrid, implement onChangeColumnsVisibility and try to call it using "Hide all" and "Show all".

**Comment by flaviendelangle** [comment] 2021-07-26 08:55
We currently only have a callback for single column visibility change

```ts
export interface GridColumnVisibilityChangeParams {
  /**
   * The field of the column which visibility changed.
   */
  field: string;
  /**
   * The column of the current header component.
   */
  colDef: any;
  /**
   * API ref that let you manipulate the grid.
   */
  api: any;
  /**
   * The visibility state of the column.
   */
  isVisible: boolean;
}

  /**
   * Callback fired when a column visibility changes.
   * @param param With all properties from [[GridColumnVisibilityChangeParams]].
   */
  onColumnVisibilityChange?: (param: GridColumnVisibilityChangeParams) => void;
```

This callback takes the `field` so we can't just call it once when toggling all the columns at once.
We could either

1. add a `onColumnsVisibilityChange` that is called whenever the visibility of a column changes, but with all the columns in the params (it would also be called when a single column visibility is changed)

2. add a `onAllColumnsVisibilityChange` that is called only when toggling all the columns at once 

3.  call `onColumnVisibilityChange` for every columns toggled when toggling all

4. call `onColumnVisibilityChange` once when toggle all columns but without the `field` / `colDef` params (seems quite hacky)


Right now, I don't see any event that you could listen to have this change, except `stateChange` which is very low level.

**Comment by DanailH** [comment] 2021-07-26 10:02
I quickly checked how the `Hide All` / `Show All` is implemented and it seems that they are not actually using the provided API -> `setColumnVisibility`. There is the code that hides or shows all columns https://github.com/mui-org/material-ui-x/blob/master/packages/grid/_modules_/grid/components/panel/GridColumnsPanel.tsx#L56-L68

We could just call the `setColumnVisibility` API since we are already looping through all the columns?

A potential solution would be as follows:

```diff
--- a/packages/grid/_modules_/grid/components/panel/GridColumnsPanel.tsx
+++ b/packages/grid/_modules_/grid/components/panel/GridColumnsPanel.tsx
@@ -55,12 +55,7 @@ export function GridColumnsPanel() {

   const toggleAllColumns = React.useCallback(
     (value: boolean) => {
-      apiRef!.current.updateColumns(
-        columns.map((col) => {
-          col.hide = value;
-          return col;
-        }),
-      );
+      columns.forEach((column) => apiRef!.current.setColumnVisibility(column.field, value));
     },
     [apiRef, columns],
   );
```

**Comment by flaviendelangle** [comment] 2021-07-26 10:17
The issue here is that is would rerun `updateColumnsWidth` for each columns, which would make the complexity `n**2` (n being the amount of columns).

**Comment by DanailH** [comment] 2021-07-26 10:34
True, that's why I marked it as a possible solution. A better approach would be to batch the changes and emit a single event. Another option is to structure the API as follows:

- `onColumnsVisibilityChange` as part of the grid props that returns an array
- `onColumnVisibilityChange` as part of the `GridColDef`

**Comment by oliviertassinari** [comment] 2021-07-28 14:43
This issue resonates with point 2. of https://github.com/mui-org/material-ui-x/issues/1412#issuecomment-860935241

**Comment by flaviendelangle** [comment] 2021-11-17 11:47
Here is an updates reproduction case from #3207 Visit https://codesandbox.io/s/basicfilteringgrid-material-demo-forked-78j8g?file=/demo.js

**Comment by Arzh42** [comment] 2022-01-03 10:39
Hello, I'm currently blocked by this issue, do you know if there is some way to get around this issue or to hide the hideAll and showAll buttons until a better solutions ?

**Comment by zhikin2207** [comment] 2022-01-04 17:27
Blocked as well, do you know about any of possible overhead solutions?

**Comment by flaviendelangle** [comment] 2022-01-05 09:46
I will probably start working on https://github.com/mui-org/material-ui-x/issues/1412#issuecomment-860935241 soon
I will most likely add a `visibleColumns` `onVisibleColumnsChange` callbacks. Switching to a method that receives all the visible columns will allow to also track the "hide all" / "show all" toggle.

**Comment by david-ic3** [comment] 2022-01-05 13:05
I have the same issue, blocked with this one as Visibility state is in a controlled mode. 

@flaviendelangle , your solution would be fine

**Comment by Arzh42** [comment] 2022-01-05 14:59
Yes your solution seems fine for me too

**Closed** 2022-01-19 16:23 UTC
Labels: enhancement, component: DataGridPro, pro plan
