### ISSUE TITLE
Data Grid customization example demo had a runtime error!

### ISSUE THREAD

**Issue by DimitarTerzov** [mui-org/material-ui-x#927] opened 2021-01-25 08:50 UTC
When I hide two columns one after another demo breaks

This is the link to example:
https://material-ui.com/components/data-grid/rendering/#customization-example

I run example on Google Chrome: Version 87.0.4280.141

This is the error message:
TypeError: Cannot read property 'width' of undefined

**Comment by DanailH** [comment] 2021-01-26 09:06
Hi @DimitarTerzov thanks for reporting this but it seems that it is a duplicate of https://github.com/mui-org/material-ui-x/issues/856. We already fixed it and the fix will be part of the next release.

**Comment by DanailH** [comment] 2021-01-26 09:07
Duplicate of https://github.com/mui-org/material-ui-x/issues/856

**Closed** 2021-01-26 09:08 UTC
Labels: duplicate
