### ISSUE TITLE
[DataGrid] Row Checkboxes: spacebar does not select row

### ISSUE THREAD

**Issue by petermikitsh** [mui-org/material-ui-x#700] opened 2020-12-06 19:18 UTC
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

- Select a data row checkbox, and press the spacebar
- Observe the row is not selected

## Expected Behavior 🤔

- Select data row checkbox, press spacebar, row is selected

## Steps to Reproduce 🕹

Steps:

1. Go to https://material-ui.com/components/data-grid/#mit-version
2. Tab focus a row checkbox (not the "select all/none" checkbox)
3. Press spacebar

## Notes

On the commercial XGrid version, the same problem exists, but there's an added effect of paging the table (it scrolls down a bit).

**Comment by oliviertassinari** [comment] 2020-12-06 19:42
It was partially fixed in #673: https://master--material-ui-x.netlify.app/components/data-grid. I have opened #701 for fixing it completely.

**Comment by oliviertassinari** [comment] 2020-12-30 19:21
It looks like we have overlooked #673. While the two issues we are trying to solve were surfaced by the fix. I have also found regression #797. We might want to start fixing the regression.

**Closed** 2021-01-04 14:58 UTC
Labels: accessibility, bug 🐛, component: DataGrid
