### ISSUE TITLE
Consider enabling auto focus on filter by column

### ISSUE THREAD

**Issue by olhapi** [mui-org/material-ui-x#2201] opened 2021-07-24 07:56 UTC
Consider enabling autofocus on value input field of filter by column.

- [ ] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

1) open column menu
![image](https://user-images.githubusercontent.com/4780263/126861327-2b43573a-99dc-47ac-bf3f-0121e88535cc.png)

2) click filter
![image](https://user-images.githubusercontent.com/4780263/126861347-3b8be1f9-5525-4539-9d9e-0d18b0eb5ca1.png)

3) in my opinion focus should be automatically switched to value input

The idea is to click Filter and be able to type search phrase right away.

## Order id 💳
**26955**

**Comment by oliviertassinari** [comment] 2021-07-25 20:42
Duplicate of #1783

**Closed by oliviertassinari** 2021-07-25 20:42 UTC
Labels: status: needs triage
