### ISSUE TITLE
[XGrid] An error occurred when rows is empty array

### ISSUE THREAD

**Issue by Bluefitdev** [mui-org/material-ui-x#1326] opened 2021-04-01 00:35 UTC
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Issue ONLY happens in XGrid, not in Data-grid

## Expected Behavior 🤔

If you go to my [sandbox](https://codesandbox.io/s/data-grid-bug-loading-empty-row-o90e5?file=/src/MyList.js) and change the import and component from `XGrid` to `DataGrid`, then both RowsOverlay and Loading works. However in my current production, it returns `TypeError: Cannot read property 'current' of undefined`. Reproducible by using `XGrid` component in the sandbox

Please help...

## Steps to Reproduce 🕹
[sandbox](https://codesandbox.io/s/data-grid-bug-loading-empty-row-o90e5?file=/src/MyList.js) 

## Your Environment 🌎
Browser: Chrome

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
npx: installed 2 in 4.577s

  System:
    OS: macOS 11.2.3
  Binaries:
    Node: 12.20.0 - ~/.nvm/versions/node/v12.20.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v12.20.0/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.20.0/bin/npm
  Browsers:
    Chrome: 89.0.4389.90
    Edge: Not Found
    Firefox: 76.0.1
    Safari: 14.0.3
  npmPackages:
    @material-ui/core: ^4.11.2 => 4.11.2
    @material-ui/icons: ^4.11.2 => 4.11.2
    @material-ui/lab: ^4.0.0-alpha.57 => 4.0.0-alpha.57
    @material-ui/pickers: 3.2.10 => 3.2.10
    @material-ui/styles:  4.11.2
    @material-ui/system:  4.11.2
    @material-ui/types:  5.1.0
    @material-ui/utils:  4.11.2
    @material-ui/x-grid: ^4.0.0-alpha.23 => 4.0.0-alpha.23
    @material-ui/x-license:  4.0.0-alpha.21
    @types/react:  17.0.0
    react: ^17.0.1 => 17.0.1
    react-dom: ^17.0.1 => 17.0.1
    styled-components: ^5.1.1 => 5.2.1
    typescript:  3.9.7
```
</details>

## Order id 💳
I have purchased the XGrid license as well, order: #23091

Thanks guys

**Comment by Bluefitdev** [comment] 2021-04-07 03:51
@oliviertassinari hey mate, any fix for this? Its literally just swapping the component. We want to use the XGrid features...

**Comment by dtassone** [comment] 2021-04-08 16:06
the problem is due to how you import `GridOverlay` in your `NoRowsOverlay` file.
As you use x-grid, it should come from the x-grid package. 

`import { GridOverlay } from "@material-ui/x-grid";` would fix your demo

**Comment by oliviertassinari** [comment] 2021-04-08 23:33
I'm reopening as there is an opportunity to improve the DX. I will share more details about my proposed solution tomorrow. The quick version is that we can warn when the grid components aren't composed correctly, avoiding the inefficiency cycle with opening an issue. I don't expect a large diff. The first time we implemented this kn the core was for v0, a long time ago.

**Comment by Bluefitdev** [comment] 2021-04-09 00:27
@dtassone, nice catch! Thanks for that

**Comment by dtassone** [comment] 2021-04-12 13:14
@oliviertassinari as discussed please open a separate issue for the warning.
Closing this one as fixed

**Closed by dtassone** 2021-04-12 13:14 UTC
Labels: component: DataGrid, docs

**Comment by oliviertassinari** [comment] 2021-04-12 22:05
I have simplified the reproduction down to https://codesandbox.io/s/data-grid-bug-loading-empty-row-forked-x20om?file=/src/App.js

**Comment by oliviertassinari** [comment] 2021-04-12 23:28
I have updated the issue description so other developers can find it.

**Comment by nemonemi** [comment] 2022-05-20 11:21
Should anyone come across this when configuring pagination, make sure to pass the correct value to the table.
In my case, I've passed the value of 50 to a table that has not that many pages, and that threw this error.
