### ISSUE TITLE
[Doc] add controlled example for XGrid resizing

### ISSUE THREAD

**Issue by david-iccube** [mui-org/material-ui-x#1683] opened 2021-05-17 06:27 UTC
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Missing controlled version of column resizing

## Motivation 🔦

The motivation is to have the column sizes saved into the browser local storage (could be another kind of storage). End users can get back their former grid state when navigating back to the use case.

Yes, there is a work around, just not very clean. I guess this is a general grid state issue.

**Comment by oliviertassinari** [comment] 2021-05-17 12:32
Duplicate of #820

**Closed by oliviertassinari** 2021-05-17 12:32 UTC
Labels: status: needs triage
