### ISSUE TITLE
Best practice for working with the selectionModel when default is "selected"

### ISSUE THREAD

**Issue by EdmundsEcho** [mui-org/material-ui-x#1868] opened 2021-06-10 15:08 UTC
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Context: 
* I'm loading the data using server-side pagination
* The grid uses the `checkboxSelection` option
* Key: All of the values start-off as selected in my data

Bad: The checkbox in the header displays the "partial" selection state when those values being displayed are all selected.

Good: The checkbox in the header displays the "none" selection state when none of the values being displayed are selected.

```jsx
    <XGrid  
      className={clsx('EtlUnit-ValueGrid')}
      loading={data.status === 'pending' ?? true}
      rows={rows}
      // pagination
      pagination
      paginationMode='server'
      page={data?.cache?.page - 1}
      pageSize={ROWS_PER_PAGE}
      rowCount={data?.cache?.totalCount ?? 0}
      onPageChange={({ page }) => setPageNumber(page)}
      onPageSizeChange={({ pageSize }) => setPageSize(pageSize)}
      columns={columns}
      onRowSelected={handleToggleValue}
      disableColumnSelector
      autoHeight
      // filtering
      filterRowMode='server'
      onFilterModelChange={handleFilterModelChange}
      // user input
      checkboxSelection
      selectionModel={selectionModel}
      onColumnHeaderClick={handleToggleAll}
      autoSize={false}
    />
```

## Expected Behavior 🤔

As of now, I'm not sure how the grid should consider the data *not yet loaded*, nor where I have provided some sort of default for those *not yet loaded*.

What I do know, is that the header should act consistently one way or the other.  Right now, the grid clearly assumes that what has not yet loaded is "not selected".  This is a reasonable default except that I'm using a default of "selected".

All in all, the expected behavior would be to configure a default "selected | notSelected" for the grid so that it starts off in the correct state in the header.

## Please advise

Given whether this is considered a bug, or just the need to better understand the best way to work with the `selectionModel` is likely arbitrary, what is the recommended way to control the initial state of the `selectionModel` using server-side, paginated data?  

As you can see in the grid set-up, I'm providing it the `selectionModel` prop that *only describes the page being displayed* (the only data in the state).  Should I be using the `apiRef` directly to frontload a version of the data I can infer using the total number of records available on the server?

PS: Given that my data starts as "all selected" I was considering just reversing the checkbox display and what it means to select a row (i.e., user clicks the first time => selected -> deselected).  My first try using the theme props override method failed:

```jsx
components={{
              Checkbox: {
                  checkedIcon: () => <Clear />,  // just reverse how the state is rendered
                  icon: () => <Check />,   // ... normally would use Clear
              },
            }}
```

... but this worked well (thank you for the new slot!):

```jsx
// using forwardRef in particular is required because the parent requires the DOM ref of the 
// underlying Check and Clear components (among other changes)

const Checkbox = React.forwardRef((e, ref) => {
  switch (true) {
    case e?.indeterminate ?? false:
      return <IndeterminateCheckBoxIcon innerRef={ref} color='primary' />;
    case e.checked:
      return <Clear innerRef={ref} />;
    default:
      return <Check innerRef={ref} color='primary' />;
  }
});
Checkbox.displayName = 'GridCheckbox';

components=  components: {
    Checkbox,
  },
```

**Comment by oliviertassinari** [comment] 2021-06-20 14:51
@EdmundsEcho I'm closing as no reproductions were provided. It might be a duplicate of #1782

**Closed by oliviertassinari** 2021-06-20 14:51 UTC
Labels: status: needs triage
