### ISSUE TITLE
Columns in DataGrid are getting nuts after dragging a link inside a cell

### ISSUE THREAD

**Issue by kjeske** [mui-org/material-ui-x#1960] opened 2021-06-23 10:38 UTC
When you have a link in one of the cells in the DataGrid and you try to drag it (hold and move), the columns will start to reorder and behave unexpectedly.

![matui](https://user-images.githubusercontent.com/3659976/123082684-95f70280-d41f-11eb-885e-35a860348802.gif)

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When you have a link in one of the cells in the DataGrid and you try to drag it (hold and move), the columns will start to reorder and behave unexpectedly.

## Expected Behavior 🤔

When you have a link in one of the cells in the DataGrid and you try to drag it (hold and move), the columns won't move.

## Steps to Reproduce 🕹

Steps:

1. Go to https://material-ui.com/components/data-grid/rows/#infinite-loading
2. Press a link inside of one of the cells and try to move it

## Context 🔦

Normal work

## Your Environment 🌎

No info

**Comment by oliviertassinari** [comment] 2021-06-24 21:17
Duplicate of #1579

**Comment by oliviertassinari** [comment] 2021-06-25 11:48
Duplicate of #1579

**Closed** 2021-06-25 11:48 UTC
Labels: component: DataGrid, duplicate
