### ISSUE TITLE
[XGrid][DataGrid] DataGrid's scrollbar behaviour not working correctly

### ISSUE THREAD

**Issue by VandekerkhoveBertil** [mui-org/material-ui-x#943] opened 2021-01-28 16:19 UTC
While working with the DataGrid component, I discovered some weird issues with the scrollbar's which I think (IMHO) aren't correct behaviour's.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Issue 1:

When there are not too much rows in the grid for the vertical scrollbar to be shown but the columns overflow the grid's widtd, the vertical scrollbar is shown:

![image](https://user-images.githubusercontent.com/32326988/106165513-79fe7600-618b-11eb-9d2e-cdaae281d29b.png)

If you simply make the columns smaller, you get the expected behaviour:

![image](https://user-images.githubusercontent.com/32326988/106165633-94385400-618b-11eb-93bd-0cc19cf6dd82.png)

Issue 2: 

When you than add more items to the grid to make it overflow the grid's height, there is happening something strange too. When the columns are overflowing too, you will see that the last item is cut off:

![image](https://user-images.githubusercontent.com/32326988/106165921-e7aaa200-618b-11eb-8b9d-6289c14ea4a6.png)
 
And if you then make the columns smaller, that issue is fixed but there is still a horizontal scrollbar shown (possible because of the vertical scrollbar):

![image](https://user-images.githubusercontent.com/32326988/106166040-0ad55180-618c-11eb-9307-4dd52f30909a.png)

## Expected Behavior 🤔
The expected behavior I want is that the vertical scroll bar is only shown when the height of the grid's viewport is overflown, and that the horizontal scroll bar is only shown when the width of the grid's viewport is overflown.

## Steps to Reproduce 🕹

Link to codepen: https://codesandbox.io/s/material-demo-forked-9h9su?file=/demo.js

For the first issue, you can place rows 9-11 in comments.
For the second issue, you can uncomment them again.

## Context 🔦

We want to make sure that the grid is adjusted to it's content, when there are less rows than the space the grid gets it should function like you are using autoHeight. But when the number of rows is larger than the space the grid gets we should be able to scroll in the grid with the correct scrollbar behaviour.

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
                        
```
 System:                                                 
  OS: Windows 10 10.0.19042                             
Binaries:                                               
  Node: 12.18.4 - C:\Program Files\nodejs\node.EXE      
  Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CM
  npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD         
Browsers:                                               
  Chrome: 87.0.4280.141                                 
  Edge: Spartan (44.19041.423.0), Chromium (88.0.705.50)
npmPackages:                                            
  @material-ui/core: 4.11.0 => 4.11.0                   
  @material-ui/icons: 4.9.1 => 4.9.1                    
  @material-ui/lab: ^4.0.0-alpha.56 => 4.0.0-alpha.56   
  @material-ui/pickers: ^3.2.10 => 3.2.10               
  @material-ui/styles:  4.10.0                          
  @material-ui/system:  4.9.14                          
  @material-ui/types:  5.1.0                            
  @material-ui/utils:  4.10.2                           
  @material-ui/x-grid: ^4.0.0-alpha.14 => 4.0.0-alpha.14
  @material-ui/x-license:  4.0.0-alpha.14               
  @types/react: ^16.9.41 => 16.9.41                     
  react: ^16.13.1 => 16.13.1                            
  react-dom: ^16.13.1 => 16.13.1                        
  typescript: ^3.9.6 => 3.9.6   
```
</details>

**Comment by oliviertassinari** [comment] 2021-01-30 13:25
- Issue 1 is expected, the horizontal scrollbar hides a part of the last row, and hence needs a vertical scrollbar
- Issue 2 is a duplicate of #660.

**Closed by oliviertassinari** 2021-01-30 13:25 UTC
Labels: status: needs triage

**Comment by ThomasStock** [comment] 2021-02-01 10:13
(I am a colleague of @VandekerkhoveBertil)

@oliviertassinari
Are you saying that there is no way to show a extra-wide grid without having a tiny vertical scrollbar appear?

Our use-case is that we need to show a grid with a large amount of columns to the user. 
It is very possible that the grid has only a few items.
Having a vertical scrollbar appear to show the last few pixels of the last row is unacceptable UX for our application and we mainly chose XGrid as part of our solution for the UX it can provide.

Is it possible to reconsider this issue as a bug?
Would it help if we re-report the first issue as a separate one?

**Comment by oliviertassinari** [comment] 2021-02-01 10:32
> Our use-case is that we need to show a grid with a large amount of columns to the user.
It is very possible that the grid has only a few items.

@ThomasStock I don't understand, you are in control of the height of the grid, you need to account for the horizontal scrollbar height to not have the vertical one.

**Comment by ThomasStock** [comment] 2021-02-01 11:01
@oliviertassinari My apologies, I did not notice in the codepen that we set a very specific maxHeight with no room to spare for the scrollbar.
Issue seems indeed at our side.
