### ISSUE TITLE
[DataGrid] Add option to stop bubbling of column headersort direction change event

### ISSUE THREAD

**Issue by joziahg** [mui-org/material-ui-x#1721] opened 2021-05-20 23:15 UTC
Sort direction change event for the column header component is bubbling up through my components causing weird behavior when implementing a custom column menu.

- [ x] The issue is present in the latest release.
- [ x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When opening a dialog from the column menu the only way to get any functionality is to sprinkle e.stopPropogation() here and there.

## Expected Behavior 🤔

Clicking in the column menu anywhere including child components does not change sort direction. 

## Steps to Reproduce 🕹

https://codesandbox.io/s/material-demo-forked-elw02?file=/demo.js
Steps:

1. Open column menu
2. open dialog within column menu
3. click anywhere or change any values in dialog
4. select closes dialog

## Context 🔦
Trying to make a column edit dialog accessible via the column menu

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>

```
    System:
    OS: Linux 4.19 Ubuntu 18.04.5 LTS (Bionic Beaver)
  Binaries:
    Node: 12.21.0 - ~/.nvm/versions/node/v12.21.0/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v12.21.0/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @emotion/react: ^11.4.0 => 11.4.0 
    @emotion/styled: ^11.3.0 => 11.3.0 
    @material-ui/core: ^5.0.0-alpha.34 => 5.0.0-alpha.34 
    @material-ui/icons: ^5.0.0-alpha.34 => 5.0.0-alpha.34 
    @material-ui/lab: ^5.0.0-alpha.34 => 5.0.0-alpha.34 
    @material-ui/private-theming:  5.0.0-alpha.33 
    @material-ui/styled-engine:  5.0.0-alpha.34 
    @material-ui/styles: ^5.0.0-alpha.33 => 5.0.0-alpha.33 
    @material-ui/system:  5.0.0-alpha.34 
    @material-ui/types:  6.0.0 
    @material-ui/unstyled:  5.0.0-alpha.34 
    @material-ui/utils:  5.0.0-alpha.33 
    @material-ui/x-grid: ^4.0.0-alpha.29 => 4.0.0-alpha.29 
    @material-ui/x-license:  4.0.0-alpha.29 
    @types/react:  17.0.6 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
```
</details>

**Comment by oliviertassinari** [comment] 2021-05-21 19:23
Interesting.

Point 3 can be solved like #1324 (and tested the same way).

```diff
diff --git a/packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx b/packages/grid/_modules_/grid/components/columnHeaders/
GridColumnHeaderItem.tsx
index 9a46f799..c8606022 100644
--- a/packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx
+++ b/packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx
@@ -82,12 +82,18 @@ export const GridColumnHeaderItem = React.memo(
     }

     const publish = React.useCallback(
-      (eventName: string) => (event: React.MouseEvent | React.DragEvent) =>
+      (eventName: string) => (event: React.MouseEvent | React.DragEvent) => {
+        // Ignore portal
+        if (!event.currentTarget.contains(event.target as HTMLElement)) {
+          return;
+        }
+
         apiRef!.current.publishEvent(
           eventName,
           apiRef!.current.getColumnHeaderParams(column.field),
           event,
-        ),
+        )
+      },
       [apiRef, column.field],
     );
```

Point 4 is a duplicate of #1314.

**Closed** 2021-11-03 13:11 UTC
Labels: bug 🐛, component: DataGrid
