### ISSUE TITLE
createMuiTheme input type doesn't support overrides or props for MuiDataGrid (TypeScript)

### ISSUE THREAD

**Issue by vktrl** [mui-org/material-ui-x#919] opened 2021-01-24 16:49 UTC
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

createMuiTheme function input type doesn't have props or overrides property for configuring MuiDataGrid.

## Expected Behavior 🤔

[Documentation](https://material-ui.com/api/data-grid/) suggests that it's possible to set default props and override CSS globally using theme.

## Steps to Reproduce 🕹

https://codesandbox.io/s/typescript-react-material-ui-forked-yg451

**Comment by oliviertassinari** [comment] 2021-01-26 20:28
This is basically the same problem that we had with the lab: https://github.com/mui-org/material-ui/issues/19427. We should apply the same solution. Note that the fewer repository, the easier this problem is to fix.

**Comment by oliviertassinari** [comment] 2021-07-07 09:56
The implementation is here https://github.com/mui-org/material-ui-x/blob/55972c6631773a70b04a1cdcf21ac758955b04ee/packages/grid/data-grid/src/DataGrid.tsx#L52 but not the types

**Comment by oliviertassinari** [comment] 2021-07-07 09:56
Duplicate of #1755

**Closed by oliviertassinari** 2021-07-07 09:56 UTC
Labels: component: DataGrid, duplicate
