### ISSUE TITLE
Total row prop for infinite loading: now = rows loaded, future = rows available

### ISSUE THREAD

**Issue by EdmundsEcho** [mui-org/material-ui-x#1883] opened 2021-06-12 22:02 UTC
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

The infinite loading feature is working nicely with access the apiRef to upsert records with each new batch once the user hits the end of the window.

My requests to the server provide a "totalCount" so I know in advance the total to expect (not required, but useful even when using infinity window).  

However, this is not a prop I can use in the `rowCount` prop current version of XGrid.  The prop is used to set the `MuiDataGrid-dataContainer` `min-height`.  If that number does  not match what is actually loaded into the grid, the `onScrollEnd` event won't fire as expected, but rather would let the user scroll, and scroll without seeing more than the first batch of records.

The idea for a new prop would be something that differentiates what the `MuiDataGrid-dataContainer` depends on and what is used to indicate "Total Rows" in the footer.

Now: 
```jsx
<XGrid rowCount={/* do not use if using infinity loading */}
```
Future:
option 1:
```jsx
<XGrid rowCount={data.pageInfo.totalCount} onRowsScrollEnd={...} />
```
option 2:
```jsx
<XGrid maxRowCount={data.pageInfo.totalCount  onRowsScrollEnd={...}}
```

The first option requires that the `data-container` ignore the prop when `typeof onRowsScrollEnd !== 'undefined'` to compute `min-height` (as of now, it uses the prop regardless). The conditional use of the prop would ensure  `pagination` still functions as expected.  Given that infinite loading and pagination are mutually exclusive states, it likely avoids needing option 2 that creates a new prop.

**Comment by oliviertassinari** [comment] 2021-06-12 23:56
Duplicate of #1247

**Closed by oliviertassinari** 2021-06-12 23:56 UTC
Labels: status: needs triage
