### ISSUE TITLE
[DataGrid] Columns to have a fluid width

### ISSUE THREAD

**Issue by amiranga** [mui-org/material-ui-x#379] opened 2020-09-24 11:47 UTC
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Summary 💡
As the `data-grid` document says, By default, the columns have a width of 100 pixels. We can override it by using the `width` property available in `ColDef`.
Is there an option for columns to have a fluid width so that columns will get a proportion of the width of the container?

## Examples 🌈

```
<div style={{ width: "100%"}}>
<DataGrid
  columns={[
    { field: 'id' },
    { field: 'username' },
    { field: 'age' },
  ]}
  rows={rows}
/>
</div>
```
If my window width is 900px. The column with for 'id', 'username' and 'age' should be 300px each.
Columns should resize automatically when window width changes.

## Motivation 🔦

In most of the table components, I have worked with, this is the default behavior. Is there a way to accomplish this using column props?? or should this be a new feature??

**Comment by oliviertassinari** [comment] 2020-09-30 10:24
Duplicate of #347

**Comment by oliviertassinari** [comment] 2020-09-30 10:25
@elisherer Mind that class names without Mui as a prefix are private. Use `.rendering-zone` at your own risk.

**Closed by oliviertassinari** 2020-09-30 10:25 UTC
Labels: component: DataGrid, duplicate

**Comment by FelipeBattistotti** [comment] 2021-07-07 04:13
> I also need this behavior
> 
> A workaround would be to use the following style overrides:
> 
> ```js
>          {
>             colCell: {
>               flex: 1,
>               minWidth: "1px !important",
>               maxWidth: "none !important"
>             },
>             viewport: {
>               "& .rendering-zone": {
>                 width: "initial !important",
>                 maxWidth: "initial !important"
>               }
>             },
>             row: {
>               width: "100% !important"
>             },
>             colCellWrapper: {
>               display: "flex"
>             },
>             cell: {
>               flex: 1,
>               minWidth: "1px !important",
>               maxWidth: "none !important",
>               "&:last-of-type": {
>                 minWidth: "0 !important",
>                 flex: 0
>               }
>             }
>          }
> ```
> 
> * Do not provide width for the columns in the ColDef[] array
> 
> **Update:**
> 
> * Unstable. Use at your own risk. (This sample uses a private use class "rendering-zone")
> * This will only stretch evenly the columns. It will not change dynamically according to content like tables do.



Hi @elisherer,
Did you resolve the problem with column fluid width?

Can you share a code example?

Thanks!
