### ISSUE TITLE
[XGrid] Performance issue when sorting/filtering 100k rows client-side

### ISSUE THREAD

**Issue by arheinjohnson** [mui-org/material-ui-x#1506] opened 2021-04-27 20:09 UTC
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When we use XGrid for 100k rows, performance is very slow and usually crashes the browser. For 50k rows, performance is still unacceptably slow. How can we improve the performance? What are the trade offs of server side filtering and server side paginating?

## Expected Behavior 🤔

Faster UX.

## Steps to Reproduce 🕹

https://codesandbox.io/s/awesome-framework-kqbcp?file=/src/Demo.tsx

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
- Browser:
    Chrome
- System:
    OS: Windows 10 10.0.18363
- Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
- Browsers:
    Chrome: 90.0.4430.85
    Edge: Spartan (44.18362.1474.0)
```
</details>

## Order id 💳

Order #23360

**Comment by oliviertassinari** [comment] 2021-04-27 20:57
@arheinjohnson Do you have a reproduction we can look into? Also, could you be more specific on what you mean by slow?

**Comment by arheinjohnson** [comment] 2021-04-27 21:09
Right, so scrolling and pagination are still great, but the sort and filter experience becomes painful. 

I was surprised to see this, because the Commercial version demo here is rather fast:
https://material-ui.com/components/data-grid/#commercial-version

Do you recommend against server side pagination and filtering?

I can create a reproduction.

**Comment by oliviertassinari** [comment] 2021-04-27 21:50
@arheinjohnson I'm confused. The reproduction is using client-side sorting and filtering but you seem to use the server-side.

**Comment by arheinjohnson** [comment] 2021-04-27 21:53
Oh my mistake for not being clear, I am using client-side and am asking how to improve performance. For example, would you recommend server-side if I have data sets > 100k rows? Or am I missing something else obvious about XGrid to make it perform faster?

**Comment by oliviertassinari** [comment] 2021-04-27 22:13
I have updated the reproduction to log the time a sort and filter would normally take: https://codesandbox.io/s/great-rain-uy0be?file=/src/Demo.tsx. You are right, it should be really fast: https://codesandbox.io/s/great-rain-uy0be?file=/src/Demo.tsx.

I can confirm that there is something significantly wrong. Sorting 100k rows in the live demo should take [at most 200ms](https://codesandbox.io/s/material-demo-forked-0d22r?file=/demo.tsx) not [~2000ms](https://material-ui.com/components/data-grid/#commercial-version).

**Comment by arheinjohnson** [comment] 2021-04-27 23:26
What do you recommend we do in the short term, or will a resolution be available sooner than later?

**Comment by oliviertassinari** [comment] 2021-04-28 00:03
@dtassone was planning to work on performance issues this sprint.

**Comment by dtassone** [comment] 2021-04-28 16:23
I have removed the heavy work of the params that we send in events.

**Comment by arheinjohnson** [comment] 2021-04-28 16:34
Sorry if this is obvious, do we need to upgrade XGrid to pull the performance improvements?

**Comment by oliviertassinari** [comment] 2021-04-28 16:41
@arheinjohnson check the CI status of #1513, you should find a codesandbox.io step. Open it. Then, you should find a version of the component you can install with the WIP changes.

**Comment by oliviertassinari** [comment] 2021-04-28 16:43
https://github.com/mui-org/material-ui/blob/next/CONTRIBUTING.md#how-can-i-use-a-change-that-wasnt-released-yet

**Comment by dtassone** [comment] 2021-04-28 17:27
I believe there is clear perf improvement
https://github.com/mui-org/material-ui-x/pull/1513#issuecomment-828636527

**Comment by arheinjohnson** [comment] 2021-04-28 17:54
Thanks for this! Weird, when I went to sort "Commodity" ASC, I received an unresponsive page error. Due to firewall, I'm unable to upload a screenshot.

**Comment by arheinjohnson** [comment] 2021-05-06 21:05
So, how much faster should server-side filtering and server-side pagination be for XGrid? Wondering if you can help me understand the trade-offs for server-side versus client-side.

**Comment by oliviertassinari** [comment] 2021-05-06 21:35
@arheinjohnson It would depend.

Cost of client-side filtering:

1. Loading all the data, slow, I doubt you can load more than 10k records, unless spending a couple of seconds.
2. Filtering client-side, almost instant, ~1ms

Cost of server-side filtering:

1. The network request ~50ms, each time
2. Run the query on the database ~50ms?
3. Overhead, 100ms?

**Comment by arheinjohnson** [comment] 2021-05-06 21:52
That helps, thanks @oliviertassinari. We'll try out server-side filtering and server-side pagination to see if we get our desired performance. Some of the database queries can be cut out with caching. Is there any hope for very fast client-side loading and filtering in the future for > 100k records?

**Comment by oliviertassinari** [comment] 2021-05-06 21:55
> Is there any hope for very fast client-side loading and filtering in the future for > 100k records?

For 100k records, I don't see why it would take 1ms for us, with proper caching. For >100k, you might start to hit other issues: #240.

**Comment by arheinjohnson** [comment] 2021-05-06 22:13
Feels like I'm going in a circle a bit, sorry for that. Well we upgraded from 4.0.0-alpha.24 up to 4.0.0-alpha.27 and it seems to have alleviated our XGrid performance problems for 100k rows for now. Sorting and filtering client-side are pretty fast. Will let you know as we learn more! Thank you for the component!

**Comment by oliviertassinari** [comment] 2021-05-06 22:21
@arheinjohnson Actually, I'm curious. How did you manage to load 100k records client-side? I had always assumed that this would be performed server-side unless run inside an electron environment with direct fs access.

**Comment by arheinjohnson** [comment] 2021-05-06 22:25
I am not sure what you are asking, I'm using a standard http request to retrieve rows from an API. By the way I am using pagination.

**Comment by dtassone** [comment] 2021-05-07 09:35
To load large amount of data on the client side, you should batch server updates with a stream, and update the grid using
`apiRef.current.updateRows(<batch here>)`

Also performance will improve when we merge #1513

**Comment by arheinjohnson** [comment] 2021-05-07 16:22
@dtassone Could you write a demo of updating the grid using apiRef.current.updateRows(<batch here>)? I'm not familiar with streaming server updates.

**Comment by zig145** [comment] 2021-05-12 01:01
I want to jump in to point out that there is major performance issue with filtering since 4.0.0-alpha.23.  You can see it here https://material-ui.com/components/data-grid/#commercial-version with filter "commodity contains 'soy'".  That is taking more than 1m to filter.  If you open up the code sandbox for this example (https://codesandbox.io/s/cgbej), and switch to 4.0.0-alpha.22, you'll see that filter performs in milliseconds speed rather than minutes.  It doesn't look to me like #1513 addresses this, but I could be wrong.

**Comment by oliviertassinari** [comment] 2021-05-13 22:59
@dtassone Should we close this issue? It seems that we have fixed the main pain point (slow filtering).

**Closed** 2021-05-14 08:08 UTC
Labels: components: XGrid, important, performance
