### ISSUE TITLE
[Utils][DataGrid] Regression seen on 5.2.2 -> 5.2.3

### ISSUE THREAD

**Issue by hafley66** [mui-org/material-ui-x#3389] opened 2021-12-09 15:55 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Getting errors when trying to open DataGrid column selector from column menu.
I know the demo is with data grid, but the error is throwing on version changes of `@mui/material`, so I have put it here. Feel free to move.

### Expected behavior 🤔

Reproducible sandboxes:
Confirmation of expected behavior on 5.2.2: 
https://codesandbox.io/s/regression-on-column-selector-works-in-5-2-2-pqsj9?file=/demo.js

Confirmation of regression on 5.2.3:
https://codesandbox.io/s/regression-on-column-selector-broken-in-5-2-3-p18fi?file=/demo.js

### Steps to reproduce 🕹

1. Click on triple dot menu on hovering a column header
2. Click on menu item 'Show Columns'
3. This only happens from `@mui/material@5.2.2` -> `@mui/material@5.2.3`

Minified error comes out as:
`(0 , $csb___mui_utils.internal_resolveProps) is not a function`

**Comment by flaviendelangle** [comment] 2021-12-10 13:39
Thanks for the issue
I can't reproduce it even with your 5.2.3 Codesandbox.
Could you give me your browser name and version ?

**Comment by hafley66** [comment] 2021-12-10 13:55
It chose latest dg which is at 5.2.0 now, likely was issue in 5.1.0. I have pinned version 5.1.0 in both sandboxes. If not a severe issue, then feel free to close, while I was reproducing I believe thats when 5.2.0 came out, but didn't see any mention of this fix in changelog

**Comment by m4theushw** [comment] 2021-12-10 14:30
I can see the error opening the CodeSandbox. But if I download it as .zip and run, the error is gone. @hafley66 do you see this error in your application?

`internal_resolveProps` was added in @mui/utils 5.2.3, however, we have `^5.2.2` as version so it should pick the latest package version.

**Comment by hafley66** [comment] 2021-12-10 15:06
Not in my actual application, we have wrappers for mui/material and datagrid, and I constrain versions that way for all projects that use it. So not seen in prod or staging envs, but I will also download zip and see what happens

**Comment by oliviertassinari** [comment] 2022-01-29 18:10
I could simplify the reproduction down to https://codesandbox.io/s/regression-on-column-selector-broken-in-5-2-3-forked-but84. It looks like a bug codesandbox. I'm closing.

**Closed by oliviertassinari** 2022-01-29 18:10 UTC
Labels: component: data grid
