### ISSUE TITLE
DataGrid column reorder bug when used with HTML Drag and Drop API

### ISSUE THREAD

**Issue by Sam-CellarDoor** [mui-org/material-ui-x#1930] opened 2021-06-18 22:14 UTC
# DataGrid column reorder bug when used with HTML Drag and Drop API

- [ ] The issue is present in the latest release.
- [x ] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When the html drag & drop API is used to make an element (in this case, a mui list item) draggable, and that element is dragged over a DataGrid component, the DataGrid's columns are rapidly shuffled. 

## Expected Behavior 🤔

Devs should be able to make DataGrid cells that are drop containers, and be able to drag elements from outside the DataGrid into those cells without triggering a UX breaking rapid shuffle of columns. This should likely not happen at all, but should particularly not happen when disableColumnReorder={true} is applied to the DataGrid (as in the following codesandbox example).

## Steps to Reproduce 🕹

  https://codesandbox.io/s/mui-datagrid-dd-bug-oxjix?file=/src/App.js

Steps:

 1. Drag the tag elements from the left into the DataGrid
 2. Observe rapid column shuffling

## Context 🔦

  Original issue was discovered in React-Typescript project, but works the same in JS (see the codesandbox example). As described in "Expected Behavior" I am trying to make elements that can be dragged into the DataGrid and dropped into custom component drop containers created using renderCell. This feature will allow the application of "tags" on rows of data in a ux friendly manner (drag and drop).

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.12 - /usr/local/bin/npm
  Managers:
    Homebrew: 3.1.4 - /usr/local/bin/brew
    pip3: 21.1 - /Library/Frameworks/Python.framework/Versions/3.9/bin/pip3
  Utilities:
    Git: 2.31.1 - /usr/local/bin/git
  Browsers:
    Chrome: 91.0.4472.106
    Firefox: 89.0.1
</details>

**Comment by oliviertassinari** [comment] 2021-06-18 22:43
Duplicate of #1579

**Closed** 2021-06-18 22:43 UTC
Labels: duplicate
