### ISSUE TITLE
[DataGrid] Filter UI loses focus while searching / typing

### ISSUE THREAD

**Issue by hmaack** [mui-org/material-ui-x#1493] opened 2021-04-26 10:42 UTC
While using the filter in the table header the filter text field loses the focus after the user stops typing and the search starts. It looks like the header cell somehow steels the focus? This issue is present in the latest Firefox 88.0. 

![mui-bug](https://user-images.githubusercontent.com/1143110/116069329-8c555680-a68b-11eb-8d68-97a113e55222.gif)

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

The text field in the filter loses the focus after typing. 

## Expected Behavior 🤔

I expect that the text field is still focused so that I can modify my filter parameter without selecting the text field again. 

## Steps to Reproduce 🕹

Steps:

1. Open https://cb7st.csb.app/
2. Click in any header cell to sort it
3. Click the menu icon to open the filter dialog
4. Type some random characters and wait while the search starts
5. The focused UI element changed

## Context 🔦

Doesn't matter I guess. 

## Your Environment 🌎

Sandbox-App: https://cb7st.csb.app/
Sandbox: https://codesandbox.io/s/cb7st

**Comment by m4theushw** [comment] 2021-04-26 13:18
I managed to reproduce the bug in Firefox and Chrome.

![focus-bug](https://user-images.githubusercontent.com/42154031/116088851-a174ba00-a678-11eb-808c-1ef74be5cd6b.gif)

**Comment by dtassone** [comment] 2021-04-26 13:52
> I managed to reproduce the bug in Firefox and Chrome.
> 
> ![focus-bug]

The focus is going back to the column header, I think that's because, when you erase the value, there is no filter for a render which put the focus back on the col header.

**Comment by dtassone** [comment] 2021-04-26 13:52
Why is it specific to firefox? 🤔

**Comment by oliviertassinari** [comment] 2021-04-26 14:31
A reminder for https://github.com/mui-org/material-ui-x/pull/1205#discussion_r596918212 😁

https://github.com/mui-org/material-ui-x/blob/f5642ae7fe19ed8b8998182c1a6f49c2ff7bb149/packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx#L153-L158

**Comment by hmaack** [comment] 2021-04-26 14:49
Somehow I couldn't reproduce this bug in Chrome. ( Version 90.0.4430.85 (Official Build) (x86_64) ) Are you able @oliviertassinari ?

**Comment by hmaack** [comment] 2021-04-26 14:52
I couldn't reproduce this on Chrome ( Version 90.0.4430.85 (Official Build) (x86_64) ) Are you able @dtassone ? That's why I thought it's important to define. 👍🏼  - In any case, I'm happy you could reproduce this. 👍🏼

**Comment by dtassone** [comment] 2021-04-26 16:33
I believe it will be fixed when we merge #1421 
https://codesandbox.io/s/create-react-app-with-typescript-forked-01cvk

**Closed** 2021-04-28 15:36 UTC
Labels: bug 🐛, component: DataGrid
