### ISSUE TITLE
[bug] - `onCellEditCommit` now has old value on commit on version 5.2+

### ISSUE THREAD

**Issue by mfaheemakhtar** [mui-org/material-ui-x#3826] opened 2022-02-03 08:50 UTC
### Order ID 💳

#30063

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

`onCellEditCommit` now has old value on commit on version 5.2+.

Causing the grid values to commit wrong values to the server.

Works fine on 5.2.x

https://codesandbox.io/s/oncellcommit-7sid1?file=/src/App.tsx

This library need some focus on testing side.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment] 2022-02-03 09:59
https://user-images.githubusercontent.com/3309670/152319987-7c10ccbe-e0c3-4a74-9f64-1707029d7049.mp4

**Comment by flaviendelangle** [comment] 2022-02-03 10:16
@m4theushw most likely caused by #3617. The commit takes place before the value is updated.
I let you handle that one since you know the codebase :+1:

**Comment by m4theushw** [comment] 2022-02-03 12:49
Duplicate of #3729

#3825 is gonna fix this issue. Here's the updated CodeSandbox with the unreleased fix: https://codesandbox.io/s/oncellcommit-forked-z1kcx?file=/src/App.tsx

**Closed by m4theushw** 2022-02-03 12:49 UTC
Labels: bug 🐛, regression, feature: Editing, support: commercial
