### ISSUE TITLE
[DataGrid] Rendering wrong virtualRowsCount

### ISSUE THREAD

**Issue by qkdreyer** [mui-org/material-ui-x#671] opened 2020-12-01 12:44 UTC
Data-Grid (sometimes) provides a wrong rendering

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

TotalRowCount is not synced with RenderingZone children

## Expected Behavior 🤔

TotalRowCount should be synced with RenderingZone children

## Steps to Reproduce 🕹

Sadly, I didn't manage to produce a reproductible demo, I hope that the following context will be enough to find what's wrong

## Context 🔦

```
index-esm.js:1183 Material-UI: Viewport - Rendering ViewPort
index-esm.js:1183 Material-UI: useVirtualRows - applying scrollTop  0
index-esm.js:1183 Material-UI: GridComponent - Overriding state with props.state
index-esm.js:1183 Material-UI: Viewport - Rendering ViewPort
index-esm.js:1183 Material-UI: useVirtualRows - applying scrollTop  0
index-esm.js:1183 Material-UI: useApi - Clearing rowClick event
index-esm.js:1183 Material-UI: useApi - Clearing stateChange event
index-esm.js:1183 Material-UI: useApi - Clearing keydown event
index-esm.js:1183 Material-UI: useApi - Clearing selectionChange event
index-esm.js:1183 Material-UI: useApi - Clearing pageChange event
index-esm.js:1183 Material-UI: useApi - Binding rowClick event
index-esm.js:1183 Material-UI: useApi - Binding stateChange event
index-esm.js:1183 Material-UI: useColumns - Hydrating Columns with default definitions
index-esm.js:1183 Material-UI: useColumns - Calculating visibleColumns
index-esm.js:1183 Material-UI: useColumns - Calculating columnsMeta
index-esm.js:1183 Material-UI: useColumns - Building columns lookup
index-esm.js:1183 Material-UI: useColumns - Updating columns state.
index-esm.js:1183 Material-UI: useVirtualColumns - Clearing previous renderedColRef
index-esm.js:1183 Material-UI: useApi - Binding keydown event
index-esm.js:1183 Material-UI: useApi - Binding selectionChange event
index-esm.js:1183 Material-UI: useApi - Binding pageChange event
index-esm.js:1183 Material-UI: Viewport - Rendering ViewPort
index-esm.js:1183 Material-UI: useVirtualRows - applying scrollTop  0
scheduler.development.js:147 [Violation] 'message' handler took 203ms
index-esm.js:1183 Material-UI: useContainerProps - Calculating container sizes.
index-esm.js:1183 Material-UI: useContainerProps - window Size - W: 534 H: 434 
index-esm.js:1183 Material-UI: useContainerProps - viewportPageSize:  8, rzPageSize: 16, viewportMaxPage: 1
index-esm.js:1183 Material-UI: useContainerProps - returning container props {virtualRowsCount: 1, renderingZonePageSize: 16, viewportPageSize: 8, totalSizes: {…}, dataContainerSizes: {…}, …}
index-esm.js:1183 Material-UI: Viewport - Rendering ViewPort
index-esm.js:1183 Material-UI: useVirtualRows - applying scrollTop  0
index-esm.js:1183 Material-UI: useApi - Clearing keydown event
index-esm.js:1183 Material-UI: useApi - Binding keydown event
index-esm.js:1183 Material-UI: useVirtualRows - gridState.containerSizes updated, updating viewport. 
index-esm.js:1183 Material-UI: useVirtualRows - Handling scroll Left: 0 Top: 0
index-esm.js:1183 Material-UI: useVirtualColumns - Columns from name to length
index-esm.js:1183 Material-UI: useVirtualColumns - Column buffer: 2, tolerance: 1
index-esm.js:1183 Material-UI: useVirtualColumns - Previous values  => first: 0, last: 0
index-esm.js:1183 Material-UI: useVirtualColumns - Current displayed values  => first: 0, last: 2
index-esm.js:1183 Material-UI: useVirtualColumns - Difference with first: 1 and last: 3 
index-esm.js:1183 Material-UI: useVirtualColumns - New columns state to render {firstColIdx: 0, lastColIdx: 2, leftEmptyWidth: 0, rightEmptyWidth: 1}
index-esm.js:1183 Material-UI: useVirtualRows -  viewportHeight:434, rzScrollTop: 0, scrollTop: 0, current page = 0
index-esm.js:1183 Material-UI: useVirtualRows - reRender: trigger rendering
index-esm.js:1183 Material-UI: useVirtualRows - totalRowCount has changed to 1, updating viewport.
index-esm.js:1183 Material-UI: useVirtualRows - Handling scroll Left: 0 Top: 0
index-esm.js:1183 Material-UI: useVirtualColumns - Columns from name to length
index-esm.js:1183 Material-UI: useVirtualColumns - Column buffer: 2, tolerance: 1
index-esm.js:1183 Material-UI: useVirtualColumns - Previous values  => first: 0, last: 2
index-esm.js:1183 Material-UI: useVirtualColumns - Current displayed values  => first: 0, last: 2
index-esm.js:1183 Material-UI: useVirtualColumns - Difference with first: 1 and last: 1 
index-esm.js:1183 Material-UI: useVirtualColumns - No rendering needed on columns
index-esm.js:1183 Material-UI: useVirtualRows -  viewportHeight:434, rzScrollTop: 0, scrollTop: 0, current page = 0
index-esm.js:1183 Material-UI: Viewport - Rendering ViewPort
index-esm.js:1183 Material-UI: useVirtualRows - applying scrollTop  0
index-esm.js:1183 Material-UI: Viewport - Rendering ViewPort
index-esm.js:1183 Material-UI: useVirtualRows - applying scrollTop  0
index-esm.js:1183 Material-UI: GridComponent - Overriding state with props.state
index-esm.js:1183 Material-UI: Viewport - Rendering ViewPort
index-esm.js:1183 Material-UI: useVirtualRows - applying scrollTop  0
index-esm.js:1183 Material-UI: useVirtualColumns - Clearing previous renderedColRef
index-esm.js:1183 Material-UI: useVirtualRows - Handling scroll Left: 0 Top: 0
index-esm.js:1183 Material-UI: useVirtualColumns - Columns from name to length
index-esm.js:1183 Material-UI: useVirtualColumns - Column buffer: 2, tolerance: 1
index-esm.js:1183 Material-UI: useVirtualColumns - Previous values  => first: 0, last: 0
index-esm.js:1183 Material-UI: useVirtualColumns - Current displayed values  => first: 0, last: 2
index-esm.js:1183 Material-UI: useVirtualColumns - Difference with first: 1 and last: 3 
index-esm.js:1183 Material-UI: useVirtualColumns - New columns state to render {firstColIdx: 0, lastColIdx: 2, leftEmptyWidth: 0, rightEmptyWidth: 1}
index-esm.js:1183 Material-UI: useVirtualRows -  viewportHeight:434, rzScrollTop: 0, scrollTop: 0, current page = 0
index-esm.js:1183 Material-UI: useContainerProps - Calculating container sizes.
index-esm.js:1183 Material-UI: useContainerProps - window Size - W: 534 H: 454 
index-esm.js:1183 Material-UI: useApi - Clearing rowClick event
index-esm.js:1183 Material-UI: useApi - Clearing stateChange event
index-esm.js:1183 Material-UI: useApi - Clearing keydown event
index-esm.js:1183 Material-UI: useApi - Clearing selectionChange event
index-esm.js:1183 Material-UI: useApi - Clearing resize event
index-esm.js:1183 Material-UI: useApi - Clearing pageChange event
index-esm.js:1183 Material-UI: useApi - Binding rowClick event
index-esm.js:1183 Material-UI: useApi - Binding stateChange event
index-esm.js:1183 Material-UI: useColumns - Hydrating Columns with default definitions
index-esm.js:1183 Material-UI: useColumns - Calculating visibleColumns
index-esm.js:1183 Material-UI: useColumns - Calculating columnsMeta
index-esm.js:1183 Material-UI: useColumns - Building columns lookup
index-esm.js:1183 Material-UI: useColumns - Updating columns state.
index-esm.js:1183 Material-UI: useVirtualColumns - Clearing previous renderedColRef
index-esm.js:1183 Material-UI: useApi - Binding keydown event
index-esm.js:1183 Material-UI: useApi - Binding selectionChange event
index-esm.js:1183 Material-UI: useSorting - row changed, applying sortModel
index-esm.js:1183 Material-UI: useContainerProps - Calculating container sizes.
index-esm.js:1183 Material-UI: useContainerProps - window Size - W: 534 H: 454 
index-esm.js:1183 Material-UI: useContainerProps - viewportPageSize:  8, rzPageSize: 16, viewportMaxPage: 1
index-esm.js:1183 Material-UI: useContainerProps - returning container props {virtualRowsCount: 6, renderingZonePageSize: 16, viewportPageSize: 8, totalSizes: {…}, dataContainerSizes: {…}, …}
index-esm.js:1183 Material-UI: useContainerProps - Calculating container sizes.
index-esm.js:1183 Material-UI: useContainerProps - window Size - W: 534 H: 454 
index-esm.js:1183 Material-UI: useContainerProps - viewportPageSize:  8, rzPageSize: 16, viewportMaxPage: 1
index-esm.js:1183 Material-UI: useContainerProps - returning container props {virtualRowsCount: 6, renderingZonePageSize: 16, viewportPageSize: 8, totalSizes: {…}, dataContainerSizes: {…}, …}
index-esm.js:1183 Material-UI: useApi - Binding resize event
index-esm.js:1183 Material-UI: useVirtualRows - totalRowCount has changed to 6, updating viewport.
index-esm.js:1183 Material-UI: useVirtualRows - Handling scroll Left: 0 Top: 0
index-esm.js:1183 Material-UI: useVirtualColumns - Columns from name to length
index-esm.js:1183 Material-UI: useVirtualColumns - Column buffer: 2, tolerance: 1
index-esm.js:1183 Material-UI: useVirtualColumns - Previous values  => first: 0, last: 0
index-esm.js:1183 Material-UI: useVirtualColumns - Current displayed values  => first: 0, last: 2
index-esm.js:1183 Material-UI: useVirtualColumns - Difference with first: 1 and last: 3 
index-esm.js:1183 Material-UI: useVirtualColumns - New columns state to render {firstColIdx: 0, lastColIdx: 2, leftEmptyWidth: 0, rightEmptyWidth: 1}
index-esm.js:1183 Material-UI: useVirtualRows -  viewportHeight:454, rzScrollTop: 0, scrollTop: 0, current page = 0
index-esm.js:1183 Material-UI: useVirtualRows - reRender: trigger rendering
index-esm.js:1183 Material-UI: useApi - Binding pageChange event
index-esm.js:1183 Material-UI: Viewport - Rendering ViewPort
index-esm.js:1183 Material-UI: useVirtualRows - applying scrollTop  0
index-esm.js:1183 Material-UI: useApi - Clearing keydown event
index-esm.js:1183 Material-UI: useApi - Binding keydown event
index-esm.js:1183 Material-UI: useContainerProps - Calculating container sizes.
index-esm.js:1183 Material-UI: useContainerProps - window Size - W: 534 H: 454 
index-esm.js:1183 Material-UI: useContainerProps - viewportPageSize:  8, rzPageSize: 16, viewportMaxPage: 1
index-esm.js:1183 Material-UI: useContainerProps - returning container props {virtualRowsCount: 6, renderingZonePageSize: 16, viewportPageSize: 8, totalSizes: {…}, dataContainerSizes: {…}, …}
index-esm.js:1183 Material-UI: useVirtualRows - totalRowCount has changed to 6, updating viewport.
index-esm.js:1183 Material-UI: useVirtualRows - Handling scroll Left: 0 Top: 0
index-esm.js:1183 Material-UI: useVirtualColumns - Columns from name to length
index-esm.js:1183 Material-UI: useVirtualColumns - Column buffer: 2, tolerance: 1
index-esm.js:1183 Material-UI: useVirtualColumns - Previous values  => first: 0, last: 2
index-esm.js:1183 Material-UI: useVirtualColumns - Current displayed values  => first: 0, last: 2
index-esm.js:1183 Material-UI: useVirtualColumns - Difference with first: 1 and last: 1 
index-esm.js:1183 Material-UI: useVirtualColumns - No rendering needed on columns
index-esm.js:1183 Material-UI: useVirtualRows -  viewportHeight:454, rzScrollTop: 0, scrollTop: 0, current page = 0
index-esm.js:1183 Material-UI: Viewport - Rendering ViewPort
index-esm.js:1183 Material-UI: useVirtualRows - applying scrollTop  0
index-esm.js:1183 Material-UI: useContainerProps - viewportPageSize:  8, rzPageSize: 16, viewportMaxPage: 1
index-esm.js:1183 Material-UI: useContainerProps - returning container props {virtualRowsCount: 1, renderingZonePageSize: 16, viewportPageSize: 8, totalSizes: {…}, dataContainerSizes: {…}, …}
index-esm.js:1183 Material-UI: useVirtualRows - totalRowCount has changed to 6, updating viewport.
index-esm.js:1183 Material-UI: useVirtualRows - Handling scroll Left: 0 Top: 0
index-esm.js:1183 Material-UI: useVirtualColumns - Columns from name to length
index-esm.js:1183 Material-UI: useVirtualColumns - Column buffer: 2, tolerance: 1
index-esm.js:1183 Material-UI: useVirtualColumns - Previous values  => first: 0, last: 2
index-esm.js:1183 Material-UI: useVirtualColumns - Current displayed values  => first: 0, last: 2
index-esm.js:1183 Material-UI: useVirtualColumns - Difference with first: 1 and last: 1 
index-esm.js:1183 Material-UI: useVirtualColumns - No rendering needed on columns
index-esm.js:1183 Material-UI: useVirtualRows -  viewportHeight:454, rzScrollTop: 0, scrollTop: 0, current page = 0
index-esm.js:1183 Material-UI: useVirtualRows - reRender: trigger rendering
index-esm.js:1183 Material-UI: Viewport - Rendering ViewPort
index-esm.js:1183 Material-UI: useVirtualRows - applying scrollTop  0
index-esm.js:96 [Violation] 'requestAnimationFrame' handler took 752ms
index-esm.js:1183 Material-UI: useApi - Clearing keydown event
index-esm.js:1183 Material-UI: useApi - Binding keydown event
index-esm.js:1183 Material-UI: useVirtualRows - totalRowCount has changed to 6, updating viewport.
index-esm.js:1183 Material-UI: useVirtualRows - Handling scroll Left: 0 Top: 0
index-esm.js:1183 Material-UI: useVirtualColumns - Columns from name to length
index-esm.js:1183 Material-UI: useVirtualColumns - Column buffer: 2, tolerance: 1
index-esm.js:1183 Material-UI: useVirtualColumns - Previous values  => first: 0, last: 2
index-esm.js:1183 Material-UI: useVirtualColumns - Current displayed values  => first: 0, last: 2
index-esm.js:1183 Material-UI: useVirtualColumns - Difference with first: 1 and last: 1 
index-esm.js:1183 Material-UI: useVirtualColumns - No rendering needed on columns
index-esm.js:1183 Material-UI: useVirtualRows -  viewportHeight:454, rzScrollTop: 0, scrollTop: 0, current page = 0
```

## Your Environment 🌎

| Tech          | Version |
| ------------- | ------- |
| Material-UI Data-Grid | v4.0.0-alpha.10 |
| React         | ^17.0.1 |
| Browser       | Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.193 Safari/537.36 |
| TypeScript    | N/A |

**Comment by oliviertassinari** [comment] 2020-12-01 15:34
@qkdreyer Do you have a visual illustration of the issue?

**Comment by qkdreyer** [comment] 2020-12-01 15:55
http://g.recordit.co/24JAOYda0C.gif

**Comment by qkdreyer** [comment] 2020-12-01 17:14
Log diff between a working and not working session :

![image](https://user-images.githubusercontent.com/717869/100773351-09dca980-3401-11eb-80a2-5f69a23224ce.png)

**Comment by qkdreyer** [comment] 2020-12-01 17:44
I can confirm this only happens randomly when container height get resized

**Comment by DanailH** [comment] 2021-05-12 12:45
Hi @qkdreyer I just noticed the version of the DataGrid that you are using (v4.0.0-alpha.10) can you try and update to the latest one we have (v4.0.0-alpha.28) and see if the issue persists because I can't seem to reproduce it now.

**Comment by DanailH** [comment] 2021-05-14 08:24
Hi @qkdreyer I tried to reproduce the issue with the version you specified but still wasn't able to (maybe I'm doing something wrong) https://codesandbox.io/s/material-demo-forked-zntvl?file=/demo.js

Either way, a lot of things changed since v4.0.0-alpha.10 especially how that state is managed when we introduced the filtering feature. Try the latest one and if the issue persists you can reopen the issue and we will have a look again. I'm closing it for now.

**Closed** 2021-05-14 08:24 UTC
Labels: bug 🐛, component: DataGrid
