### ISSUE TITLE
Error when updating rows.  Documentation shows blank when going to next page for server-side pagination.

### ISSUE THREAD

**Issue by raemounz** [mui-org/material-ui-x#608] opened 2020-11-20 03:02 UTC
Browser: Chrome
OS: Windows
@material-ui/data-grid version: ^4.0.0-alpha.9
Language: Typescript
Framework: React

[Code]
interface Props {
  data: any;
  ...
}
const DataTable: React.FC<Props> = (props: Props) => {
      ...
      const [rows, setRows] = useState<any>([]);
      useEffect(() => {
          if (props.data) {
            console.log("setting data", props.data.content);
            setRows(props.data.content);
            setRowCount(props.data.totalElements);
            setLoading(false);
          }
      }, [props.data]);
      ...
      <DataGrid
        rows={rows}
        columns={columns}
        pagination
        pageSize={pageSize}
        rowCount={rowCount}
        paginationMode="server"
        onPageChange={handlePageChange}
        loading={loading}
      />

[Issue]
Everytime the props.data changes, I am setting the data to the rows field.  From the console log, I verify that I am receiving new sets of data.
If I go to the next page, props.data will be updated.  There's no error; however, the table becomes empty.
In the parent component, I can control what data I can pass to the DataTable component.  So when I pass in a new set of data, I got the following error.

**NOTE:  Even in your documentation, the server-side pagination is displaying blank when you try to go to the next page.**

![1](https://user-images.githubusercontent.com/8801186/99753148-af9a3980-2b20-11eb-808a-923177f67272.jpg)
![2](https://user-images.githubusercontent.com/8801186/99753159-b4f78400-2b20-11eb-8461-13d0a43c4b0d.jpg)

**Comment by oliviertassinari** [comment] 2020-11-20 11:45
Duplicate of #571

**Closed by oliviertassinari** 2020-11-20 11:45 UTC
Labels: duplicate

**Comment by raemounz** [comment] 2020-11-23 02:12
Still, the rows becomes blank when you go to the next pages.  Also, some erratic behavior happens where the table fires the "onPageChange" infinitely.  The documentation still shows blank on page change.
I advise to re-open this issue.

**Comment by oliviertassinari** [comment] 2020-11-23 11:19
> the rows become blank when you go to the next pages. 

Duplicate of #568?

> some erratic behavior happens where the table fires the "onPageChange" infinitely

Do you have a reproduction?
