### ISSUE TITLE
[DataGrid] Can't resolve '@material-ui/x-license' after updating to (4.0.0-alpha.36)

### ISSUE THREAD

**Issue by jdpst** [mui-org/material-ui-x#2297] opened 2021-08-07 12:26 UTC
> ModuleNotFoundError: Module not found: Error: Can't resolve '@material-ui/x-license'

when building with NextJS

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Build error as given above after updating to the latest alpha version.

## Expected Behavior 🤔

No errors.

## Steps to Reproduce 🕹

Steps

1. `npm i @material-ui/data-grid@4.0.0-alpha.36`
2. `npm run build` (i.e. `next build`)

**Comment by oliviertassinari** [comment] 2021-08-07 14:13
Duplicate of #2291

**Closed by oliviertassinari** 2021-08-07 14:13 UTC
Labels: status: needs triage

**Comment by jdpst** [comment] 2021-08-07 14:26
> Duplicate of #2291

My bad, not sure how I missed that one when searching.
